# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_project_dynamic_dialog.ui'
#
# Created: Sat Mar 20 11:10:38 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_NewProjectDynamicDialog(object):
    def setupUi(self, NewProjectDynamicDialog):
        NewProjectDynamicDialog.setObjectName("NewProjectDynamicDialog")
        NewProjectDynamicDialog.setWindowModality(QtCore.Qt.WindowModal)
        NewProjectDynamicDialog.resize(637, 273)
        self.verticalLayout = QtGui.QVBoxLayout(NewProjectDynamicDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_header = QtGui.QLabel(NewProjectDynamicDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_header.sizePolicy().hasHeightForWidth())
        self.lbl_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_header.setFont(font)
        self.lbl_header.setObjectName("lbl_header")
        self.verticalLayout.addWidget(self.lbl_header)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_error = QtGui.QLabel(NewProjectDynamicDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_error.sizePolicy().hasHeightForWidth())
        self.lbl_error.setSizePolicy(sizePolicy)
        self.lbl_error.setFrameShape(QtGui.QFrame.Panel)
        self.lbl_error.setFrameShadow(QtGui.QFrame.Raised)
        self.lbl_error.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lbl_error.setObjectName("lbl_error")
        self.horizontalLayout.addWidget(self.lbl_error)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.frame = QtGui.QFrame(NewProjectDynamicDialog)
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_project_name = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_project_name.sizePolicy().hasHeightForWidth())
        self.lbl_project_name.setSizePolicy(sizePolicy)
        self.lbl_project_name.setObjectName("lbl_project_name")
        self.gridLayout.addWidget(self.lbl_project_name, 0, 0, 1, 1)
        self.lbl_desc = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_desc.sizePolicy().hasHeightForWidth())
        self.lbl_desc.setSizePolicy(sizePolicy)
        self.lbl_desc.setObjectName("lbl_desc")
        self.gridLayout.addWidget(self.lbl_desc, 1, 0, 1, 1)
        self.le_project_description = QtGui.QLineEdit(self.frame)
        self.le_project_description.setObjectName("le_project_description")
        self.gridLayout.addWidget(self.le_project_description, 1, 1, 1, 1)
        self.le_project_name = QtGui.QLineEdit(self.frame)
        self.le_project_name.setObjectName("le_project_name")
        self.gridLayout.addWidget(self.le_project_name, 0, 1, 1, 1)
        self.lbl_project_filename = QtGui.QLabel(self.frame)
        self.lbl_project_filename.setObjectName("lbl_project_filename")
        self.gridLayout.addWidget(self.lbl_project_filename, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.le_project_filename = QtGui.QLineEdit(self.frame)
        self.le_project_filename.setObjectName("le_project_filename")
        self.horizontalLayout_4.addWidget(self.le_project_filename)
        self.tb_browse_folder = QtGui.QToolButton(self.frame)
        self.tb_browse_folder.setObjectName("tb_browse_folder")
        self.horizontalLayout_4.addWidget(self.tb_browse_folder)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.frame)
        self.groupBox = QtGui.QGroupBox(NewProjectDynamicDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dynamic_widgets = QtGui.QGridLayout()
        self.dynamic_widgets.setObjectName("dynamic_widgets")
        self.verticalLayout_3.addLayout(self.dynamic_widgets)
        self.verticalLayout.addWidget(self.groupBox)
        self.buttonBox = QtGui.QDialogButtonBox(NewProjectDynamicDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(NewProjectDynamicDialog)
        QtCore.QMetaObject.connectSlotsByName(NewProjectDynamicDialog)
        NewProjectDynamicDialog.setTabOrder(self.le_project_name, self.le_project_description)
        NewProjectDynamicDialog.setTabOrder(self.le_project_description, self.le_project_filename)
        NewProjectDynamicDialog.setTabOrder(self.le_project_filename, self.tb_browse_folder)
        NewProjectDynamicDialog.setTabOrder(self.tb_browse_folder, self.buttonBox)

    def retranslateUi(self, NewProjectDynamicDialog):
        NewProjectDynamicDialog.setWindowTitle(QtGui.QApplication.translate("NewProjectDynamicDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_header.setText(QtGui.QApplication.translate("NewProjectDynamicDialog", "Step 2 of 2: Creating new project based on X", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_error.setText(QtGui.QApplication.translate("NewProjectDynamicDialog", "<error message>", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_project_name.setText(QtGui.QApplication.translate("NewProjectDynamicDialog", "Project name:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_desc.setText(QtGui.QApplication.translate("NewProjectDynamicDialog", "Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_project_filename.setText(QtGui.QApplication.translate("NewProjectDynamicDialog", "Save to:", None, QtGui.QApplication.UnicodeUTF8))
        self.tb_browse_folder.setText(QtGui.QApplication.translate("NewProjectDynamicDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("NewProjectDynamicDialog", "Project specific options", None, QtGui.QApplication.UnicodeUTF8))

