# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_project_dynamic_dialog.ui'
#
# Created: Sat Mar 20 11:10:38 2010
#      by: PyQt5 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_NewProjectDynamicDialog(object):
    def setupUi(self, NewProjectDynamicDialog):
        NewProjectDynamicDialog.setObjectName("NewProjectDynamicDialog")
        NewProjectDynamicDialog.setWindowModality(QtCore.Qt.WindowModal)
        NewProjectDynamicDialog.resize(637, 273)
        self.verticalLayout = QtWidgets.QVBoxLayout(NewProjectDynamicDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_header = QtWidgets.QLabel(NewProjectDynamicDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_header.sizePolicy().hasHeightForWidth())
        self.lbl_header.setSizePolicy(sizePolicy)
        font = QtWidgets.QFont()
        font.setPointSize(14)
        self.lbl_header.setFont(font)
        self.lbl_header.setObjectName("lbl_header")
        self.verticalLayout.addWidget(self.lbl_header)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_error = QtWidgets.QLabel(NewProjectDynamicDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_error.sizePolicy().hasHeightForWidth())
        self.lbl_error.setSizePolicy(sizePolicy)
        self.lbl_error.setFrameShape(QtWidgets.QFrame.Panel)
        self.lbl_error.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl_error.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.lbl_error.setObjectName("lbl_error")
        self.horizontalLayout.addWidget(self.lbl_error)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.frame = QtWidgets.QFrame(NewProjectDynamicDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_project_name = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_project_name.sizePolicy().hasHeightForWidth())
        self.lbl_project_name.setSizePolicy(sizePolicy)
        self.lbl_project_name.setObjectName("lbl_project_name")
        self.gridLayout.addWidget(self.lbl_project_name, 0, 0, 1, 1)
        self.lbl_desc = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_desc.sizePolicy().hasHeightForWidth())
        self.lbl_desc.setSizePolicy(sizePolicy)
        self.lbl_desc.setObjectName("lbl_desc")
        self.gridLayout.addWidget(self.lbl_desc, 1, 0, 1, 1)
        self.le_project_description = QtWidgets.QLineEdit(self.frame)
        self.le_project_description.setObjectName("le_project_description")
        self.gridLayout.addWidget(self.le_project_description, 1, 1, 1, 1)
        self.le_project_name = QtWidgets.QLineEdit(self.frame)
        self.le_project_name.setObjectName("le_project_name")
        self.gridLayout.addWidget(self.le_project_name, 0, 1, 1, 1)
        self.lbl_project_filename = QtWidgets.QLabel(self.frame)
        self.lbl_project_filename.setObjectName("lbl_project_filename")
        self.gridLayout.addWidget(self.lbl_project_filename, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.le_project_filename = QtWidgets.QLineEdit(self.frame)
        self.le_project_filename.setObjectName("le_project_filename")
        self.horizontalLayout_4.addWidget(self.le_project_filename)
        self.tb_browse_folder = QtWidgets.QToolButton(self.frame)
        self.tb_browse_folder.setObjectName("tb_browse_folder")
        self.horizontalLayout_4.addWidget(self.tb_browse_folder)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.frame)
        self.groupBox = QtWidgets.QGroupBox(NewProjectDynamicDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dynamic_widgets = QtWidgets.QGridLayout()
        self.dynamic_widgets.setObjectName("dynamic_widgets")
        self.verticalLayout_3.addLayout(self.dynamic_widgets)
        self.verticalLayout.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(NewProjectDynamicDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(NewProjectDynamicDialog)
        QtCore.QMetaObject.connectSlotsByName(NewProjectDynamicDialog)
        NewProjectDynamicDialog.setTabOrder(self.le_project_name, self.le_project_description)
        NewProjectDynamicDialog.setTabOrder(self.le_project_description, self.le_project_filename)
        NewProjectDynamicDialog.setTabOrder(self.le_project_filename, self.tb_browse_folder)
        NewProjectDynamicDialog.setTabOrder(self.tb_browse_folder, self.buttonBox)

    def retranslateUi(self, NewProjectDynamicDialog):
        NewProjectDynamicDialog.setWindowTitle(QtWidgets.QApplication.translate("NewProjectDynamicDialog", "Dialog", None, QtWidgets.QApplication.UnicodeUTF8))
        self.lbl_header.setText(QtWidgets.QApplication.translate("NewProjectDynamicDialog", "Step 2 of 2: Creating new project based on X", None, QtWidgets.QApplication.UnicodeUTF8))
        self.lbl_error.setText(QtWidgets.QApplication.translate("NewProjectDynamicDialog", "<error message>", None, QtWidgets.QApplication.UnicodeUTF8))
        self.lbl_project_name.setText(QtWidgets.QApplication.translate("NewProjectDynamicDialog", "Project name:", None, QtWidgets.QApplication.UnicodeUTF8))
        self.lbl_desc.setText(QtWidgets.QApplication.translate("NewProjectDynamicDialog", "Description:", None, QtWidgets.QApplication.UnicodeUTF8))
        self.lbl_project_filename.setText(QtWidgets.QApplication.translate("NewProjectDynamicDialog", "Save to:", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tb_browse_folder.setText(QtWidgets.QApplication.translate("NewProjectDynamicDialog", "...", None, QtWidgets.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("NewProjectDynamicDialog", "Project specific options", None, QtWidgets.QApplication.UnicodeUTF8))

