~/ urbansim_misc.dat
~/ This macro:
~/ 1) Sets the output format to 8.4
~/ 2) Outputs the named full matrices (up to 9)
~/    for the i,j pairs 1-932, 1-932.
~/ 3) - - to the new file usimout.dat
~/ 4) And exits both the program and EMME/2
~/
~!if exist urbansim_misc.datt erase urbansim_misc.dat
reports=?
3.14
~+|4|2|8,4|y|4|n
~+|1|3
avehda
au1tim
hbwdap
hbwtwp
atrnst
atrtwa
~+|||y|1,938||1,938||2|urbansim_misc.dat
q
q
