~/ usimoutq.mac
~/ This macro:
~/ 1) Sets the output format to 8.4
~/ 2) Outputs the named full matrices (up to 9)
~/    for the i,j pairs 1-932, 1-932.
~/ 3) - - to the new file travel_times.dat
~/ 4) And exits both the program and EMME/2
~/
~!if exist travel_times.dat erase travel_times.dat
reports=?
3.14
~+|4|2|8,4|n|4|n
~+|1|3
au1tim
~+|||y|1,938||1,938||2|travel_times.dat
q
q
