# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Documents and Settings\Christoffer Klang\My Documents\workspace\opus_trunk\opus_gui\general_manager\views\variable_library.ui'
#
# Created: Thu Jun 11 12:39:44 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_VariableLibrary(object):
    def setupUi(self, VariableLibrary):
        VariableLibrary.setObjectName("VariableLibrary")
        VariableLibrary.resize(914, 598)
        VariableLibrary.setSizeGripEnabled(True)
        self.verticalLayout = QtGui.QVBoxLayout(VariableLibrary)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(VariableLibrary)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.cbo_dataset_filter = QtGui.QComboBox(VariableLibrary)
        self.cbo_dataset_filter.setMinimumSize(QtCore.QSize(200, 0))
        self.cbo_dataset_filter.setObjectName("cbo_dataset_filter")
        self.horizontalLayout_2.addWidget(self.cbo_dataset_filter)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.table_container = QtGui.QVBoxLayout()
        self.table_container.setObjectName("table_container")
        self.verticalLayout.addLayout(self.table_container)
        self.group_progress = QtGui.QGroupBox(VariableLibrary)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_progress.sizePolicy().hasHeightForWidth())
        self.group_progress.setSizePolicy(sizePolicy)
        self.group_progress.setObjectName("group_progress")
        self.horizontalLayout = QtGui.QHBoxLayout(self.group_progress)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progress_validation = QtGui.QProgressBar(self.group_progress)
        self.progress_validation.setProperty("value", QtCore.QVariant(100))
        self.progress_validation.setTextVisible(True)
        self.progress_validation.setObjectName("progress_validation")
        self.horizontalLayout.addWidget(self.progress_validation)
        self.pb_cancel_validation = QtGui.QPushButton(self.group_progress)
        self.pb_cancel_validation.setDefault(True)
        self.pb_cancel_validation.setObjectName("pb_cancel_validation")
        self.horizontalLayout.addWidget(self.pb_cancel_validation)
        self.verticalLayout.addWidget(self.group_progress)
        self.widget = QtGui.QWidget(VariableLibrary)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.hboxlayout = QtGui.QHBoxLayout(self.widget)
        self.hboxlayout.setObjectName("hboxlayout")
        self.pb_create_new = QtGui.QPushButton(self.widget)
        self.pb_create_new.setEnabled(True)
        self.pb_create_new.setObjectName("pb_create_new")
        self.hboxlayout.addWidget(self.pb_create_new)
        self.line_2 = QtGui.QFrame(self.widget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.hboxlayout.addWidget(self.line_2)
        self.pb_validate_selected = QtGui.QPushButton(self.widget)
        self.pb_validate_selected.setObjectName("pb_validate_selected")
        self.hboxlayout.addWidget(self.pb_validate_selected)
        self.pb_problems = QtGui.QPushButton(self.widget)
        self.pb_problems.setEnabled(False)
        self.pb_problems.setObjectName("pb_problems")
        self.hboxlayout.addWidget(self.pb_problems)
        spacerItem1 = QtGui.QSpacerItem(441, 24, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.line = QtGui.QFrame(self.widget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.hboxlayout.addWidget(self.line)
        self.pb_close = QtGui.QPushButton(self.widget)
        self.pb_close.setAutoDefault(False)
        self.pb_close.setDefault(False)
        self.pb_close.setObjectName("pb_close")
        self.hboxlayout.addWidget(self.pb_close)
        self.pb_apply = QtGui.QPushButton(self.widget)
        self.pb_apply.setEnabled(True)
        self.pb_apply.setObjectName("pb_apply")
        self.hboxlayout.addWidget(self.pb_apply)
        self.pb_apply_and_close = QtGui.QPushButton(self.widget)
        self.pb_apply_and_close.setAutoDefault(True)
        self.pb_apply_and_close.setDefault(True)
        self.pb_apply_and_close.setObjectName("pb_apply_and_close")
        self.hboxlayout.addWidget(self.pb_apply_and_close)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(VariableLibrary)
        QtCore.QMetaObject.connectSlotsByName(VariableLibrary)

    def retranslateUi(self, VariableLibrary):
        VariableLibrary.setWindowTitle(QtGui.QApplication.translate("VariableLibrary", "Variable Library", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("VariableLibrary", "Show variables from dataset:", None, QtGui.QApplication.UnicodeUTF8))
        self.group_progress.setTitle(QtGui.QApplication.translate("VariableLibrary", "Validating variables", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_cancel_validation.setText(QtGui.QApplication.translate("VariableLibrary", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_create_new.setText(QtGui.QApplication.translate("VariableLibrary", "Create Variable", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_validate_selected.setToolTip(QtGui.QApplication.translate("VariableLibrary", "Checks all variable syntax and makes sure that it can be computed on the baseyear data.", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_validate_selected.setText(QtGui.QApplication.translate("VariableLibrary", "Validate Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_problems.setText(QtGui.QApplication.translate("VariableLibrary", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_close.setText(QtGui.QApplication.translate("VariableLibrary", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_apply.setText(QtGui.QApplication.translate("VariableLibrary", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_apply_and_close.setText(QtGui.QApplication.translate("VariableLibrary", "Apply and Close", None, QtGui.QApplication.UnicodeUTF8))

