# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'variable_editor.ui'
#
# Created: Mon Feb 09 18:29:30 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_VariableEditor(object):
    def setupUi(self, VariableEditor):
        VariableEditor.setObjectName("VariableEditor")
        VariableEditor.resize(520, 376)
        VariableEditor.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalLayout = QtGui.QVBoxLayout(VariableEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameWidget = QtGui.QWidget(VariableEditor)
        self.nameWidget.setObjectName("nameWidget")
        self._4 = QtGui.QHBoxLayout(self.nameWidget)
        self._4.setObjectName("_4")
        self.label = QtGui.QLabel(self.nameWidget)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setObjectName("label")
        self._4.addWidget(self.label)
        self.leVarName = QtGui.QLineEdit(self.nameWidget)
        self.leVarName.setObjectName("leVarName")
        self._4.addWidget(self.leVarName)
        self.verticalLayout.addWidget(self.nameWidget)
        self.sourceWidget = QtGui.QWidget(VariableEditor)
        self.sourceWidget.setObjectName("sourceWidget")
        self._2 = QtGui.QHBoxLayout(self.sourceWidget)
        self._2.setObjectName("_2")
        self.label_4 = QtGui.QLabel(self.sourceWidget)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_4.setObjectName("label_4")
        self._2.addWidget(self.label_4)
        self.cboVarType = QtGui.QComboBox(self.sourceWidget)
        self.cboVarType.setObjectName("cboVarType")
        self.cboVarType.addItem(QtCore.QString())
        self.cboVarType.addItem(QtCore.QString())
        self.cboVarType.addItem(QtCore.QString())
        self._2.addWidget(self.cboVarType)
        self.verticalLayout.addWidget(self.sourceWidget)
        self.rbUseIndicator = QtGui.QRadioButton(VariableEditor)
        self.rbUseIndicator.setObjectName("rbUseIndicator")
        self.verticalLayout.addWidget(self.rbUseIndicator)
        self.rbUseModel = QtGui.QRadioButton(VariableEditor)
        self.rbUseModel.setObjectName("rbUseModel")
        self.verticalLayout.addWidget(self.rbUseModel)
        self.rbUseBoth = QtGui.QRadioButton(VariableEditor)
        self.rbUseBoth.setObjectName("rbUseBoth")
        self.verticalLayout.addWidget(self.rbUseBoth)
        self.definitionWidget = QtGui.QWidget(VariableEditor)
        self.definitionWidget.setObjectName("definitionWidget")
        self._3 = QtGui.QHBoxLayout(self.definitionWidget)
        self._3.setObjectName("_3")
        self.label_5 = QtGui.QLabel(self.definitionWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_5.setObjectName("label_5")
        self._3.addWidget(self.label_5)
        self.txtVarDef = QtGui.QTextEdit(self.definitionWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtVarDef.sizePolicy().hasHeightForWidth())
        self.txtVarDef.setSizePolicy(sizePolicy)
        self.txtVarDef.setBaseSize(QtCore.QSize(0, 20))
        self.txtVarDef.setTabChangesFocus(True)
        self.txtVarDef.setAcceptRichText(False)
        self.txtVarDef.setObjectName("txtVarDef")
        self._3.addWidget(self.txtVarDef)
        self.verticalLayout.addWidget(self.definitionWidget)
        self.widget = QtGui.QWidget(VariableEditor)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 45))
        self.widget.setObjectName("widget")
        self.hboxlayout = QtGui.QHBoxLayout(self.widget)
        self.hboxlayout.setObjectName("hboxlayout")
        self.btnCheckSyntax = QtGui.QPushButton(self.widget)
        self.btnCheckSyntax.setObjectName("btnCheckSyntax")
        self.hboxlayout.addWidget(self.btnCheckSyntax)
        self.btnCheckData = QtGui.QPushButton(self.widget)
        self.btnCheckData.setObjectName("btnCheckData")
        self.hboxlayout.addWidget(self.btnCheckData)
        spacerItem = QtGui.QSpacerItem(441, 24, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.buttonBox = QtGui.QDialogButtonBox(self.widget)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.hboxlayout.addWidget(self.buttonBox)
        self.line = QtGui.QFrame(self.widget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.hboxlayout.addWidget(self.line)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(VariableEditor)
        QtCore.QMetaObject.connectSlotsByName(VariableEditor)

    def retranslateUi(self, VariableEditor):
        VariableEditor.setWindowTitle(QtGui.QApplication.translate("VariableEditor", "Variable editor", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setToolTip(QtGui.QApplication.translate("VariableEditor", "A name for this variable. Use only alphanumeric characters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("VariableEditor", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setToolTip(QtGui.QApplication.translate("VariableEditor", "Where the variable definition derives from. \n"
"An \"expression\" uses the Tekoa domain-specific language, \n"
"\"python class\" is a path to a variable defined in a python module (e.g. urbansim.gridcell.population), \n"
"and \"primary attribute\" refers to a primary attribute of the given dataset. ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("VariableEditor", "Variable type:", None, QtGui.QApplication.UnicodeUTF8))
        self.cboVarType.setItemText(0, QtGui.QApplication.translate("VariableEditor", "expression", None, QtGui.QApplication.UnicodeUTF8))
        self.cboVarType.setItemText(1, QtGui.QApplication.translate("VariableEditor", "primary attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.cboVarType.setItemText(2, QtGui.QApplication.translate("VariableEditor", "Python class", None, QtGui.QApplication.UnicodeUTF8))
        self.rbUseIndicator.setText(QtGui.QApplication.translate("VariableEditor", "Use variable as an indicator", None, QtGui.QApplication.UnicodeUTF8))
        self.rbUseModel.setText(QtGui.QApplication.translate("VariableEditor", "Use variable in a model", None, QtGui.QApplication.UnicodeUTF8))
        self.rbUseBoth.setText(QtGui.QApplication.translate("VariableEditor", "Use variable both in a model and as an indicator", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("VariableEditor", "Definition:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCheckSyntax.setToolTip(QtGui.QApplication.translate("VariableEditor", "Verify that the syntax of variable definition parses correctly.", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCheckSyntax.setText(QtGui.QApplication.translate("VariableEditor", "Check syntax", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCheckData.setToolTip(QtGui.QApplication.translate("VariableEditor", "Verify that the variable can be computed against the baseyear data for this project.", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCheckData.setText(QtGui.QApplication.translate("VariableEditor", "Check against data", None, QtGui.QApplication.UnicodeUTF8))

