# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Documents and Settings\Christoffer Klang\My Documents\workspace\opus_trunk\opus_gui\general_manager\views\variable_library.ui'
#
# Created: Thu Jun 11 12:39:44 2009
#      by: PyQt5 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_VariableLibrary(object):
    def setupUi(self, VariableLibrary):
        VariableLibrary.setObjectName("VariableLibrary")
        VariableLibrary.resize(914, 598)
        VariableLibrary.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(VariableLibrary)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(VariableLibrary)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.cbo_dataset_filter = QtWidgets.QComboBox(VariableLibrary)
        self.cbo_dataset_filter.setMinimumSize(QtCore.QSize(200, 0))
        self.cbo_dataset_filter.setObjectName("cbo_dataset_filter")
        self.horizontalLayout_2.addWidget(self.cbo_dataset_filter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.table_container = QtWidgets.QVBoxLayout()
        self.table_container.setObjectName("table_container")
        self.verticalLayout.addLayout(self.table_container)
        self.group_progress = QtWidgets.QGroupBox(VariableLibrary)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_progress.sizePolicy().hasHeightForWidth())
        self.group_progress.setSizePolicy(sizePolicy)
        self.group_progress.setObjectName("group_progress")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.group_progress)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progress_validation = QtWidgets.QProgressBar(self.group_progress)
        self.progress_validation.setProperty("value", QtCore.QVariant(100))
        self.progress_validation.setTextVisible(True)
        self.progress_validation.setObjectName("progress_validation")
        self.horizontalLayout.addWidget(self.progress_validation)
        self.pb_cancel_validation = QtWidgets.QPushButton(self.group_progress)
        self.pb_cancel_validation.setDefault(True)
        self.pb_cancel_validation.setObjectName("pb_cancel_validation")
        self.horizontalLayout.addWidget(self.pb_cancel_validation)
        self.verticalLayout.addWidget(self.group_progress)
        self.widget = QtWidgets.QWidget(VariableLibrary)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.widget)
        self.hboxlayout.setObjectName("hboxlayout")
        self.pb_create_new = QtWidgets.QPushButton(self.widget)
        self.pb_create_new.setEnabled(True)
        self.pb_create_new.setObjectName("pb_create_new")
        self.hboxlayout.addWidget(self.pb_create_new)
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.hboxlayout.addWidget(self.line_2)
        self.pb_validate_selected = QtWidgets.QPushButton(self.widget)
        self.pb_validate_selected.setObjectName("pb_validate_selected")
        self.hboxlayout.addWidget(self.pb_validate_selected)
        self.pb_problems = QtWidgets.QPushButton(self.widget)
        self.pb_problems.setEnabled(False)
        self.pb_problems.setObjectName("pb_problems")
        self.hboxlayout.addWidget(self.pb_problems)
        spacerItem1 = QtWidgets.QSpacerItem(441, 24, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.hboxlayout.addWidget(self.line)
        self.pb_close = QtWidgets.QPushButton(self.widget)
        self.pb_close.setAutoDefault(False)
        self.pb_close.setDefault(False)
        self.pb_close.setObjectName("pb_close")
        self.hboxlayout.addWidget(self.pb_close)
        self.pb_apply = QtWidgets.QPushButton(self.widget)
        self.pb_apply.setEnabled(True)
        self.pb_apply.setObjectName("pb_apply")
        self.hboxlayout.addWidget(self.pb_apply)
        self.pb_apply_and_close = QtWidgets.QPushButton(self.widget)
        self.pb_apply_and_close.setAutoDefault(True)
        self.pb_apply_and_close.setDefault(True)
        self.pb_apply_and_close.setObjectName("pb_apply_and_close")
        self.hboxlayout.addWidget(self.pb_apply_and_close)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(VariableLibrary)
        QtCore.QMetaObject.connectSlotsByName(VariableLibrary)

    def retranslateUi(self, VariableLibrary):
        VariableLibrary.setWindowTitle(QtWidgets.QApplication.translate("VariableLibrary", "Variable Library", None))
        self.label.setText(QtWidgets.QApplication.translate("VariableLibrary", "Show variables from dataset:", None))
        self.group_progress.setTitle(QtWidgets.QApplication.translate("VariableLibrary", "Validating variables", None))
        self.pb_cancel_validation.setText(QtWidgets.QApplication.translate("VariableLibrary", "Cancel", None))
        self.pb_create_new.setText(QtWidgets.QApplication.translate("VariableLibrary", "Create Variable", None))
        self.pb_validate_selected.setToolTip(QtWidgets.QApplication.translate("VariableLibrary", "Checks all variable syntax and makes sure that it can be computed on the baseyear data.", None))
        self.pb_validate_selected.setText(QtWidgets.QApplication.translate("VariableLibrary", "Validate Selected", None))
        self.pb_problems.setText(QtWidgets.QApplication.translate("VariableLibrary", "0", None))
        self.pb_close.setText(QtWidgets.QApplication.translate("VariableLibrary", "Close", None))
        self.pb_apply.setText(QtWidgets.QApplication.translate("VariableLibrary", "Apply", None))
        self.pb_apply_and_close.setText(QtWidgets.QApplication.translate("VariableLibrary", "Apply and Close", None))

