# PopGen 1.1 is A Synthetic Population Generator for Advanced
# Microsimulation Models of Travel Demand 
# Copyright (C) 2009, Arizona State University
# See PopGen/License

DEFAULT_PERSON_PUMS2000_QUERIES = [ "alter table person_pums add column agep bigint",
                                "alter table person_pums add column gender bigint",
                                "alter table person_pums add column race bigint",
                                "alter table person_pums add column employment bigint",
                                "update person_pums set agep = 1 where age < 5",
                                "update person_pums set agep = 2 where age >= 5 and age < 15",
                                "update person_pums set agep = 3 where age >= 15 and age < 25",
                                "update person_pums set agep = 4 where age >= 25 and age < 35",
                                "update person_pums set agep = 5 where age >= 35 and age < 45",
                                "update person_pums set agep = 6 where age >= 45 and age < 55",
                                "update person_pums set agep = 7 where age >= 55 and age < 65",
                                "update person_pums set agep = 8 where age >= 65 and age < 75",
                                "update person_pums set agep = 9 where age >= 75 and age < 85",
                                "update person_pums set agep = 10 where age >= 85",
                                "update person_pums set gender = sex",
                                "update person_pums set race = 1 where race1 = 1",
                                "update person_pums set race = 2 where race1 = 2",
                                "update person_pums set race = 3 where race1 >=3 and race1 <= 5",
                                "update person_pums set race = 4 where race1 = 6",
                                "update person_pums set race = 5 where race1 = 7",
                                "update person_pums set race = 6 where race1 = 8",
                                "update person_pums set race = 7 where race1 = 9",
                                "update person_pums set employment = 1 where esr = 0",
                                "update person_pums set employment = 2 where esr = 1 or esr = 2 or esr = 4 or esr = 5",
                                "update person_pums set employment = 3 where esr = 3",
                                "update person_pums set employment = 4 where esr = 6",
                                "drop table person_sample",
                                "create table person_sample select state, pumano, hhid, serialno, pnum, agep, gender, race, employment, relate from person_pums",
                                "alter table person_sample add index(serialno, pnum)",
                                "drop table hhld_sample_temp",
                                "alter table hhld_sample drop column hhldrage",
                                "alter table hhld_sample rename to hhld_sample_temp",
                                "drop table hhld_sample",
                                "create table hhld_sample select hhld_sample_temp.*, agep as hhldrage from hhld_sample_temp left join person_sample using(serialno) where relate = 1",
                                "alter table hhld_sample add index(serialno)",
                                "update hhld_sample set hhldrage = 1 where hhldrage <=7 ",
                                "update hhld_sample set hhldrage = 2 where hhldrage >7"]

DEFAULT_PERSON_PUMSACS_QUERIES = ["alter table person_pums change agep age bigint",
                                  "alter table person_pums change puma pumano bigint",
                                  "alter table person_pums change rac1p race1 bigint",
                                  "alter table person_pums change st state bigint",
                                  "alter table person_pums change sporder pnum bigint",
                                  "alter table person_pums change rel relate bigint",

                                  "alter table person_pums add column agep bigint",
                                  "alter table person_pums add column gender bigint",
                                  "alter table person_pums add column race bigint",
                                  "alter table person_pums add column employment bigint",
                                  "update person_pums set agep = 1 where age < 5",
                                  "update person_pums set agep = 2 where age >= 5 and age < 15",
                                  "update person_pums set agep = 3 where age >= 15 and age < 25",
                                  "update person_pums set agep = 4 where age >= 25 and age < 35",
                                  "update person_pums set agep = 5 where age >= 35 and age < 45",
                                  "update person_pums set agep = 6 where age >= 45 and age < 55",
                                  "update person_pums set agep = 7 where age >= 55 and age < 65",
                                  "update person_pums set agep = 8 where age >= 65 and age < 75",
                                  "update person_pums set agep = 9 where age >= 75 and age < 85",
                                  "update person_pums set agep = 10 where age >= 85",
                                  "update person_pums set gender = sex",
                                  "update person_pums set race = 1 where race1 = 1",
                                  "update person_pums set race = 2 where race1 = 2",
                                  "update person_pums set race = 3 where race1 >=3 and race1 <= 5",
                                  "update person_pums set race = 4 where race1 = 6",
                                  "update person_pums set race = 5 where race1 = 7",
                                  "update person_pums set race = 6 where race1 = 8",
                                  "update person_pums set race = 7 where race1 = 9",
                                  "update person_pums set employment = 1 where esr = 0",
                                  "update person_pums set employment = 2 where esr = 1 or esr = 2 or esr = 4 or esr = 5",
                                  "update person_pums set employment = 3 where esr = 3",
                                  "update person_pums set employment = 4 where esr = 6",


                                  "alter table person_pums add index(serialno)",

                                   "create table person_pums1 select person_pums.*, hhid from person_pums left join serialcorr using(serialno)",
                                  "update person_pums1 set serialno = hhid",

                                  "drop table person_sample",

                                  "create table person_sample select state, pumano, hhid, serialno, pnum, agep, gender, race, employment, relate from person_pums1",
                                  "alter table person_sample add index(serialno, pnum)",

                                  "drop table hhld_sample_temp",
                                  "alter table hhld_sample drop column hhldrage",
                                  "alter table hhld_sample rename to hhld_sample_temp",
                                  "drop table hhld_sample",
                                  "create table hhld_sample select hhld_sample_temp.*, agep as hhldrage from hhld_sample_temp left join person_sample using(serialno) where relate = 0",
                                  "alter table hhld_sample add index(serialno)",
                                  "update hhld_sample set hhldrage = 1 where hhldrage <=7 ",
                                  "update hhld_sample set hhldrage = 2 where hhldrage >7",
                                  "drop table hhld_sample_temp",
                                  "drop table person_pums1"]


DEFAULT_HOUSING_PUMS2000_QUERIES = ["alter table housing_pums add index(serialno)",
                                "alter table housing_pums add column hhtype bigint",
                                "alter table housing_pums add column hhldtype bigint",
                                "alter table housing_pums add column hhldinc bigint",
                                "alter table housing_pums add column hhldtenure bigint",
                                "alter table housing_pums add column hhldsize bigint",
                                "alter table housing_pums add column childpresence bigint",
                                "alter table housing_pums add column groupquarter bigint",
                                "alter table housing_pums add column hhldfam bigint",
                        
                                "update housing_pums set hhtype = 1 where unittype = 0",
                                "update housing_pums set hhtype = 2 where unittype = 1 or unittype = 2",
                                "update housing_pums set hhldtype = 1 where hht = 1",
                                "update housing_pums set hhldtype = 2 where hht = 2",
                                "update housing_pums set hhldtype = 3 where hht = 3",
                                "update housing_pums set hhldtype = 4 where hht = 4 or hht = 5",
                                "update housing_pums set hhldtype = 5 where hht = 6 or hht = 7",
                                "update housing_pums set hhldtype = -99 where hht = 0",
                                "update housing_pums set hhldinc = 1 where hinc <15000",
                                "update housing_pums set hhldinc = 2 where hinc >= 15000 and hinc < 25000",
                                "update housing_pums set hhldinc = 3 where hinc >= 25000 and hinc < 35000",
                                "update housing_pums set hhldinc = 4 where hinc >= 35000 and hinc < 45000",
                                "update housing_pums set hhldinc = 5 where hinc >= 45000 and hinc < 60000",
                                "update housing_pums set hhldinc = 6 where hinc >= 60000 and hinc < 100000",
                                "update housing_pums set hhldinc = 7 where hinc >= 100000 and hinc < 150000",
                                "update housing_pums set hhldinc = 8 where hinc >= 150000",
                                "update housing_pums set hhldinc = -99 where hht = 0",                          
                                #"update housing_pums set hhldtenure = 1 where tenure = 1 or tenure = 2",
                                #"update housing_pums set hhldtenure = 2 where tenure = 3 or tenure = 4",
                                #"update housing_pums set hhldtenure = -99 where tenure = 0",                          
                                "update housing_pums set hhldsize = persons where persons < 7",
                                "update housing_pums set hhldsize = 7 where persons >= 7",
                                "update housing_pums set hhldsize = -99 where hht = 0",                          
                                "update housing_pums set childpresence = 1 where noc > 0",
                                "update housing_pums set childpresence = 2 where noc = 0",
                                "update housing_pums set childpresence = -99 where hht = 0",                          
                                "update housing_pums set groupquarter = unittype where unittype >0",
                                "update housing_pums set groupquarter = -99 where unittype =0",
                                
                                "update housing_pums set hhldfam = 1 where hhldtype <=3",
                                "update housing_pums set hhldfam = 2 where hhldtype > 3",

                                "delete from housing_pums where persons = 0",
                                "drop table hhld_sample",
                                "drop table gq_sample",
                                "create table hhld_sample select state, pumano, hhid, serialno, hhtype, hhldtype, hhldinc, hhldsize, childpresence, hhldfam from housing_pums where hhtype = 1",
                                "create table gq_sample select state, pumano, hhid, serialno, hhtype, groupquarter from housing_pums where hhtype = 2",
                                "alter table hhld_sample add index(serialno)",
                                "alter table gq_sample add index(serialno)"]


DEFAULT_HOUSING_PUMSACS_QUERIES = ["alter table housing_pums add index(serialno)",
                                   "alter table housing_pums change hincp hinc bigint",
                                   "alter table housing_pums change np persons bigint",
                                   "alter table housing_pums change hupaoc noc bigint",
                                   "alter table housing_pums change type unittype bigint",
                                   "alter table housing_pums change st state bigint",
                                   "alter table housing_pums change puma pumano bigint",
                                   
                                   "alter table housing_pums add column hhtype bigint",
                                   "alter table housing_pums add column hhldtype bigint",
                                   "alter table housing_pums add column hhldinc bigint",
                                   "alter table housing_pums add column hhldtenure bigint",
                                   "alter table housing_pums add column hhldsize bigint",
                                   "alter table housing_pums add column childpresence bigint",
                                   "alter table housing_pums add column groupquarter bigint",
                                   "alter table housing_pums add column hhldfam bigint",
                                   
                                   "update housing_pums set hhtype = 1 where unittype = 1",
                                   "update housing_pums set hhtype = 2 where unittype = 2 or unittype = 3",
                                   "update housing_pums set hhldtype = 1 where hht = 1",
                                   "update housing_pums set hhldtype = 2 where hht = 2",
                                   "update housing_pums set hhldtype = 3 where hht = 3",
                                   "update housing_pums set hhldtype = 4 where hht = 4 or hht = 6",
                                   "update housing_pums set hhldtype = 5 where hht = 5 or hht = 7",
                                   "update housing_pums set hhldtype = -99 where hht = 0",
                                   "update housing_pums set hhldinc = 1 where hinc <15000",
                                   "update housing_pums set hhldinc = 2 where hinc >= 15000 and hinc < 25000",
                                   "update housing_pums set hhldinc = 3 where hinc >= 25000 and hinc < 35000",
                                   "update housing_pums set hhldinc = 4 where hinc >= 35000 and hinc < 45000",
                                   "update housing_pums set hhldinc = 5 where hinc >= 45000 and hinc < 60000",
                                   "update housing_pums set hhldinc = 6 where hinc >= 60000 and hinc < 100000",
                                   "update housing_pums set hhldinc = 7 where hinc >= 100000 and hinc < 150000",
                                   "update housing_pums set hhldinc = 8 where hinc >= 150000",
                                   "update housing_pums set hhldinc = -99 where hht = 0",                          
                                   #"update housing_pums set hhldtenure = 1 where tenure = 1 or tenure = 2",
                                   #"update housing_pums set hhldtenure = 2 where tenure = 3 or tenure = 4",
                                   #"update housing_pums set hhldtenure = -99 where tenure = 0",                          
                                   "update housing_pums set hhldsize = persons where persons < 7",
                                   "update housing_pums set hhldsize = 7 where persons >= 7",
                                   "update housing_pums set hhldsize = -99 where hht = 0",                          
                                   "update housing_pums set childpresence = 1 where noc =1 or noc = 2 or noc = 3",
                                   "update housing_pums set childpresence = 2 where noc = 4",
                                   "update housing_pums set childpresence = -99 where hht = 0",                          
                                   "update housing_pums set groupquarter = 1 where unittype >1",
                                   "update housing_pums set groupquarter = -99 where unittype =1",
                                   
                                   "update housing_pums set hhldfam = 1 where hhldtype <=3",
                                   "update housing_pums set hhldfam = 2 where hhldtype > 3",

                                   "delete from housing_pums where persons = 0",
                                   "drop table serialcorr",
                                   "create table serialcorr select state, pumano, serialno from housing_pums group by serialno",
                                   "alter table serialcorr add column hhid bigint primary key auto_increment not null",
                                   "alter table serialcorr add index(serialno)",
                                   
                                   
                                   "drop table hhld_sample",
                                   "drop table gq_sample",

                                   "alter table housing_pums add index(serialno)",

                                   "create table housing_pums1 select housing_pums.*, hhid from housing_pums left join serialcorr using(serialno)",
                                   "update housing_pums1 set serialno = hhid",

                                   "create table hhld_sample select state, pumano, hhid, serialno, hhtype, hhldtype, hhldinc, hhldsize, childpresence, hhldfam from housing_pums1 where hhtype = 1",
                                   "create table gq_sample select state, pumano, hhid, serialno, hhtype, groupquarter from housing_pums1 where hhtype = 2",


                                   "alter table hhld_sample add index(serialno)",
                                   "alter table gq_sample add index(serialno)",
                                   "drop table housing_pums1"]

DEFAULT_SF2000_QUERIES = ["alter table %s add column agep1 bigint",
                          "alter table %s add column agep2 bigint",
                          "alter table %s add column agep3 bigint",
                          "alter table %s add column agep4 bigint",
                          "alter table %s add column agep5 bigint",
                          "alter table %s add column agep6 bigint",
                          "alter table %s add column agep7 bigint",
                          "alter table %s add column agep8 bigint",
                          "alter table %s add column agep9 bigint",
                          "alter table %s add column agep10 bigint",
                          "alter table %s add column gender1 bigint",
                          "alter table %s add column gender2 bigint",
                          "alter table %s add column race1 bigint",
                          "alter table %s add column race2 bigint",
                          "alter table %s add column race3 bigint",
                          "alter table %s add column race4 bigint",
                          "alter table %s add column race5 bigint",
                          "alter table %s add column race6 bigint",
                          "alter table %s add column race7 bigint",
                          "alter table %s add column employment1 bigint",
                          "alter table %s add column employment2 bigint",
                          "alter table %s add column employment3 bigint",
                          "alter table %s add column employment4 bigint",
                          "alter table %s add column childpresence1 bigint",
                          "alter table %s add column childpresence2 bigint",
                          "alter table %s add column groupquarter1 bigint",
                          "alter table %s add column groupquarter2 bigint",
                          "alter table %s add column hhldinc1 bigint",
                          "alter table %s add column hhldinc2 bigint",
                          "alter table %s add column hhldinc3 bigint",
                          "alter table %s add column hhldinc4 bigint",
                          "alter table %s add column hhldinc5 bigint",
                          "alter table %s add column hhldinc6 bigint",
                          "alter table %s add column hhldinc7 bigint",
                          "alter table %s add column hhldinc8 bigint",
                          "alter table %s add column hhldsize1 bigint",
                          "alter table %s add column hhldsize2 bigint",
                          "alter table %s add column hhldsize3 bigint",
                          "alter table %s add column hhldsize4 bigint",
                          "alter table %s add column hhldsize5 bigint",
                          "alter table %s add column hhldsize6 bigint",
                          "alter table %s add column hhldsize7 bigint",
                          "alter table %s add column hhldtype1 bigint",
                          "alter table %s add column hhldtype2 bigint",
                          "alter table %s add column hhldtype3 bigint",
                          "alter table %s add column hhldtype4 bigint",
                          "alter table %s add column hhldtype5 bigint",
                          "alter table %s add column hhldrage1 bigint",
                          "alter table %s add column hhldrage2 bigint",
                          "alter table %s add column hhldfam1 bigint",
                          "alter table %s add column hhldfam2 bigint",
                          
                          
                          "update %s set agep1 = (P008003+P008004+P008005+P008006+P008007) + (P008042+P008043+P008044+P008045+P008046)",
                          "update %s set agep2 = (P008008+P008009+P008010+P008011+P008012+P008013+P008014+P008015+P008016+P008017 ) + (P008047+P008048+P008049+P008050+P008051+P008052+P008053+P008054+P008055+P008056)",
                          "update %s set agep3 = (P008018+P008019+P008020+P008021+P008022+P008023+P008024+P008025 ) + (P008057+P008058+P008059+P008060+P008061+P008062+P008063+P008064)",
                          "update %s set agep4 = (P008026+P008027) + (P008065+P008066)",
                          "update %s set agep5 = (P008028+P008029) + (P008067+P008068)",
                          "update %s set agep6 = (P008030+P008031) + (P008069+P008070)",
                          "update %s set agep7 = (P008032+P008033+P008034) + (P008071+P008072+P008073)",
                          "update %s set agep8 = (P008035+P008036+P008037) + (P008074+P008075+P008076)",
                          "update %s set agep9 = (P008038+P008039) + (P008077+P008078)",
                          "update %s set agep10 = (P008040) + (P008079)",
                          "update %s set gender1 = P008002", 
                          "update %s set gender2 = P008041", 
                          "update %s set race1 = P006002",
                          "update %s set race2 = P006003",
                          "update %s set race3 = P006004",
                          "update %s set race4 = P006005",
                          "update %s set race5 = P006006",
                          "update %s set race6 = P006007",
                          "update %s set race7 = P006008",
                          "update %s set employment1 = agep1+agep2+P008018+P008057",
                          "update %s set employment2 = P043004+P043006+P043011+P043013",
                          "update %s set employment3 = P043007+P043014",
                          "update %s set employment4 = P043008+P043015",
                          "update %s set childpresence1 = P010008 + P010012 + P010015",
                          "update %s set childpresence2 = P010009 + P010013 + P010016 + P010017 + P010002",
                          "update %s set groupquarter1 = P009026",
                          "update %s set groupquarter2 = P009027",
                          "update %s set hhldinc1 = P052002 + P052003",
                          "update %s set hhldinc2 = P052004 + P052005",
                          "update %s set hhldinc3 = P052006 + P052007",
                          "update %s set hhldinc4 = P052008 + P052009",
                          "update %s set hhldinc5 = P052010 + P052011",
                          "update %s set hhldinc6 = P052012 + P052013",
                          "update %s set hhldinc7 = P052014 + P052015",
                          "update %s set hhldinc8 = P052016 + P052017",
                          "update %s set hhldsize1 = P014010 ",
                          "update %s set hhldsize2 = P014003+P014011 ",
                          "update %s set hhldsize3 = P014004+P014012 ",
                          "update %s set hhldsize4 = P014005+P014013 ",
                          "update %s set hhldsize5 = P014006+P014014 ",
                          "update %s set hhldsize6 = P014007+P014015 ",
                          "update %s set hhldsize7 = P014008+P014016 ",
                          "update %s set hhldtype1 = P010007",
                          "update %s set hhldtype2 = P010011 ",
                          "update %s set hhldtype3 = P010014",
                          "update %s set hhldtype4 = P010002",
                          "update %s set hhldtype5 = P010017",
                          "update %s set hhldrage1 = P012002",
                          "update %s set hhldrage2 = P012017",
                          "update %s set hhldfam1 = hhldtype1 + hhldtype2 + hhldtype3",
                          "update %s set hhldfam2 = hhldtype4 + hhldtype5",
                          

                          "drop table hhld_marginals",
                          "drop table gq_marginals",
                          "drop table person_marginals",
                          """create table hhld_marginals select state, county, tract, bg, hhldinc1, hhldinc2, hhldinc3, hhldinc4, hhldinc5, hhldinc6, hhldinc7, hhldinc8,"""
                          """hhldsize1, hhldsize2, hhldsize3, hhldsize4, hhldsize5, hhldsize6, hhldsize7, hhldtype1, hhldtype2, hhldtype3, hhldtype4, hhldtype5,"""
                          """childpresence1, childpresence2, hhldrage1, hhldrage2, hhldfam1, hhldfam2 from %s""",
                          "create table gq_marginals select state, county, tract, bg, groupquarter1, groupquarter2 from %s",
                          """create table person_marginals select state, county, tract, bg, agep1, agep2, agep3, agep4, agep5, agep6, agep7, agep8, agep9, agep10,"""
                          """gender1, gender2, race1, race2, race3, race4, race5, race6, race7, employment1, employment2, employment3, employment4 from"""
                          """ %s"""]

DEFAULT_SFACS_QUERIES = ["alter table %s add column agep1 bigint",
                         "alter table %s add column agep2 bigint",
                         "alter table %s add column agep3 bigint",
                         "alter table %s add column agep4 bigint",
                         "alter table %s add column agep5 bigint",
                         "alter table %s add column agep6 bigint",
                         "alter table %s add column agep7 bigint",
                         "alter table %s add column agep8 bigint",
                         "alter table %s add column agep9 bigint",
                         "alter table %s add column agep10 bigint",
                         "alter table %s add column gender1 bigint",
                         "alter table %s add column gender2 bigint",
                         "alter table %s add column race1 bigint",
                         "alter table %s add column race2 bigint",
                         "alter table %s add column race3 bigint",
                         "alter table %s add column race4 bigint",
                         "alter table %s add column race5 bigint",
                         "alter table %s add column race6 bigint",
                         "alter table %s add column race7 bigint",
                         "alter table %s add column race11 bigint",
                         "alter table %s add column race12 bigint",
                         "alter table %s add column race13 bigint",
                         "alter table %s add column race14 bigint",
                         "alter table %s add column race15 bigint",
                         "alter table %s add column race16 bigint",
                         "alter table %s add column race17 bigint",
                         "alter table %s add column race21 bigint",
                         "alter table %s add column race22 bigint",
                         "alter table %s add column race23 bigint",
                         "alter table %s add column race24 bigint",
                         "alter table %s add column race25 bigint",
                         "alter table %s add column race26 bigint",
                         "alter table %s add column race27 bigint",
                         "alter table %s add column employment1 bigint",
                         "alter table %s add column employment2 bigint",
                         "alter table %s add column employment3 bigint",
                         "alter table %s add column employment4 bigint",
                         "alter table %s add column childpresence1 bigint",
                         "alter table %s add column childpresence2 bigint",
                         "alter table %s add column groupquarter1 bigint",
                         "alter table %s add column hhldinc1 bigint",
                         "alter table %s add column hhldinc2 bigint",
                         "alter table %s add column hhldinc3 bigint",
                         "alter table %s add column hhldinc4 bigint",
                         "alter table %s add column hhldinc5 bigint",
                         "alter table %s add column hhldinc6 bigint",
                         "alter table %s add column hhldinc7 bigint",
                         "alter table %s add column hhldinc8 bigint",
                         "alter table %s add column hhldsize1 bigint",
                         "alter table %s add column hhldsize2 bigint",
                         "alter table %s add column hhldsize3 bigint",
                         "alter table %s add column hhldsize4 bigint",
                         "alter table %s add column hhldsize5 bigint",
                         "alter table %s add column hhldsize6 bigint",
                         "alter table %s add column hhldsize7 bigint",
                         "alter table %s add column hhldtype1 bigint",
                         "alter table %s add column hhldtype2 bigint",
                         "alter table %s add column hhldtype3 bigint",
                         "alter table %s add column hhldtype4 bigint",
                         "alter table %s add column hhldtype5 bigint",
                         "alter table %s add column hhldrage1 bigint",
                         "alter table %s add column hhldrage2 bigint",
                         "alter table %s add column hhldfam1 bigint",
                         "alter table %s add column hhldfam2 bigint",

                         "alter table %s add column check_gender bigint",
                         "alter table %s add column check_age bigint",
                         "alter table %s add column check_race bigint",
                         "alter table %s add column check_race1 bigint",
                         "alter table %s add column check_race2 bigint",
                         "alter table %s add column check_employment bigint",
                         
                         "alter table %s add column check_type bigint",
                         "alter table %s add column check_size bigint",
                         "alter table %s add column check_fam bigint",
                         "alter table %s add column check_hhldrage bigint",
                         "alter table %s add column check_inc bigint",
                         "alter table %s add column check_child bigint",
                         


                         "update %s set agep1 = (B01001000003)+(B01001000027)",
                         "update %s set agep2 = (B01001000004+B01001000005) + (B01001000028+B01001000029)",
                         "update %s set agep3 = (B01001000006+B01001000007+B01001000008+B01001000009+B01001000010) + (B01001000030+B01001000031+B01001000032+B01001000033+B01001000034)",
                         "update %s set agep4 = (B01001000011+B01001000012) + (B01001000035+B01001000036)",
                         "update %s set agep5 = (B01001000013+B01001000014) + (B01001000037+B01001000038)",
                         "update %s set agep6 = (B01001000015+B01001000016) + (B01001000039+B01001000040)",
                         "update %s set agep7 = (B01001000017+B01001000018+B01001000019) + (B01001000041+B01001000042+B01001000043)",
                         "update %s set agep8 = (B01001000020+B01001000021+B01001000022) + (B01001000044+B01001000045+B01001000046)",
                         "update %s set agep9 = (B01001000023+B01001000024) + (B01001000047+B01001000048)",
                         "update %s set agep10 = (B01001000025) + (B01001000049)",
                         "update %s set gender1 = B01001000002",
                         "update %s set gender2 = B01001000026",  
                         "update %s set race1 = B02001000002",
                         "update %s set race2 = B02001000003",
                         "update %s set race3 = B02001000004",
                         "update %s set race4 = B02001000005",
                         "update %s set race5 = B02001000006",
                         "update %s set race6 = B02001000007",
                         "update %s set race7 = B02001000009+B02001000010",

                         "update %s set race11 = C01001A00001",
                         "update %s set race12 = C01001B00001",
                         "update %s set race13 = C01001C00001",
                         "update %s set race14 = C01001D00001",
                         "update %s set race15 = C01001E00001",
                         "update %s set race16 = C01001F00001",
                         "update %s set race17 = C01001G00001",

                         "update %s set race21 = B01001A00001",
                         "update %s set race22 = B01001B00001",
                         "update %s set race23 = B01001C00001",
                         "update %s set race24 = B01001D00001",
                         "update %s set race25 = B01001E00001",
                         "update %s set race26 = B01001F00001",
                         "update %s set race27 = B01001G00001",

                         """update %s set employment2 = (B23001000005 + B23001000007) + (B23001000012 + B23001000014) + """
                         """(B23001000019 + B23001000021) + (B23001000026 + B23001000028) + (B23001000033 + B23001000035) + """
                         """(B23001000040 + B23001000042) + (B23001000047 + B23001000049) + (B23001000054 + B23001000056) + """
                         """(B23001000061 + B23001000063) + (B23001000068 + B23001000070) + (B23001000075 + B23001000080 + B23001000085) + """
                         """(B23001000091 + B23001000093) + (B23001000098 + B23001000100) + """
                         """(B23001000105 + B23001000107) + (B23001000112 + B23001000114) + (B23001000119 + B23001000121) + """
                         """(B23001000126 + B23001000128) + (B23001000133 + B23001000135) + (B23001000140 + B23001000142) + """
                         """(B23001000147 + B23001000149) + (B23001000154 + B23001000156) + (B23001000161 + B23001000166 + B23001000171)""",

                         """update %s set employment3 = (B23001000008 + B23001000015 + B23001000022 + """
                         """B23001000029 + B23001000036 + B23001000043 + B23001000050 + B23001000057 + B23001000064 +"""
                         """B23001000071 + B23001000076 + B23001000081 + B23001000086 + B23001000094 + B23001000101 +"""
                         """B23001000108 + B23001000115 + B23001000122 + B23001000129 + B23001000136 + B23001000143 +"""
                         """B23001000150 + B23001000157 + B23001000162 + B23001000167 + B23001000172) """,

                         """update %s set employment4 = (B23001000009 + B23001000016 + B23001000023 + """
                         """B23001000030 + B23001000037 + B23001000044 + B23001000051 + B23001000058 + B23001000065 +"""
                         """B23001000072 + B23001000077 + B23001000082 + B23001000087 + B23001000095 + B23001000102 +"""
                         """B23001000109 + B23001000116 + B23001000123 + B23001000130 + B23001000137 + B23001000144 +"""
                         """B23001000151 + B23001000158 + B23001000163 + B23001000168 + B23001000173) """,

                         "update %s set employment1 = gender1 + gender2 - employment2 - employment3 - employment4",

                         "update %s set groupquarter1 = B26001000001",
                         "update %s set hhldinc1 = B19001000002 + B19001000003",
                         "update %s set hhldinc2 = B19001000004 + B19001000005",
                         "update %s set hhldinc3 = B19001000006 + B19001000007",
                         "update %s set hhldinc4 = B19001000008 + B19001000009",
                         "update %s set hhldinc5 = B19001000010 + B19001000011",
                         "update %s set hhldinc6 = B19001000012 + B19001000013",
                         "update %s set hhldinc7 = B19001000014 + B19001000015",
                         "update %s set hhldinc8 = B19001000016 + B19001000017",
                         "update %s set hhldsize1 = B25009000003+B25009000011",
                         "update %s set hhldsize2 = B25009000004+B25009000012",
                         "update %s set hhldsize3 = B25009000005+B25009000013",
                         "update %s set hhldsize4 = B25009000006+B25009000014",
                         "update %s set hhldsize5 = B25009000007+B25009000015",
                         "update %s set hhldsize6 = B25009000008+B25009000016",
                         "update %s set hhldsize7 = B25009000009+B25009000017",
                         "update %s set hhldtype1 = B11001000003",
                         "update %s set hhldtype2 = B11001000005",
                         "update %s set hhldtype3 = B11001000006",
                         "update %s set hhldtype4 = B11001000008",
                         "update %s set hhldtype5 = B11001000009",
                         """update %s set hhldrage1 = (B25007000003+B25007000004+B25007000005+B25007000006+B25007000007+B25007000008)+"""
                         """(B25007000013+B25007000014+B25007000015+B25007000016+B25007000017+B25007000018)""", 
                         "update %s set hhldrage2 = (B25007000009+ B25007000010+B25007000011)+(B25007000019+ B25007000020+B25007000021)",
                         "update %s set hhldfam1 = hhldtype1 + hhldtype2 + hhldtype3",
                         "update %s set hhldfam2 = hhldtype4 + hhldtype5",
                         "update %s set childpresence1 = C23007000002",
                         "update %s set childpresence2 = C23007000017 + hhldtype4 + hhldtype5",

                         "update %s set check_gender = gender1 + gender2",
                         "update %s set check_age = agep1+agep2+agep3+agep4+agep5+agep6+agep7+agep8+agep9+agep10",
                         "update %s set check_race = race1+race2+race3+race4+race5+race6+race7",
                         "update %s set check_race1 = race11+race12+race13+race14+race15+race16+race17",
                         "update %s set check_race2 = race21+race22+race23+race24+race25+race26+race27",
                         "update %s set check_employment = employment1 + employment2 + employment3 + employment4",

                         "update %s set check_type = hhldtype1+hhldtype2+hhldtype3+hhldtype4+hhldtype5",
                         "update %s set check_size = hhldsize1+hhldsize2+hhldsize3+hhldsize4+hhldsize5+hhldsize6+hhldsize7",
                         "update %s set check_hhldrage = hhldrage1+hhldrage2",
                         "update %s set check_inc = hhldinc1+hhldinc2+hhldinc3+hhldinc4+hhldinc5+hhldinc6+hhldinc7+hhldinc8",
                         "update %s set check_fam = hhldfam1+hhldfam2",
                         "update %s set check_child = childpresence1+childpresence2",


                  

                         "drop table hhld_marginals",
                         "drop table gq_marginals",
                         "drop table person_marginals",
                         """create table hhld_marginals select state, county, tract, bg, hhldinc1, hhldinc2, hhldinc3, hhldinc4, hhldinc5, hhldinc6, hhldinc7, hhldinc8,"""
                         """hhldsize1, hhldsize2, hhldsize3, hhldsize4, hhldsize5, hhldsize6, hhldsize7, hhldtype1, hhldtype2, hhldtype3, hhldtype4, hhldtype5,"""
                         """childpresence1, childpresence2, hhldrage1, hhldrage2, hhldfam1, hhldfam2 from %s""",
                         "create table gq_marginals select state, county, tract, bg, groupquarter1 from %s",
                         """create table person_marginals select state, county, tract, bg, agep1, agep2, agep3, agep4, agep5, agep6, agep7, agep8, agep9, agep10,"""
                         """gender1, gender2, race1, race2, race3, race4, race5, race6, race7 from %s"""]


                   

                   
 


