#
# UrbanSim software. Copyright (C) 2005-2008 University of Washington
# 
# You can redistribute this program and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation
# (http://www.gnu.org/copyleft/gpl.html).
# 
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the file LICENSE.html for copyright
# and licensing information, and the file ACKNOWLEDGMENTS.html for funding and
# other acknowledgments.
# 

# this is a test of the expression alias file
# one of the aliases uses a primary attribute in the expression, the other a variable

aliases = [
        # aggregate sector job totals:
        'number_of_jobs = mpa.number_of_agents(job)',
        'mpa_total_non_home_based_jobs = mpa.aggregate(mag_zone.job.is_homebased_job==0)',
        'mpa_total_home_based_jobs = mpa.aggregate(mag_zone.job.is_homebased_job)',
        'number_of_public_jobs = mpa.aggregate(mag_zone.job.is_public_job)',
        'number_of_industrial_jobs = mpa.aggregate(mag_zone.job.is_industrial_job)',
        'number_of_entertainment_jobs = mpa.aggregate(mag_zone.job.is_entertainment_job)',
        'number_of_homebased_jobs = mpa.aggregate(mag_zone.job.is_homebased_job)',
        'number_of_office_jobs = mpa.aggregate(mag_zone.job.is_office_job)',
        # individual sector job totals:
        'number_of_agricultural_jobs = mpa.aggregate(mag_zone.job.is_agricultural_job)',
        'number_of_mining_jobs = mpa.aggregate(mag_zone.job.is_mining_job)',
        'number_of_utilities_jobs = mpa.aggregate(mag_zone.job.is_utilities_job)',
        'number_of_construction_jobs = mpa.aggregate(mag_zone.job.is_construction_job)',
        'number_of_manufacturing_jobs = mpa.aggregate(mag_zone.job.is_manufacturing_job)',
        'number_of_wholesale_jobs = mpa.aggregate(mag_zone.job.is_wholesale_job)',
        'number_of_retail_jobs = mpa.aggregate(mag_zone.job.is_retail_job)',
        'number_of_transportation_jobs = mpa.aggregate(mag_zone.job.is_transportation_job)',
        'number_of_information_jobs = mpa.aggregate(mag_zone.job.is_information_job)',
        'number_of_finance_jobs = mpa.aggregate(mag_zone.job.is_finance_job)',
        'number_of_realestate_jobs = mpa.aggregate(mag_zone.job.is_realestate_job)',
        'number_of_professional_jobs = mpa.aggregate(mag_zone.job.is_professional_job)',
        'number_of_healthcare_jobs = mpa.aggregate(mag_zone.job.is_healthcare_job)',
        'number_of_accomodation_jobs = mpa.aggregate(mag_zone.job.is_accomodation_job)',
        'number_of_foodservice_jobs = mpa.aggregate(mag_zone.job.is_foodservice_job)',
        'number_of_pubfedstate_jobs = mpa.aggregate(mag_zone.job.is_pubfedstate_job)',
        'number_of_publocal_jobs = mpa.aggregate(mag_zone.job.is_publocal_job)',
        # individual nhb sector job totals:
        'mpa_number_of_nhb_01agricultural_jobs = mpa.aggregate(mag_zone.job.is_agricultural_job * mag_zone.job.is_nonhomebased_job)',
        'mpa_number_of_nhb_02mining_jobs = mpa.aggregate(mag_zone.job.is_mining_job * mag_zone.job.is_nonhomebased_job)',
        'mpa_number_of_nhb_03utilities_jobs = mpa.aggregate(mag_zone.job.is_utilities_job * mag_zone.job.is_nonhomebased_job)',
        'mpa_number_of_nhb_04construction_jobs = mpa.aggregate(mag_zone.job.is_construction_job * mag_zone.job.is_nonhomebased_job)',
        'mpa_number_of_nhb_05manufacturing_jobs = mpa.aggregate(mag_zone.job.is_manufacturing_job * mag_zone.job.is_nonhomebased_job)',
        'mpa_number_of_nhb_06wholesale_jobs = mpa.aggregate(mag_zone.job.is_wholesale_job * mag_zone.job.is_nonhomebased_job)',
        'mpa_number_of_nhb_07retail_jobs = mpa.aggregate(mag_zone.job.is_retail_job * mag_zone.job.is_nonhomebased_job)',
        'mpa_number_of_nhb_08transportation_jobs = mpa.aggregate(mag_zone.job.is_transportation_job * mag_zone.job.is_nonhomebased_job)',
        'mpa_number_of_nhb_09information_jobs = mpa.aggregate(mag_zone.job.is_information_job * mag_zone.job.is_nonhomebased_job)',
        'mpa_number_of_nhb_10finance_jobs = mpa.aggregate(mag_zone.job.is_finance_job * mag_zone.job.is_nonhomebased_job)',
        'mpa_number_of_nhb_11realestate_jobs = mpa.aggregate(mag_zone.job.is_realestate_job * mag_zone.job.is_nonhomebased_job)',
        'mpa_number_of_nhb_12professional_jobs = mpa.aggregate(mag_zone.job.is_professional_job * mag_zone.job.is_nonhomebased_job)',
        'mpa_number_of_nhb_13management_jobs = mpa.aggregate(mag_zone.job.is_management_job * mag_zone.job.is_nonhomebased_job)',
        'mpa_number_of_nhb_14administrative_jobs = mpa.aggregate(mag_zone.job.is_admin_support_job * mag_zone.job.is_nonhomebased_job)',
        'mpa_number_of_nhb_15education_jobs = mpa.aggregate(mag_zone.job.is_educ_svcs_job * mag_zone.job.is_nonhomebased_job)',
        'mpa_number_of_nhb_16healthcare_jobs = mpa.aggregate(mag_zone.job.is_healthcare_job * mag_zone.job.is_nonhomebased_job)',
        'mpa_number_of_nhb_16medical_jobs = mpa.aggregate(mag_zone.job.is_healthcare_job * mag_zone.job.is_nonhomebased_job)',
        'mpa_number_of_nhb_17arts_jobs = mpa.aggregate(mag_zone.job.is_arts_ent_rec_job * mag_zone.job.is_nonhomebased_job)',
        'mpa_number_of_nhb_18accomodation_jobs = mpa.aggregate(mag_zone.job.is_accomodation_job * mag_zone.job.is_nonhomebased_job)',
        'mpa_number_of_nhb_19foodservice_jobs = mpa.aggregate(mag_zone.job.is_foodservice_job * mag_zone.job.is_nonhomebased_job)',
        'mpa_number_of_nhb_20other_services_jobs = mpa.aggregate(mag_zone.job.is_other_svcs_job * mag_zone.job.is_nonhomebased_job)',
        'mpa_number_of_nhb_21pubfedstate_jobs = mpa.aggregate(mag_zone.job.is_pubfedstate_job * mag_zone.job.is_nonhomebased_job)',
        'mpa_number_of_nhb_22publocal_jobs = mpa.aggregate(mag_zone.job.is_publocal_job * mag_zone.job.is_nonhomebased_job)',
        # individual hb sector job totals:
        'mpa_number_of_hb_01agricultural_jobs = mpa.aggregate(mag_zone.job.is_agricultural_job * mag_zone.job.is_homebased_job)',
        'mpa_number_of_hb_02mining_jobs = mpa.aggregate(mag_zone.job.is_mining_job * mag_zone.job.is_homebased_job)',
        'mpa_number_of_hb_03utilities_jobs = mpa.aggregate(mag_zone.job.is_utilities_job * mag_zone.job.is_homebased_job)',
        'mpa_number_of_hb_04construction_jobs = mpa.aggregate(mag_zone.job.is_construction_job * mag_zone.job.is_homebased_job)',
        'mpa_number_of_hb_05manufacturing_jobs = mpa.aggregate(mag_zone.job.is_manufacturing_job * mag_zone.job.is_homebased_job)',
        'mpa_number_of_hb_06wholesale_jobs = mpa.aggregate(mag_zone.job.is_wholesale_job * mag_zone.job.is_homebased_job)',
        'mpa_number_of_hb_07retail_jobs = mpa.aggregate(mag_zone.job.is_retail_job * mag_zone.job.is_homebased_job)',
        'mpa_number_of_hb_08transportation_jobs = mpa.aggregate(mag_zone.job.is_transportation_job * mag_zone.job.is_homebased_job)',
        'mpa_number_of_hb_09information_jobs = mpa.aggregate(mag_zone.job.is_information_job * mag_zone.job.is_homebased_job)',
        'mpa_number_of_hb_10finance_jobs = mpa.aggregate(mag_zone.job.is_finance_job * mag_zone.job.is_homebased_job)',
        'mpa_number_of_hb_11realestate_jobs = mpa.aggregate(mag_zone.job.is_realestate_job * mag_zone.job.is_homebased_job)',
        'mpa_number_of_hb_12professional_jobs = mpa.aggregate(mag_zone.job.is_professional_job * mag_zone.job.is_homebased_job)',
        'mpa_number_of_hb_13management_jobs = mpa.aggregate(mag_zone.job.is_management_job * mag_zone.job.is_homebased_job)',
        'mpa_number_of_hb_14administrative_jobs = mpa.aggregate(mag_zone.job.is_admin_support_job * mag_zone.job.is_homebased_job)',
        'mpa_number_of_hb_15education_jobs = mpa.aggregate(mag_zone.job.is_educ_svcs_job * mag_zone.job.is_homebased_job)',
        'mpa_number_of_hb_16healthcare_jobs = mpa.aggregate(mag_zone.job.is_healthcare_job * mag_zone.job.is_homebased_job)',
        'mpa_number_of_hb_16medical_jobs = mpa.aggregate(mag_zone.job.is_healthcare_job * mag_zone.job.is_homebased_job)',
        'mpa_number_of_hb_17arts_jobs = mpa.aggregate(mag_zone.job.is_arts_ent_rec_job * mag_zone.job.is_homebased_job)',
        'mpa_number_of_hb_18accomodation_jobs = mpa.aggregate(mag_zone.job.is_accomodation_job * mag_zone.job.is_homebased_job)',
        'mpa_number_of_hb_19foodservice_jobs = mpa.aggregate(mag_zone.job.is_foodservice_job * mag_zone.job.is_homebased_job)',
        'mpa_number_of_hb_20other_services_jobs = mpa.aggregate(mag_zone.job.is_other_svcs_job * mag_zone.job.is_homebased_job)',
        'mpa_number_of_hb_21pubfedstate_jobs = mpa.aggregate(mag_zone.job.is_pubfedstate_job * mag_zone.job.is_homebased_job)',
        'mpa_number_of_hb_22publocal_jobs = mpa.aggregate(mag_zone.job.is_publocal_job * mag_zone.job.is_homebased_job)',
        # population related:
        'population = mpa.number_of_agents(person)',
        'mpa_total_seasonal_population = mpa.aggregate(household.persons*mag_zone.household.is_seasonal)',
        'mpa_total_resident_population = mpa.aggregate(household.persons*mag_zone.household.is_seasonal==0)',
        'average_population_age = mpa.aggregate(person.age, function=mean)',
        'median_population_age = mpa.aggregate(person.age, function=median)',
        'number_of_children = mpa.aggregate(where(person.age < 17, 1,0))',
        'population_with_less_than_high_school_diploma = mpa.aggregate(mag_zone.person.less_than_high_school_diploma)',
        'population_with_at_least_high_school_diploma = mpa.aggregate(mag_zone.person.at_least_high_school_diploma)',
        'population_with_at_least_associates_degree = mpa.aggregate(mag_zone.person.at_least_associates_degree)',
        'population_with_at_least_bachelors_degree = mpa.aggregate(mag_zone.person.at_least_bachelors_degree)',
        'population_with_at_least_masters_degree = mpa.aggregate(mag_zone.person.at_least_masters_degree)',
        'average_adult_education = mpa.aggregate(mag_zone.person.is_adult*person.education, function=mean)',
        # household related:
        'number_of_hh_age_of_head_over_55 = mpa.aggregate(mag_zone.household.hh_head_over_55)',
        'number_of_households = mpa.number_of_agents(household)',
        'mpa_total_seasonal_households = mpa.aggregate(mag_zone.household.is_seasonal)',
        'mpa_total_resident_households = mpa.aggregate(mag_zone.household.is_seasonal==0)',
        'percent_hh_age_of_head_over_55 = mpa.aggregate(safe_array_divide(mag_zone.mpa.number_of_hh_age_of_head_over_55, mag_zone.mpa.number_of_households))',
        'number_of_hh_size_1 = mpa.aggregate(household.persons==1)',
        'number_of_hh_size_2 = mpa.aggregate(household.persons==2)',
        'number_of_hh_size_3 = mpa.aggregate(household.persons==3)',
        'number_of_hh_size_4 = mpa.aggregate(household.persons==4)',
        'number_of_hh_size_5 = mpa.aggregate(household.persons==5)',
        'number_of_hh_size_6 = mpa.aggregate(household.persons==6)',
        'number_of_hh_size_7up = mpa.aggregate(household.persons>6)',
        'number_of_hh_1_child = mpa.aggregate(household.children==1)',
        'number_of_hh_2_children = mpa.aggregate(household.children==2)',
        'number_of_hh_3_children = mpa.aggregate(household.children==3)',
        'number_of_hh_4up_children = mpa.aggregate(household.children>3)',
        'persons_per_hh = mpa.aggregate(household.persons, function=mean)',
        'number_of_hh_0_workers = mpa.aggregate(household.workers==0)',
        'number_of_hh_1_workers = mpa.aggregate(household.workers==1)',
        'number_of_hh_2_workers = mpa.aggregate(household.workers==2)',
        'number_of_hh_3up_workers = mpa.aggregate(household.workers>2)',
        'number_of_hh_0_vehicles = mpa.aggregate(mag_zone.household.number_of_vehicles0)',
        'number_of_hh_1_vehicles = mpa.aggregate(mag_zone.household.number_of_vehicles1)',
        'number_of_hh_2_vehicles = mpa.aggregate(mag_zone.household.number_of_vehicles2)',
        'number_of_hh_3_vehicles = mpa.aggregate(mag_zone.household.number_of_vehicles3)',
        'number_of_hh_4up_vehicles = mpa.aggregate(mag_zone.household.number_of_vehicles4up)',
        'average_resident_household_income = mpa.aggregate(household.income*household.is_seasonal==0, function=mean)',
        'median_resident_household_income = mpa.aggregate(household.income*household.is_seasonal==0, function=median)',
        'mpa_hh_inc_quint01 = mpa.aggregate(mag_zone.household.income_quintiles==1)',
        'mpa_hh_inc_quint02 = mpa.aggregate(mag_zone.household.income_quintiles==2)',
        'mpa_hh_inc_quint03 = mpa.aggregate(mag_zone.household.income_quintiles==3)',
        'mpa_hh_inc_quint04 = mpa.aggregate(mag_zone.household.income_quintiles==4)',
        'mpa_hh_inc_quint05 = mpa.aggregate(mag_zone.household.income_quintiles==5)',
        'mpa_hh_age_of_head_under_25 = raz2012.aggregate(mag_zone.household.age_of_head_under_25)',
        'mpa_hh_age_of_head_26_35 = mpa.aggregate(mag_zone.household.age_of_head_26_35)',
        'mpa_hh_age_of_head_36_45 = mpa.aggregate(mag_zone.household.age_of_head_36_45)',
        'mpa_hh_age_of_head_46_55 = mpa.aggregate(mag_zone.household.age_of_head_46_55)',
        'mpa_hh_age_of_head_56_65 = mpa.aggregate(mag_zone.household.age_of_head_56_65)',
        'mpa_hh_age_of_head_66_up = mpa.aggregate(mag_zone.household.age_of_head_66_up)',
        # DU related
        'total_dus = mpa.aggregate(building.residential_units)',
        'total_sfr_dus = mpa.aggregate(mag_zone.building.number_sfr_dus)',
        'total_mfr_dus = mpa.aggregate(mag_zone.building.number_mfr_dus)',
        'total_mh_dus = mpa.aggregate(mag_zone.building.number_mh_dus)',
        'percent_dus_built = safe_array_divide(mag_zone.mpa.total_dus, mpa.aggregate(building.residential_units_capacity))',
        'percent_sfr_dus = safe_array_divide(mag_zone.mpa.total_sfr_dus, mag_zone.mpa.total_dus)',
        'percent_sfr_mh_dus = safe_array_divide((mag_zone.mpa.total_sfr_dus+mag_zone.mpa.total_mh_dus), mag_zone.mpa.total_dus)',
        'percent_mfr_dus = safe_array_divide(mag_zone.mpa.total_mfr_dus, mag_zone.mpa.total_dus)',
        'percent_mh_dus = safe_array_divide(mag_zone.mpa.total_mh_dus, mag_zone.mpa.total_dus)',
        'mpa_dus_constructed_this_year = mpa.aggregate(mag_zone.building.bldg_du_constructed_this_year)',
        'mpa_residential_units_percent_buildout = mag_zone.mpa.total_dus/mpa.aggregate(zone.res_units_capacity_2100)',
        # other indicators
        'jobs_housing_ratio = safe_array_divide(mag_zone.mpa.number_of_jobs, mag_zone.mpa.total_dus)',
        'occupancy_rate = safe_array_divide(mag_zone.mpa.number_of_households, mag_zone.mpa.total_dus)',
        # older v3x expressions:
        'mpa_residential_units = mpa.aggregate(building.residential_units)',
        'mpa_jobs_5 = mpa.aggregate(job.sector_id==5)',
        'mpa_total_jobs = mpa.number_of_agents(job)',
        'mpa_county_jobs_5 = mpa.disaggregate(county.county_jobs_5)',
        'mpa_county_total_jobs = mpa.disaggregate(county.total_jobs)',
        'lq5 = safe_array_divide((safe_array_divide(mag_zone.mpa.mpa_jobs_5,mag_zone.mpa.mpa_total_jobs)), \
                                 (safe_array_divide(mag_zone.mpa.mpa_county_jobs_5,mag_zone.mpa.mpa_county_total_jobs)))',
           ]
