~/ utility_values.mac
~/ This macro:
~/ 1) Sets the output format to 8.4
~/ 2) Outputs the named full matrices (up to 9)
~/    for the i,j pairs 1-932, 1-932.
~/ 3) - - to the new file usimout.dat
~/ 4) And exits both the program and EMME/2
~/
~!if exist utility_values.dat erase utility_values.dat
reports=?
3.14
~+|4|2|8,4|y|4|n
~+|1|3
utlda1
utlda2
utlda3
utlda4
utltw1
utltw2
utltw3
utltw4
~+|||y|1,938||1,938||2|utility_values.dat
q
q
