# Opus/UrbanSim urban simulation software.
# Copyright (C) 2010-2011 University of California, Berkeley, 2005-2009 University of Washington
# See opus_core/LICENSE 

import os
import dbf
from opus_core.logger import logger
from numpy import logical_or, logical_and, array, where, zeros
from opus_core.variables.variable_name import VariableName
from opus_core.resources import Resources
from wfrc.cube.get_cache_data_into_travel_model import GetCacheDataIntoTravelModel
from opus_core.session_configuration import SessionConfiguration
from opus_core.store.attribute_cache import AttributeCache

class GetCacheDataIntoTravelModel(GetCacheDataIntoTravelModel):
    """Write urbansim simulation information into a (file) format 
    that travel model uses to update its tazdata. """
    
    def create_travel_model_input_file(self,
                                       config,
                                       year,
                                       zone_set,
                                       #dataset_pool,
                                       delimiter = ',',
                                       *args,**kwargs):
        """Writes to file specified by 'urbansim_to_tm_variable_file' 
        to [travel_model_data_directory]/[year_directory], which travel model 
        will use as input.
        """
        tm_config       = config['travel_model_configuration']
        column_names    = tm_config['tm_variable_order']
        variable_list   = []
                
        for name in column_names:
            variable_list.append(tm_config['urbansim_to_tm_variable_mapping'][name])

        # compute our variables
	dataset_pool = SessionConfiguration().get_dataset_pool()
        zone_set.compute_variables(variable_list, dataset_pool=dataset_pool)
        variable_short_name = [VariableName(x).get_alias() for x in variable_list]
        # the short names are generated by the zone_set, e.g. ['autogenvar1', 'autogenvar5', 'autogenvar7' ... ]
        # logger.log_status(variable_short_name)
        
        # prepare the data for writing.
        # not packing it into a numpy array because we lose the int/float information
        data = {}  # colnum -> data array
        for i in range(len(variable_short_name)):
            this_column = zone_set.get_attribute(variable_short_name[i])
            data[i] = this_column

        # make the travel model directory
        tm_input_data_dir = os.path.join(tm_config['travel_model_base_directory'], tm_config[year]['year_dir'])
        if not os.path.exists(tm_input_data_dir):
            os.makedirs(tm_input_data_dir)
        
        tm_file = tm_config['urbansim_to_tm_variable_file'] + '_' + tm_config[year]['year_dir'] + '.csv'   
        self._update_travel_model_data_file(tm_config, data, column_names, 
                os.path.join(tm_input_data_dir, tm_file), delimiter)
        dbf.from_csv(csvfile = os.path.join(tm_input_data_dir, tm_file), to_disk = True, field_names = None)
        
    def _update_travel_model_data_file(self, tm_config, data, header, input_file, delimiter):
        self._write_to_txt_file(data, header, input_file, delimiter)
        
    def _write_to_txt_file(self, data, header, input_file, delimiter=','):
        logger.start_block("Writing to travel_model input file %s" % input_file)
        newfile = open(input_file, 'w')
        newfile.write(delimiter.join(header).replace("tm.", "") + "\n")
        for row in range(len(data[0])):
            for col in range(len(header)):
                newfile.write(str(data[col][row]))
                if col < len(header)-1:
                    newfile.write(",")
            newfile.write("\n")
                                          
        newfile.close()
        
        logger.end_block()
            
if __name__ == "__main__":
    try: import wingdbstub
    except: pass
    from optparse import OptionParser
    from opus_core.file_utilities import get_resources_from_file
    parser = OptionParser()
    parser.add_option("-r", "--resources", dest="resources_file_name", action="store", type="string",
                      help="Name of file containing resources")
    parser.add_option("-y", "--year", dest="year", action="store", type="int",
                      help="Year in which to 'run' the travel model")
    (options, args) = parser.parse_args()
    r = get_resources_from_file(options.resources_file_name)
    resources = Resources(get_resources_from_file(options.resources_file_name))

    SessionConfiguration(new_instance=True,
                         package_order=resources['dataset_pool_configuration'].package_order,                 
                         in_storage=AttributeCache())

    GetCacheDataIntoTravelModel().run(resources, options.year)
