# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulation_gui_element.ui'
#
# Created: Fri Feb  6 14:38:48 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_SimulationGuiElement(object):
    def setupUi(self, SimulationGuiElement):
        SimulationGuiElement.setObjectName("SimulationGuiElement")
        SimulationGuiElement.resize(1114, 856)
        self.gridLayout_2 = QtGui.QGridLayout(SimulationGuiElement)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.modelControlWidget = QtGui.QWidget(SimulationGuiElement)
        self.modelControlWidget.setObjectName("modelControlWidget")
        self.gridLayout = QtGui.QGridLayout(self.modelControlWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pbnStartModel = QtGui.QPushButton(self.modelControlWidget)
        self.pbnStartModel.setObjectName("pbnStartModel")
        self.gridLayout.addWidget(self.pbnStartModel, 0, 0, 1, 1)
        self.pbnRemoveModel = QtGui.QPushButton(self.modelControlWidget)
        self.pbnRemoveModel.setObjectName("pbnRemoveModel")
        self.gridLayout.addWidget(self.pbnRemoveModel, 1, 0, 1, 1)
        self.lblRun = QtGui.QLabel(self.modelControlWidget)
        self.lblRun.setObjectName("lblRun")
        self.gridLayout.addWidget(self.lblRun, 0, 1, 1, 1)
        self.lblBatch = QtGui.QLabel(self.modelControlWidget)
        self.lblBatch.setObjectName("lblBatch")
        self.gridLayout.addWidget(self.lblBatch, 1, 1, 1, 1)
        self.leRunName = QtGui.QLineEdit(self.modelControlWidget)
        self.leRunName.setObjectName("leRunName")
        self.gridLayout.addWidget(self.leRunName, 0, 2, 1, 1)
        self.cboOptionalIndicatorBatch = QtGui.QComboBox(self.modelControlWidget)
        self.cboOptionalIndicatorBatch.setObjectName("cboOptionalIndicatorBatch")
        self.gridLayout.addWidget(self.cboOptionalIndicatorBatch, 1, 2, 1, 1)
        self.gridLayout_2.addWidget(self.modelControlWidget, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(SimulationGuiElement)
        self.tabWidget.setObjectName("tabWidget")
        self.simprogressWidget = QtGui.QWidget()
        self.simprogressWidget.setObjectName("simprogressWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.simprogressWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.simprogressWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.runProgressBarTotal = QtGui.QProgressBar(self.simprogressWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runProgressBarTotal.sizePolicy().hasHeightForWidth())
        self.runProgressBarTotal.setSizePolicy(sizePolicy)
        self.runProgressBarTotal.setProperty("value", QtCore.QVariant(24))
        self.runProgressBarTotal.setObjectName("runProgressBarTotal")
        self.horizontalLayout.addWidget(self.runProgressBarTotal)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_4 = QtGui.QLabel(self.simprogressWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.summaryCurrentYearValue = QtGui.QLabel(self.simprogressWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.summaryCurrentYearValue.sizePolicy().hasHeightForWidth())
        self.summaryCurrentYearValue.setSizePolicy(sizePolicy)
        self.summaryCurrentYearValue.setObjectName("summaryCurrentYearValue")
        self.horizontalLayout_4.addWidget(self.summaryCurrentYearValue)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.cbYear = QtGui.QCheckBox(self.simprogressWidget)
        self.cbYear.setChecked(True)
        self.cbYear.setObjectName("cbYear")
        self.verticalLayout.addWidget(self.cbYear)
        self.gb_year_progress = QtGui.QGroupBox(self.simprogressWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_year_progress.sizePolicy().hasHeightForWidth())
        self.gb_year_progress.setSizePolicy(sizePolicy)
        self.gb_year_progress.setFlat(False)
        self.gb_year_progress.setObjectName("gb_year_progress")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gb_year_progress)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtGui.QLabel(self.gb_year_progress)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.runProgressBarYear = QtGui.QProgressBar(self.gb_year_progress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runProgressBarYear.sizePolicy().hasHeightForWidth())
        self.runProgressBarYear.setSizePolicy(sizePolicy)
        self.runProgressBarYear.setProperty("value", QtCore.QVariant(24))
        self.runProgressBarYear.setObjectName("runProgressBarYear")
        self.horizontalLayout_3.addWidget(self.runProgressBarYear)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label_5 = QtGui.QLabel(self.gb_year_progress)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.summaryCurrentModelValue = QtGui.QLabel(self.gb_year_progress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.summaryCurrentModelValue.sizePolicy().hasHeightForWidth())
        self.summaryCurrentModelValue.setSizePolicy(sizePolicy)
        self.summaryCurrentModelValue.setObjectName("summaryCurrentModelValue")
        self.horizontalLayout_5.addWidget(self.summaryCurrentModelValue)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.cbModel = QtGui.QCheckBox(self.gb_year_progress)
        self.cbModel.setObjectName("cbModel")
        self.verticalLayout_2.addWidget(self.cbModel)
        self.gb_model_progress = QtGui.QGroupBox(self.gb_year_progress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_model_progress.sizePolicy().hasHeightForWidth())
        self.gb_model_progress.setSizePolicy(sizePolicy)
        self.gb_model_progress.setObjectName("gb_model_progress")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gb_model_progress)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtGui.QLabel(self.gb_model_progress)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.runProgressBarModel = QtGui.QProgressBar(self.gb_model_progress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runProgressBarModel.sizePolicy().hasHeightForWidth())
        self.runProgressBarModel.setSizePolicy(sizePolicy)
        self.runProgressBarModel.setProperty("value", QtCore.QVariant(24))
        self.runProgressBarModel.setObjectName("runProgressBarModel")
        self.horizontalLayout_2.addWidget(self.runProgressBarModel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtGui.QSpacerItem(28, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.label_6 = QtGui.QLabel(self.gb_model_progress)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.summaryCurrentPieceValue = QtGui.QLabel(self.gb_model_progress)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.summaryCurrentPieceValue.sizePolicy().hasHeightForWidth())
        self.summaryCurrentPieceValue.setSizePolicy(sizePolicy)
        self.summaryCurrentPieceValue.setObjectName("summaryCurrentPieceValue")
        self.horizontalLayout_6.addWidget(self.summaryCurrentPieceValue)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addWidget(self.gb_model_progress)
        self.verticalLayout.addWidget(self.gb_year_progress)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.tabWidget.addTab(self.simprogressWidget, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_5.setContentsMargins(0, 3, 0, 3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.logText = QtGui.QTextEdit(self.tab_2)
        self.logText.setLineWidth(0)
        self.logText.setReadOnly(True)
        self.logText.setObjectName("logText")
        self.gridLayout_5.addWidget(self.logText, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.indicatorWidget = QtGui.QWidget()
        self.indicatorWidget.setObjectName("indicatorWidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.indicatorWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter = QtGui.QSplitter(self.indicatorWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.diagnostic_go_button = QtGui.QPushButton(self.splitter)
        self.diagnostic_go_button.setObjectName("diagnostic_go_button")
        self.diagnostic_indicator_type = QtGui.QComboBox(self.splitter)
        self.diagnostic_indicator_type.setObjectName("diagnostic_indicator_type")
        self.diagnostic_indicator_type.addItem(QtCore.QString())
        self.diagnostic_indicator_type.addItem(QtCore.QString())
        self.diagnostic_dataset_name = QtGui.QComboBox(self.splitter)
        self.diagnostic_dataset_name.setObjectName("diagnostic_dataset_name")
        self.diagnostic_indicator_name = QtGui.QComboBox(self.splitter)
        self.diagnostic_indicator_name.setObjectName("diagnostic_indicator_name")
        self.diagnostic_year = QtGui.QComboBox(self.splitter)
        self.diagnostic_year.setObjectName("diagnostic_year")
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        self.indicatorResultsTab = QtGui.QTabWidget(self.indicatorWidget)
        self.indicatorResultsTab.setObjectName("indicatorResultsTab")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.indicatorResultsTab.addTab(self.tab_4, "")
        self.gridLayout_3.addWidget(self.indicatorResultsTab, 1, 0, 1, 1)
        self.tabWidget.addTab(self.indicatorWidget, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)

        self.retranslateUi(SimulationGuiElement)
        self.tabWidget.setCurrentIndex(0)
        self.indicatorResultsTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SimulationGuiElement)

    def retranslateUi(self, SimulationGuiElement):
        SimulationGuiElement.setWindowTitle(QtGui.QApplication.translate("SimulationGuiElement", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnStartModel.setText(QtGui.QApplication.translate("SimulationGuiElement", "Start Simulation...", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnRemoveModel.setText(QtGui.QApplication.translate("SimulationGuiElement", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.lblRun.setText(QtGui.QApplication.translate("SimulationGuiElement", "Run Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBatch.setToolTip(QtGui.QApplication.translate("SimulationGuiElement", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If an indicator batch (defined in the Results Manager)<br>is selected, it will be executed over every <br>year of the simulation being configured. <br>It will executed after the simulation is completed.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBatch.setText(QtGui.QApplication.translate("SimulationGuiElement", "Indicator Batch:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setToolTip(QtGui.QApplication.translate("SimulationGuiElement", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This scenario run will appear <br>in the Results Manager under the name <br>specified here. If not specified,<br>the name will default to a combination <br>of run id and date of run.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SimulationGuiElement", "Total progress:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("SimulationGuiElement", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.summaryCurrentYearValue.setText(QtGui.QApplication.translate("SimulationGuiElement", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.cbYear.setText(QtGui.QApplication.translate("SimulationGuiElement", "Show progress within current year", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SimulationGuiElement", "Year progress:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("SimulationGuiElement", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.summaryCurrentModelValue.setText(QtGui.QApplication.translate("SimulationGuiElement", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.cbModel.setText(QtGui.QApplication.translate("SimulationGuiElement", "Show progress within current model", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SimulationGuiElement", "Model progress:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("SimulationGuiElement", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.summaryCurrentPieceValue.setText(QtGui.QApplication.translate("SimulationGuiElement", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.simprogressWidget), QtGui.QApplication.translate("SimulationGuiElement", "Simulation Progress", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("SimulationGuiElement", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.diagnostic_go_button.setText(QtGui.QApplication.translate("SimulationGuiElement", "Diagnose...", None, QtGui.QApplication.UnicodeUTF8))
        self.diagnostic_indicator_type.setItemText(0, QtGui.QApplication.translate("SimulationGuiElement", "map", None, QtGui.QApplication.UnicodeUTF8))
        self.diagnostic_indicator_type.setItemText(1, QtGui.QApplication.translate("SimulationGuiElement", "table", None, QtGui.QApplication.UnicodeUTF8))
        self.indicatorResultsTab.setTabText(self.indicatorResultsTab.indexOf(self.tab_4), QtGui.QApplication.translate("SimulationGuiElement", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.indicatorWidget), QtGui.QApplication.translate("SimulationGuiElement", "Diagnostics", None, QtGui.QApplication.UnicodeUTF8))

