# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/ckla/Dropbox/urbansim/xml_converter/src/converter_gui.ui'
#
# Created: Sat May  9 13:38:44 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ConverterGui(object):
    def setupUi(self, ConverterGui):
        ConverterGui.setObjectName("ConverterGui")
        ConverterGui.resize(618, 380)
        self.verticalLayout_2 = QtGui.QVBoxLayout(ConverterGui)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stack_steps = QtGui.QStackedWidget(ConverterGui)
        self.stack_steps.setObjectName("stack_steps")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtGui.QVBoxLayout(self.page)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.frame_error = QtGui.QFrame(self.page)
        self.frame_error.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_error.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_error.setObjectName("frame_error")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_error)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.p0_info_icon = QtGui.QLabel(self.frame_error)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p0_info_icon.sizePolicy().hasHeightForWidth())
        self.p0_info_icon.setSizePolicy(sizePolicy)
        self.p0_info_icon.setPixmap(QtGui.QPixmap(":/images/images/messagebox_info.png"))
        self.p0_info_icon.setMargin(5)
        self.p0_info_icon.setObjectName("p0_info_icon")
        self.horizontalLayout_2.addWidget(self.p0_info_icon)
        self.p0_warning_icon = QtGui.QLabel(self.frame_error)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p0_warning_icon.sizePolicy().hasHeightForWidth())
        self.p0_warning_icon.setSizePolicy(sizePolicy)
        self.p0_warning_icon.setPixmap(QtGui.QPixmap(":/images/images/messagebox_warning.png"))
        self.p0_warning_icon.setMargin(5)
        self.p0_warning_icon.setObjectName("p0_warning_icon")
        self.horizontalLayout_2.addWidget(self.p0_warning_icon)
        self.p0_text = QtGui.QLabel(self.frame_error)
        self.p0_text.setWordWrap(True)
        self.p0_text.setObjectName("p0_text")
        self.horizontalLayout_2.addWidget(self.p0_text)
        self.verticalLayout.addWidget(self.frame_error)
        self.frame = QtGui.QFrame(self.page)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.le_filename = QtGui.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_filename.setFont(font)
        self.le_filename.setFrame(True)
        self.le_filename.setReadOnly(False)
        self.le_filename.setObjectName("le_filename")
        self.horizontalLayout_5.addWidget(self.le_filename)
        self.pb_get_filename = QtGui.QToolButton(self.frame)
        self.pb_get_filename.setObjectName("pb_get_filename")
        self.horizontalLayout_5.addWidget(self.pb_get_filename)
        self.verticalLayout.addWidget(self.frame)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pb_next = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_next.sizePolicy().hasHeightForWidth())
        self.pb_next.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_next.setIcon(icon)
        self.pb_next.setIconSize(QtCore.QSize(32, 32))
        self.pb_next.setObjectName("pb_next")
        self.horizontalLayout.addWidget(self.pb_next)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.stack_steps.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_page2 = QtGui.QFrame(self.page_2)
        self.frame_page2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_page2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_page2.setObjectName("frame_page2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_page2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.p1_ok_icon = QtGui.QLabel(self.frame_page2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p1_ok_icon.sizePolicy().hasHeightForWidth())
        self.p1_ok_icon.setSizePolicy(sizePolicy)
        self.p1_ok_icon.setPixmap(QtGui.QPixmap(":/images/images/apply.png"))
        self.p1_ok_icon.setMargin(5)
        self.p1_ok_icon.setObjectName("p1_ok_icon")
        self.horizontalLayout_8.addWidget(self.p1_ok_icon)
        self.p1_info_icon = QtGui.QLabel(self.frame_page2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p1_info_icon.sizePolicy().hasHeightForWidth())
        self.p1_info_icon.setSizePolicy(sizePolicy)
        self.p1_info_icon.setPixmap(QtGui.QPixmap(":/images/images/messagebox_info.png"))
        self.p1_info_icon.setMargin(5)
        self.p1_info_icon.setObjectName("p1_info_icon")
        self.horizontalLayout_8.addWidget(self.p1_info_icon)
        self.p1_warning_icon = QtGui.QLabel(self.frame_page2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p1_warning_icon.sizePolicy().hasHeightForWidth())
        self.p1_warning_icon.setSizePolicy(sizePolicy)
        self.p1_warning_icon.setPixmap(QtGui.QPixmap(":/images/images/messagebox_warning.png"))
        self.p1_warning_icon.setMargin(5)
        self.p1_warning_icon.setObjectName("p1_warning_icon")
        self.horizontalLayout_8.addWidget(self.p1_warning_icon)
        self.p1_text = QtGui.QLabel(self.frame_page2)
        self.p1_text.setWordWrap(True)
        self.p1_text.setObjectName("p1_text")
        self.horizontalLayout_8.addWidget(self.p1_text)
        self.pb_show_warnings = QtGui.QPushButton(self.frame_page2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_show_warnings.sizePolicy().hasHeightForWidth())
        self.pb_show_warnings.setSizePolicy(sizePolicy)
        self.pb_show_warnings.setObjectName("pb_show_warnings")
        self.horizontalLayout_8.addWidget(self.pb_show_warnings)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.frame_2 = QtGui.QFrame(self.frame_page2)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.le_filename_out = QtGui.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_filename_out.setFont(font)
        self.le_filename_out.setFrame(True)
        self.le_filename_out.setReadOnly(False)
        self.le_filename_out.setObjectName("le_filename_out")
        self.horizontalLayout_6.addWidget(self.le_filename_out)
        self.pb_get_filename_out = QtGui.QToolButton(self.frame_2)
        self.pb_get_filename_out.setObjectName("pb_get_filename_out")
        self.horizontalLayout_6.addWidget(self.pb_get_filename_out)
        self.verticalLayout_3.addWidget(self.frame_2)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.verticalLayout_4.addWidget(self.frame_page2)
        self.frame_log = QtGui.QFrame(self.page_2)
        self.frame_log.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_log.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_log.setObjectName("frame_log")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame_log)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.txt_log = QtGui.QTextEdit(self.frame_log)
        self.txt_log.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.txt_log.setObjectName("txt_log")
        self.verticalLayout_5.addWidget(self.txt_log)
        self.verticalLayout_4.addWidget(self.frame_log)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pb_back = QtGui.QPushButton(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_back.sizePolicy().hasHeightForWidth())
        self.pb_back.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_back.setIcon(icon1)
        self.pb_back.setIconSize(QtCore.QSize(32, 32))
        self.pb_back.setObjectName("pb_back")
        self.horizontalLayout_3.addWidget(self.pb_back)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.pb_log = QtGui.QPushButton(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_log.sizePolicy().hasHeightForWidth())
        self.pb_log.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/images/messagebox_info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_log.setIcon(icon2)
        self.pb_log.setIconSize(QtCore.QSize(32, 32))
        self.pb_log.setCheckable(True)
        self.pb_log.setChecked(False)
        self.pb_log.setFlat(False)
        self.pb_log.setObjectName("pb_log")
        self.horizontalLayout_3.addWidget(self.pb_log)
        self.pb_save = QtGui.QPushButton(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_save.sizePolicy().hasHeightForWidth())
        self.pb_save.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/images/filesave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_save.setIcon(icon3)
        self.pb_save.setIconSize(QtCore.QSize(32, 32))
        self.pb_save.setObjectName("pb_save")
        self.horizontalLayout_3.addWidget(self.pb_save)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.stack_steps.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.stack_steps)

        self.retranslateUi(ConverterGui)
        self.stack_steps.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ConverterGui)

    def retranslateUi(self, ConverterGui):
        ConverterGui.setWindowTitle(QtGui.QApplication.translate("ConverterGui", "Converter for Opus Project Files", None, QtGui.QApplication.UnicodeUTF8))
        self.p0_text.setText(QtGui.QApplication.translate("ConverterGui", "error message", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_get_filename.setToolTip(QtGui.QApplication.translate("ConverterGui", "Select file to convert", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_get_filename.setText(QtGui.QApplication.translate("ConverterGui", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_next.setText(QtGui.QApplication.translate("ConverterGui", "Inspect", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_next.setShortcut(QtGui.QApplication.translate("ConverterGui", "Ctrl+K", None, QtGui.QApplication.UnicodeUTF8))
        self.p1_text.setText(QtGui.QApplication.translate("ConverterGui", "information", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_show_warnings.setText(QtGui.QApplication.translate("ConverterGui", "warnings", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_get_filename_out.setText(QtGui.QApplication.translate("ConverterGui", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_back.setText(QtGui.QApplication.translate("ConverterGui", "Inspect another file", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_back.setShortcut(QtGui.QApplication.translate("ConverterGui", "Ctrl+K", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_log.setText(QtGui.QApplication.translate("ConverterGui", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_log.setShortcut(QtGui.QApplication.translate("ConverterGui", "Ctrl+K", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_save.setText(QtGui.QApplication.translate("ConverterGui", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_save.setShortcut(QtGui.QApplication.translate("ConverterGui", "Ctrl+K", None, QtGui.QApplication.UnicodeUTF8))

from . import resources_rc
