#
# UrbanSim software. Copyright (C) 1998-2007 University of Washington
# 
# You can redistribute this program and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation
# (http://www.gnu.org/copyleft/gpl.html).
# 
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the file LICENSE.html for copyright
# and licensing information, and the file ACKNOWLEDGMENTS.html for funding and
# other acknowledgments.
# 

from urbansim.datasets.travel_data_dataset import TravelDataDataset
from opus_core.store.mysql_storage import mysql_storage
from urbansim.datasets.zone_dataset import ZoneDataset
from opus_core.resources import Resources
from numpy import array, float32, ones
from os.path import join
import os
from opus_core.logger import logger
from opus_emme2.models.abstract_emme2_travel_model import AbstractEmme2TravelModel
from opus_core.store.attribute_cache import AttributeCache
from opus_core.session_configuration import SessionConfiguration

class RunEmmissionEmme2Macros(AbstractEmme2TravelModel):
    """Class to run specified Emme2 macros. run_emmission_emme2_macros should run before 
       opus_emme2.models.get_emme2_data_into_cache. Then in the configuration, if there is some
       desired matrix generated by a macro, the matrix_variable_map config entry will store it.
       The macro specification should also have a specification of the bank it should run in.
    """

    def run(self, config, year):
        """This is the main entry point.  It gets the appropriate values from the 
        travel_model_configuration part of this config, and then runs the specified 
        emme/2 macros."""
        from opus_emme2.travel_model_output import TravelModelOutput
        import opus_emme2
        tm_output = TravelModelOutput()
        macro_dir = os.path.join(opus_emme2.__path__[0],'emmission_emme2_macros')
        specified_macros = config['travel_model_configuration'][year]['emmission_emme2_macros']
        for macro_name, macro_info in specified_macros.iteritems():
            bank = macro_info['bank']
            bank_path = self.get_emme2_dir(config, year, bank)
            macro_path = os.path.join(macro_dir, bank, macro_name)
            tm_output.run_emme2_macro(macro_path, bank_path, macro_info['scenario'])

        
if __name__ == "__main__":
    try: import wingdbstub
    except: pass
    from optparse import OptionParser
    from opus_core.file_utilities import get_resources_from_file
    parser = OptionParser()
    parser.add_option("-r", "--resources", dest="resources_file_name", action="store", type="string",
                      help="Name of file containing resources")
    parser.add_option("-y", "--year", dest="year", action="store", type="int",
                      help="Year in which to 'run' the travel model")
    (options, args) = parser.parse_args()
   
    r = get_resources_from_file(options.resources_file_name)
    resources = Resources(get_resources_from_file(options.resources_file_name))
    
    SessionConfiguration(new_instance=True,
                         package_order=resources['dataset_pool_configuration'].package_order,
                         package_order_exceptions=resources['dataset_pool_configuration'].package_order_exceptions,                              
                         in_storage=AttributeCache())

    logger.enable_memory_logging()
    RunEmmissionEmme2Macros().run(resources, options.year)    
