Queries to count number of households in each age of head and income bin						

			AGE_GP		INCOME	
		create table tempcount;				

		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	1	and income=	1	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	1	and income=	2	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	1	and income=	3	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	1	and income=	4	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	1	and income=	5	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	1	and income=	6	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	1	and income=	7	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	1	and income=	8	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	2	and income=	1	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	2	and income=	2	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	2	and income=	3	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	2	and income=	4	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	2	and income=	5	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	2	and income=	6	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	2	and income=	7	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	2	and income=	8	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	3	and income=	1	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	3	and income=	2	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	3	and income=	3	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	3	and income=	4	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	3	and income=	5	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	3	and income=	6	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	3	and income=	7	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	3	and income=	8	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	4	and income=	1	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	4	and income=	2	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	4	and income=	3	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	4	and income=	4	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	4	and income=	5	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	4	and income=	6	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	4	and income=	7	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	4	and income=	8	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	5	and income=	1	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	5	and income=	2	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	5	and income=	3	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	5	and income=	4	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	5	and income=	5	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	5	and income=	6	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	5	and income=	7	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	5	and income=	8	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	6	and income=	1	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	6	and income=	2	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	6	and income=	3	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	6	and income=	4	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	6	and income=	5	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	6	and income=	6	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	6	and income=	7	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	6	and income=	8	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	7	and income=	1	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	7	and income=	2	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	7	and income=	3	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	7	and income=	4	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	7	and income=	5	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	7	and income=	6	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	7	and income=	7	;
		"insert into tempcount select age_of_head,income,count(*) from wave2 where age_of_head="	7	and income=	8	;
Queries to count number of moving households in each age of head and income bin						
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	1	and income=	1	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	1	and income=	2	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	1	and income=	3	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	1	and income=	4	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	1	and income=	5	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	1	and income=	6	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	1	and income=	7	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	1	and income=	8	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	2	and income=	1	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	2	and income=	2	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	2	and income=	3	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	2	and income=	4	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	2	and income=	5	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	2	and income=	6	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	2	and income=	7	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	2	and income=	8	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	3	and income=	1	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	3	and income=	2	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	3	and income=	3	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	3	and income=	4	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	3	and income=	5	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	3	and income=	6	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	3	and income=	7	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	3	and income=	8	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	4	and income=	1	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	4	and income=	2	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	4	and income=	3	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	4	and income=	4	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	4	and income=	5	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	4	and income=	6	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	4	and income=	7	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	4	and income=	8	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	5	and income=	1	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	5	and income=	2	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	5	and income=	3	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	5	and income=	4	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	5	and income=	5	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	5	and income=	6	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	5	and income=	7	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	5	and income=	8	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	6	and income=	1	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	6	and income=	2	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	6	and income=	3	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	6	and income=	4	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	6	and income=	5	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	6	and income=	6	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	6	and income=	7	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	6	and income=	8	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	7	and income=	1	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	7	and income=	2	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	7	and income=	3	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	7	and income=	4	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	7	and income=	5	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	7	and income=	6	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	7	and income=	7	where hhchg=1;
		"insert into tempcount select age_of_head,income,count(*) as cntcg from wave2 where age_of_head="	7	and income=	8	where hhchg=1;
