# Opus/UrbanSim urban simulation software.
# Copyright (C) 2005, 2006, 2007, 2008, 2009 University of Washington
# See opus_docs/LICENSE 


specification={
1:
[
 ('constant', 'constant'),

 ('urbansim.gridcell.building_age', 'BLD_AGE'),
# ('urbansim.gridcell.is_outside_urban_growth_boundary', 'OUT_UGB'),
 ('urbansim.gridcell.is_near_arterial', 'ART'),
 ('urbansim.gridcell.is_near_highway', 'HWY'),
# ('urbansim.gridcell.ln_distance_to_highway', 'LDHW'),
# ('urbansim.gridcell.percent_floodplain', 'PFLOOD'),
# ('urbansim.gridcell.percent_stream_buffer', 'PSTREAM'),

#  ('urbansim.gridcell.ln_total_improvement_value', 'LIMPV'),

#  ('urbansim.gridcell.ln_total_nonresidential_sqft_within_walking_distance', 'LNRSFW'),
# #('urbansim.gridcell.ln_commercial_sqft', 'LSFC'),
# ('urbansim.gridcell.ln_commercial_sqft_within_walking_distance', 'LSFCW'),
# #('urbansim.gridcell.ln_industrial_sqft', 'LSFI'),
# ('urbansim.gridcell.ln_industrial_sqft_within_walking_distance', 'LSFIW'),

# # ('urbansim.gridcell.ln_residential_units', 'LDU'),
  ('urbansim.gridcell.ln_residential_units_within_walking_distance', 'LDUW'),
# ('urbansim.gridcell.residential_density', 'RDEN'),
# ('urbansim.gridcell. population_density', 'POPDEN'),
# ('urbansim.gridcell.ln_total_population_within_walking_distance', 'LPOPW'),
#  ('urbansim.gridcell.ln_total_employment_within_walking_distance', 'LE_W'),
 ('urbansim.gridcell.ln_basic_sector_employment_within_walking_distance', 'LE_BW'),
 ('urbansim.gridcell.ln_retail_sector_employment_within_walking_distance', 'LE_REW'),
 ('urbansim.gridcell.ln_service_sector_employment_within_walking_distance', 'LE_SEW'),

 ('urbansim.gridcell.percent_commercial_within_walking_distance','PCW'),
 ('urbansim.gridcell.percent_industrial_within_walking_distance','PIW'), 
 ('urbansim.gridcell.percent_residential_within_walking_distance','PRW'),
  ('urbansim.gridcell.percent_developed_within_walking_distance', 'PDEVW'),
# ('urbansim.gridcell.percent_open_space_within_walking_distance','POSW'), 
  ('urbansim.gridcell.percent_water', 'PWATER'),
#  ('urbansim.gridcell.percent_wetland', 'PWETLA'),

# ('ln(urbansim.gridcell.average_income)','LAI'),
 ('ln(urbansim.gridcell.average_income_within_walking_distance)','LAIW'),
# ('urbansim.gridcell.percent_low_income_households_within_walking_distance', 'PLIW'),
# #('urbansim.gridcell.percent_mid_income_households_within_walking_distance', 'PMIW'),
# ('urbansim.gridcell.percent_high_income_households_within_walking_distance', 'PHIW'),
# ('urbansim.gridcell.is_average_income_within_walking_distance_high_income', 'AIHIW'),
# ('urbansim.gridcell.is_average_income_high_income', 'AIHI'), 
 
#  ('LNGCWEDA = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_drive_alone))','LNGCWEDA'),
#  ('LNGCWETW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_transit_walk))','LNGCWETW'),
#  ('LNGCWEW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_walk))','LNGCWEW'),
#  ('LNE20MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_drive_alone))','LNE20MDA'),
#  ('LNE20MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_transit_walk))','LNE20MTW'),
#  ('LNE20MW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_walk))','LNE20MW'),
  ('LNE30MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_drive_alone))','LNE30MDA'),
  ('LNE30MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_transit_walk))','LNE30MTW'),
  ('gc_cbd = gridcell.disaggregate(psrc.zone.generalized_cost_hbw_am_drive_alone_to_129)', 'GC_CBD'),
#  ('psrc.gridcell.travel_time_hbw_am_drive_alone_to_cbd', 'TT_CBD'),
],
2:
[
 ('constant', 'constant'),

 ('urbansim.gridcell.building_age', 'BLD_AGE'),
# ('urbansim.gridcell.is_outside_urban_growth_boundary', 'OUT_UGB'),
 ('urbansim.gridcell.is_near_arterial', 'ART'),
 ('urbansim.gridcell.is_near_highway', 'HWY'),
# ('urbansim.gridcell.ln_distance_to_highway', 'LDHW'),
# ('urbansim.gridcell.percent_floodplain', 'PFLOOD'),
# ('urbansim.gridcell.percent_stream_buffer', 'PSTREAM'),

#  ('urbansim.gridcell.ln_total_improvement_value', 'LIMPV'),

#  ('urbansim.gridcell.ln_total_nonresidential_sqft_within_walking_distance', 'LNRSFW'),
# #('urbansim.gridcell.ln_commercial_sqft', 'LSFC'),
# ('urbansim.gridcell.ln_commercial_sqft_within_walking_distance', 'LSFCW'),
# #('urbansim.gridcell.ln_industrial_sqft', 'LSFI'),
# ('urbansim.gridcell.ln_industrial_sqft_within_walking_distance', 'LSFIW'),

# # ('urbansim.gridcell.ln_residential_units', 'LDU'),
  ('urbansim.gridcell.ln_residential_units_within_walking_distance', 'LDUW'),
# ('urbansim.gridcell.residential_density', 'RDEN'),
# ('urbansim.gridcell. population_density', 'POPDEN'),
# ('urbansim.gridcell.ln_total_population_within_walking_distance', 'LPOPW'),
#  ('urbansim.gridcell.ln_total_employment_within_walking_distance', 'LE_W'),
 ('urbansim.gridcell.ln_basic_sector_employment_within_walking_distance', 'LE_BW'),
 ('urbansim.gridcell.ln_retail_sector_employment_within_walking_distance', 'LE_REW'),
 ('urbansim.gridcell.ln_service_sector_employment_within_walking_distance', 'LE_SEW'),

 ('urbansim.gridcell.percent_commercial_within_walking_distance','PCW'),
 ('urbansim.gridcell.percent_industrial_within_walking_distance','PIW'), 
 ('urbansim.gridcell.percent_residential_within_walking_distance','PRW'),
  ('urbansim.gridcell.percent_developed_within_walking_distance', 'PDEVW'),
# ('urbansim.gridcell.percent_open_space_within_walking_distance','POSW'), 
  ('urbansim.gridcell.percent_water', 'PWATER'),
#  ('urbansim.gridcell.percent_wetland', 'PWETLA'),

# ('ln(urbansim.gridcell.average_income)','LAI'),
 ('ln(urbansim.gridcell.average_income_within_walking_distance)','LAIW'),
# ('urbansim.gridcell.percent_low_income_households_within_walking_distance', 'PLIW'),
# #('urbansim.gridcell.percent_mid_income_households_within_walking_distance', 'PMIW'),
# ('urbansim.gridcell.percent_high_income_households_within_walking_distance', 'PHIW'),
# ('urbansim.gridcell.is_average_income_within_walking_distance_high_income', 'AIHIW'),
# ('urbansim.gridcell.is_average_income_high_income', 'AIHI'), 
 
#  ('LNGCWEDA = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_drive_alone))','LNGCWEDA'),
#  ('LNGCWETW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_transit_walk))','LNGCWETW'),
#  ('LNGCWEW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_walk))','LNGCWEW'),
#  ('LNE20MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_drive_alone))','LNE20MDA'),
#  ('LNE20MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_transit_walk))','LNE20MTW'),
#  ('LNE20MW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_walk))','LNE20MW'),
  ('LNE30MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_drive_alone))','LNE30MDA'),
  ('LNE30MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_transit_walk))','LNE30MTW'),
  ('gc_cbd = gridcell.disaggregate(psrc.zone.generalized_cost_hbw_am_drive_alone_to_129)', 'GC_CBD'),
#  ('psrc.gridcell.travel_time_hbw_am_drive_alone_to_cbd', 'TT_CBD'),
],

3:
[
 ('constant', 'constant'),

 ('urbansim.gridcell.building_age', 'BLD_AGE'),
# ('urbansim.gridcell.is_outside_urban_growth_boundary', 'OUT_UGB'),
 ('urbansim.gridcell.is_near_arterial', 'ART'),
 ('urbansim.gridcell.is_near_highway', 'HWY'),
# ('urbansim.gridcell.ln_distance_to_highway', 'LDHW'),
# ('urbansim.gridcell.percent_floodplain', 'PFLOOD'),
# ('urbansim.gridcell.percent_stream_buffer', 'PSTREAM'),

#  ('urbansim.gridcell.ln_total_improvement_value', 'LIMPV'),

#  ('urbansim.gridcell.ln_total_nonresidential_sqft_within_walking_distance', 'LNRSFW'),
# #('urbansim.gridcell.ln_commercial_sqft', 'LSFC'),
# ('urbansim.gridcell.ln_commercial_sqft_within_walking_distance', 'LSFCW'),
# #('urbansim.gridcell.ln_industrial_sqft', 'LSFI'),
# ('urbansim.gridcell.ln_industrial_sqft_within_walking_distance', 'LSFIW'),

# # ('urbansim.gridcell.ln_residential_units', 'LDU'),
  ('urbansim.gridcell.ln_residential_units_within_walking_distance', 'LDUW'),
# ('urbansim.gridcell.residential_density', 'RDEN'),
# ('urbansim.gridcell. population_density', 'POPDEN'),
# ('urbansim.gridcell.ln_total_population_within_walking_distance', 'LPOPW'),
#  ('urbansim.gridcell.ln_total_employment_within_walking_distance', 'LE_W'),
 ('urbansim.gridcell.ln_basic_sector_employment_within_walking_distance', 'LE_BW'),
 ('urbansim.gridcell.ln_retail_sector_employment_within_walking_distance', 'LE_REW'),
 ('urbansim.gridcell.ln_service_sector_employment_within_walking_distance', 'LE_SEW'),

 ('urbansim.gridcell.percent_commercial_within_walking_distance','PCW'),
 ('urbansim.gridcell.percent_industrial_within_walking_distance','PIW'), 
 ('urbansim.gridcell.percent_residential_within_walking_distance','PRW'),
  ('urbansim.gridcell.percent_developed_within_walking_distance', 'PDEVW'),
# ('urbansim.gridcell.percent_open_space_within_walking_distance','POSW'), 
  ('urbansim.gridcell.percent_water', 'PWATER'),
#  ('urbansim.gridcell.percent_wetland', 'PWETLA'),

# ('ln(urbansim.gridcell.average_income)','LAI'),
 ('ln(urbansim.gridcell.average_income_within_walking_distance)','LAIW'),
# ('urbansim.gridcell.percent_low_income_households_within_walking_distance', 'PLIW'),
# #('urbansim.gridcell.percent_mid_income_households_within_walking_distance', 'PMIW'),
# ('urbansim.gridcell.percent_high_income_households_within_walking_distance', 'PHIW'),
# ('urbansim.gridcell.is_average_income_within_walking_distance_high_income', 'AIHIW'),
# ('urbansim.gridcell.is_average_income_high_income', 'AIHI'), 
 
#  ('LNGCWEDA = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_drive_alone))','LNGCWEDA'),
#  ('LNGCWETW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_transit_walk))','LNGCWETW'),
#  ('LNGCWEW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_walk))','LNGCWEW'),
#  ('LNE20MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_drive_alone))','LNE20MDA'),
#  ('LNE20MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_transit_walk))','LNE20MTW'),
#  ('LNE20MW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_walk))','LNE20MW'),
  ('LNE30MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_drive_alone))','LNE30MDA'),
  ('LNE30MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_transit_walk))','LNE30MTW'),
  ('gc_cbd = gridcell.disaggregate(psrc.zone.generalized_cost_hbw_am_drive_alone_to_129)', 'GC_CBD'),
#  ('psrc.gridcell.travel_time_hbw_am_drive_alone_to_cbd', 'TT_CBD'),
],

4:
[
 ('constant', 'constant'),

 ('urbansim.gridcell.building_age', 'BLD_AGE'),
# ('urbansim.gridcell.is_outside_urban_growth_boundary', 'OUT_UGB'),
 ('urbansim.gridcell.is_near_arterial', 'ART'),
 ('urbansim.gridcell.is_near_highway', 'HWY'),
# ('urbansim.gridcell.ln_distance_to_highway', 'LDHW'),
# ('urbansim.gridcell.percent_floodplain', 'PFLOOD'),
# ('urbansim.gridcell.percent_stream_buffer', 'PSTREAM'),

#  ('urbansim.gridcell.ln_total_improvement_value', 'LIMPV'),

#  ('urbansim.gridcell.ln_total_nonresidential_sqft_within_walking_distance', 'LNRSFW'),
# #('urbansim.gridcell.ln_commercial_sqft', 'LSFC'),
# ('urbansim.gridcell.ln_commercial_sqft_within_walking_distance', 'LSFCW'),
# #('urbansim.gridcell.ln_industrial_sqft', 'LSFI'),
# ('urbansim.gridcell.ln_industrial_sqft_within_walking_distance', 'LSFIW'),

# # ('urbansim.gridcell.ln_residential_units', 'LDU'),
  ('urbansim.gridcell.ln_residential_units_within_walking_distance', 'LDUW'),
# ('urbansim.gridcell.residential_density', 'RDEN'),
# ('urbansim.gridcell. population_density', 'POPDEN'),
# ('urbansim.gridcell.ln_total_population_within_walking_distance', 'LPOPW'),
#  ('urbansim.gridcell.ln_total_employment_within_walking_distance', 'LE_W'),
 ('urbansim.gridcell.ln_basic_sector_employment_within_walking_distance', 'LE_BW'),
 ('urbansim.gridcell.ln_retail_sector_employment_within_walking_distance', 'LE_REW'),
 ('urbansim.gridcell.ln_service_sector_employment_within_walking_distance', 'LE_SEW'),

 ('urbansim.gridcell.percent_commercial_within_walking_distance','PCW'),
 ('urbansim.gridcell.percent_industrial_within_walking_distance','PIW'), 
 ('urbansim.gridcell.percent_residential_within_walking_distance','PRW'),
  ('urbansim.gridcell.percent_developed_within_walking_distance', 'PDEVW'),
# ('urbansim.gridcell.percent_open_space_within_walking_distance','POSW'), 
  ('urbansim.gridcell.percent_water', 'PWATER'),
#  ('urbansim.gridcell.percent_wetland', 'PWETLA'),

# ('ln(urbansim.gridcell.average_income)','LAI'),
 ('ln(urbansim.gridcell.average_income_within_walking_distance)','LAIW'),
# ('urbansim.gridcell.percent_low_income_households_within_walking_distance', 'PLIW'),
# #('urbansim.gridcell.percent_mid_income_households_within_walking_distance', 'PMIW'),
# ('urbansim.gridcell.percent_high_income_households_within_walking_distance', 'PHIW'),
# ('urbansim.gridcell.is_average_income_within_walking_distance_high_income', 'AIHIW'),
# ('urbansim.gridcell.is_average_income_high_income', 'AIHI'), 
 
#  ('LNGCWEDA = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_drive_alone))','LNGCWEDA'),
#  ('LNGCWETW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_transit_walk))','LNGCWETW'),
#  ('LNGCWEW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_walk))','LNGCWEW'),
#  ('LNE20MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_drive_alone))','LNE20MDA'),
#  ('LNE20MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_transit_walk))','LNE20MTW'),
#  ('LNE20MW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_walk))','LNE20MW'),
  ('LNE30MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_drive_alone))','LNE30MDA'),
  ('LNE30MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_transit_walk))','LNE30MTW'),
  ('gc_cbd = gridcell.disaggregate(psrc.zone.generalized_cost_hbw_am_drive_alone_to_129)', 'GC_CBD'),
#  ('psrc.gridcell.travel_time_hbw_am_drive_alone_to_cbd', 'TT_CBD'),
],

5:
[
 ('constant', 'constant'),

 ('urbansim.gridcell.building_age', 'BLD_AGE'),
# ('urbansim.gridcell.is_outside_urban_growth_boundary', 'OUT_UGB'),
 ('urbansim.gridcell.is_near_arterial', 'ART'),
 ('urbansim.gridcell.is_near_highway', 'HWY'),
# ('urbansim.gridcell.ln_distance_to_highway', 'LDHW'),
# ('urbansim.gridcell.percent_floodplain', 'PFLOOD'),
# ('urbansim.gridcell.percent_stream_buffer', 'PSTREAM'),

#  ('urbansim.gridcell.ln_total_improvement_value', 'LIMPV'),

#  ('urbansim.gridcell.ln_total_nonresidential_sqft_within_walking_distance', 'LNRSFW'),
# #('urbansim.gridcell.ln_commercial_sqft', 'LSFC'),
# ('urbansim.gridcell.ln_commercial_sqft_within_walking_distance', 'LSFCW'),
# #('urbansim.gridcell.ln_industrial_sqft', 'LSFI'),
# ('urbansim.gridcell.ln_industrial_sqft_within_walking_distance', 'LSFIW'),

# # ('urbansim.gridcell.ln_residential_units', 'LDU'),
  ('urbansim.gridcell.ln_residential_units_within_walking_distance', 'LDUW'),
# ('urbansim.gridcell.residential_density', 'RDEN'),
# ('urbansim.gridcell. population_density', 'POPDEN'),
# ('urbansim.gridcell.ln_total_population_within_walking_distance', 'LPOPW'),
#  ('urbansim.gridcell.ln_total_employment_within_walking_distance', 'LE_W'),
 ('urbansim.gridcell.ln_basic_sector_employment_within_walking_distance', 'LE_BW'),
 ('urbansim.gridcell.ln_retail_sector_employment_within_walking_distance', 'LE_REW'),
 ('urbansim.gridcell.ln_service_sector_employment_within_walking_distance', 'LE_SEW'),

 ('urbansim.gridcell.percent_commercial_within_walking_distance','PCW'),
 ('urbansim.gridcell.percent_industrial_within_walking_distance','PIW'), 
 ('urbansim.gridcell.percent_residential_within_walking_distance','PRW'),
  ('urbansim.gridcell.percent_developed_within_walking_distance', 'PDEVW'),
# ('urbansim.gridcell.percent_open_space_within_walking_distance','POSW'), 
  ('urbansim.gridcell.percent_water', 'PWATER'),
#  ('urbansim.gridcell.percent_wetland', 'PWETLA'),

# ('ln(urbansim.gridcell.average_income)','LAI'),
 ('ln(urbansim.gridcell.average_income_within_walking_distance)','LAIW'),
# ('urbansim.gridcell.percent_low_income_households_within_walking_distance', 'PLIW'),
# #('urbansim.gridcell.percent_mid_income_households_within_walking_distance', 'PMIW'),
# ('urbansim.gridcell.percent_high_income_households_within_walking_distance', 'PHIW'),
# ('urbansim.gridcell.is_average_income_within_walking_distance_high_income', 'AIHIW'),
# ('urbansim.gridcell.is_average_income_high_income', 'AIHI'), 
 
#  ('LNGCWEDA = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_drive_alone))','LNGCWEDA'),
#  ('LNGCWETW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_transit_walk))','LNGCWETW'),
#  ('LNGCWEW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_walk))','LNGCWEW'),
#  ('LNE20MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_drive_alone))','LNE20MDA'),
#  ('LNE20MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_transit_walk))','LNE20MTW'),
#  ('LNE20MW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_walk))','LNE20MW'),
  ('LNE30MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_drive_alone))','LNE30MDA'),
  ('LNE30MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_transit_walk))','LNE30MTW'),
  ('gc_cbd = gridcell.disaggregate(psrc.zone.generalized_cost_hbw_am_drive_alone_to_129)', 'GC_CBD'),
#  ('psrc.gridcell.travel_time_hbw_am_drive_alone_to_cbd', 'TT_CBD'),
],

6:
[
 ('constant', 'constant'),

 ('urbansim.gridcell.building_age', 'BLD_AGE'),
# ('urbansim.gridcell.is_outside_urban_growth_boundary', 'OUT_UGB'),
 ('urbansim.gridcell.is_near_arterial', 'ART'),
 ('urbansim.gridcell.is_near_highway', 'HWY'),
# ('urbansim.gridcell.ln_distance_to_highway', 'LDHW'),
# ('urbansim.gridcell.percent_floodplain', 'PFLOOD'),
# ('urbansim.gridcell.percent_stream_buffer', 'PSTREAM'),

#  ('urbansim.gridcell.ln_total_improvement_value', 'LIMPV'),

#  ('urbansim.gridcell.ln_total_nonresidential_sqft_within_walking_distance', 'LNRSFW'),
# #('urbansim.gridcell.ln_commercial_sqft', 'LSFC'),
# ('urbansim.gridcell.ln_commercial_sqft_within_walking_distance', 'LSFCW'),
# #('urbansim.gridcell.ln_industrial_sqft', 'LSFI'),
# ('urbansim.gridcell.ln_industrial_sqft_within_walking_distance', 'LSFIW'),

# # ('urbansim.gridcell.ln_residential_units', 'LDU'),
  ('urbansim.gridcell.ln_residential_units_within_walking_distance', 'LDUW'),
# ('urbansim.gridcell.residential_density', 'RDEN'),
# ('urbansim.gridcell. population_density', 'POPDEN'),
# ('urbansim.gridcell.ln_total_population_within_walking_distance', 'LPOPW'),
#  ('urbansim.gridcell.ln_total_employment_within_walking_distance', 'LE_W'),
 ('urbansim.gridcell.ln_basic_sector_employment_within_walking_distance', 'LE_BW'),
 ('urbansim.gridcell.ln_retail_sector_employment_within_walking_distance', 'LE_REW'),
 ('urbansim.gridcell.ln_service_sector_employment_within_walking_distance', 'LE_SEW'),

 ('urbansim.gridcell.percent_commercial_within_walking_distance','PCW'),
 ('urbansim.gridcell.percent_industrial_within_walking_distance','PIW'), 
 ('urbansim.gridcell.percent_residential_within_walking_distance','PRW'),
  ('urbansim.gridcell.percent_developed_within_walking_distance', 'PDEVW'),
# ('urbansim.gridcell.percent_open_space_within_walking_distance','POSW'), 
  ('urbansim.gridcell.percent_water', 'PWATER'),
#  ('urbansim.gridcell.percent_wetland', 'PWETLA'),

# ('ln(urbansim.gridcell.average_income)','LAI'),
 ('ln(urbansim.gridcell.average_income_within_walking_distance)','LAIW'),
# ('urbansim.gridcell.percent_low_income_households_within_walking_distance', 'PLIW'),
# #('urbansim.gridcell.percent_mid_income_households_within_walking_distance', 'PMIW'),
# ('urbansim.gridcell.percent_high_income_households_within_walking_distance', 'PHIW'),
# ('urbansim.gridcell.is_average_income_within_walking_distance_high_income', 'AIHIW'),
# ('urbansim.gridcell.is_average_income_high_income', 'AIHI'), 
 
#  ('LNGCWEDA = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_drive_alone))','LNGCWEDA'),
#  ('LNGCWETW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_transit_walk))','LNGCWETW'),
#  ('LNGCWEW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_walk))','LNGCWEW'),
#  ('LNE20MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_drive_alone))','LNE20MDA'),
#  ('LNE20MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_transit_walk))','LNE20MTW'),
#  ('LNE20MW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_walk))','LNE20MW'),
  ('LNE30MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_drive_alone))','LNE30MDA'),
  ('LNE30MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_transit_walk))','LNE30MTW'),
  ('gc_cbd = gridcell.disaggregate(psrc.zone.generalized_cost_hbw_am_drive_alone_to_129)', 'GC_CBD'),
#  ('psrc.gridcell.travel_time_hbw_am_drive_alone_to_cbd', 'TT_CBD'),
],

7:
[
 ('constant', 'constant'),

 ('urbansim.gridcell.building_age', 'BLD_AGE'),
# ('urbansim.gridcell.is_outside_urban_growth_boundary', 'OUT_UGB'),
 ('urbansim.gridcell.is_near_arterial', 'ART'),
 ('urbansim.gridcell.is_near_highway', 'HWY'),
# ('urbansim.gridcell.ln_distance_to_highway', 'LDHW'),
# ('urbansim.gridcell.percent_floodplain', 'PFLOOD'),
# ('urbansim.gridcell.percent_stream_buffer', 'PSTREAM'),

#  ('urbansim.gridcell.ln_total_improvement_value', 'LIMPV'),

#  ('urbansim.gridcell.ln_total_nonresidential_sqft_within_walking_distance', 'LNRSFW'),
# #('urbansim.gridcell.ln_commercial_sqft', 'LSFC'),
# ('urbansim.gridcell.ln_commercial_sqft_within_walking_distance', 'LSFCW'),
# #('urbansim.gridcell.ln_industrial_sqft', 'LSFI'),
# ('urbansim.gridcell.ln_industrial_sqft_within_walking_distance', 'LSFIW'),

# # ('urbansim.gridcell.ln_residential_units', 'LDU'),
  ('urbansim.gridcell.ln_residential_units_within_walking_distance', 'LDUW'),
# ('urbansim.gridcell.residential_density', 'RDEN'),
# ('urbansim.gridcell. population_density', 'POPDEN'),
# ('urbansim.gridcell.ln_total_population_within_walking_distance', 'LPOPW'),
#  ('urbansim.gridcell.ln_total_employment_within_walking_distance', 'LE_W'),
 ('urbansim.gridcell.ln_basic_sector_employment_within_walking_distance', 'LE_BW'),
 ('urbansim.gridcell.ln_retail_sector_employment_within_walking_distance', 'LE_REW'),
 ('urbansim.gridcell.ln_service_sector_employment_within_walking_distance', 'LE_SEW'),

 ('urbansim.gridcell.percent_commercial_within_walking_distance','PCW'),
 ('urbansim.gridcell.percent_industrial_within_walking_distance','PIW'), 
 ('urbansim.gridcell.percent_residential_within_walking_distance','PRW'),
  ('urbansim.gridcell.percent_developed_within_walking_distance', 'PDEVW'),
# ('urbansim.gridcell.percent_open_space_within_walking_distance','POSW'), 
  ('urbansim.gridcell.percent_water', 'PWATER'),
#  ('urbansim.gridcell.percent_wetland', 'PWETLA'),

# ('ln(urbansim.gridcell.average_income)','LAI'),
 ('ln(urbansim.gridcell.average_income_within_walking_distance)','LAIW'),
# ('urbansim.gridcell.percent_low_income_households_within_walking_distance', 'PLIW'),
# #('urbansim.gridcell.percent_mid_income_households_within_walking_distance', 'PMIW'),
# ('urbansim.gridcell.percent_high_income_households_within_walking_distance', 'PHIW'),
# ('urbansim.gridcell.is_average_income_within_walking_distance_high_income', 'AIHIW'),
# ('urbansim.gridcell.is_average_income_high_income', 'AIHI'), 
 
#  ('LNGCWEDA = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_drive_alone))','LNGCWEDA'),
#  ('LNGCWETW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_transit_walk))','LNGCWETW'),
#  ('LNGCWEW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_walk))','LNGCWEW'),
#  ('LNE20MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_drive_alone))','LNE20MDA'),
#  ('LNE20MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_transit_walk))','LNE20MTW'),
#  ('LNE20MW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_walk))','LNE20MW'),
  ('LNE30MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_drive_alone))','LNE30MDA'),
  ('LNE30MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_transit_walk))','LNE30MTW'),
  ('gc_cbd = gridcell.disaggregate(psrc.zone.generalized_cost_hbw_am_drive_alone_to_129)', 'GC_CBD'),
#  ('psrc.gridcell.travel_time_hbw_am_drive_alone_to_cbd', 'TT_CBD'),
],

8:
[
 ('constant', 'constant'),

 ('urbansim.gridcell.building_age', 'BLD_AGE'),
# ('urbansim.gridcell.is_outside_urban_growth_boundary', 'OUT_UGB'),
 ('urbansim.gridcell.is_near_arterial', 'ART'),
 ('urbansim.gridcell.is_near_highway', 'HWY'),
# ('urbansim.gridcell.ln_distance_to_highway', 'LDHW'),
# ('urbansim.gridcell.percent_floodplain', 'PFLOOD'),
# ('urbansim.gridcell.percent_stream_buffer', 'PSTREAM'),

#  ('urbansim.gridcell.ln_total_improvement_value', 'LIMPV'),

#  ('urbansim.gridcell.ln_total_nonresidential_sqft_within_walking_distance', 'LNRSFW'),
# #('urbansim.gridcell.ln_commercial_sqft', 'LSFC'),
# ('urbansim.gridcell.ln_commercial_sqft_within_walking_distance', 'LSFCW'),
# #('urbansim.gridcell.ln_industrial_sqft', 'LSFI'),
# ('urbansim.gridcell.ln_industrial_sqft_within_walking_distance', 'LSFIW'),

# # ('urbansim.gridcell.ln_residential_units', 'LDU'),
  ('urbansim.gridcell.ln_residential_units_within_walking_distance', 'LDUW'),
# ('urbansim.gridcell.residential_density', 'RDEN'),
# ('urbansim.gridcell. population_density', 'POPDEN'),
# ('urbansim.gridcell.ln_total_population_within_walking_distance', 'LPOPW'),
#  ('urbansim.gridcell.ln_total_employment_within_walking_distance', 'LE_W'),
 ('urbansim.gridcell.ln_basic_sector_employment_within_walking_distance', 'LE_BW'),
 ('urbansim.gridcell.ln_retail_sector_employment_within_walking_distance', 'LE_REW'),
 ('urbansim.gridcell.ln_service_sector_employment_within_walking_distance', 'LE_SEW'),

 ('urbansim.gridcell.percent_commercial_within_walking_distance','PCW'),
 ('urbansim.gridcell.percent_industrial_within_walking_distance','PIW'), 
 ('urbansim.gridcell.percent_residential_within_walking_distance','PRW'),
  ('urbansim.gridcell.percent_developed_within_walking_distance', 'PDEVW'),
# ('urbansim.gridcell.percent_open_space_within_walking_distance','POSW'), 
  ('urbansim.gridcell.percent_water', 'PWATER'),
#  ('urbansim.gridcell.percent_wetland', 'PWETLA'),

# ('ln(urbansim.gridcell.average_income)','LAI'),
 ('ln(urbansim.gridcell.average_income_within_walking_distance)','LAIW'),
# ('urbansim.gridcell.percent_low_income_households_within_walking_distance', 'PLIW'),
# #('urbansim.gridcell.percent_mid_income_households_within_walking_distance', 'PMIW'),
# ('urbansim.gridcell.percent_high_income_households_within_walking_distance', 'PHIW'),
# ('urbansim.gridcell.is_average_income_within_walking_distance_high_income', 'AIHIW'),
# ('urbansim.gridcell.is_average_income_high_income', 'AIHI'), 
 
#  ('LNGCWEDA = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_drive_alone))','LNGCWEDA'),
#  ('LNGCWETW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_transit_walk))','LNGCWETW'),
#  ('LNGCWEW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_walk))','LNGCWEW'),
#  ('LNE20MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_drive_alone))','LNE20MDA'),
#  ('LNE20MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_transit_walk))','LNE20MTW'),
#  ('LNE20MW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_walk))','LNE20MW'),
  ('LNE30MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_drive_alone))','LNE30MDA'),
  ('LNE30MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_transit_walk))','LNE30MTW'),
  ('gc_cbd = gridcell.disaggregate(psrc.zone.generalized_cost_hbw_am_drive_alone_to_129)', 'GC_CBD'),
#  ('psrc.gridcell.travel_time_hbw_am_drive_alone_to_cbd', 'TT_CBD'),
],

9:
[
 ('constant', 'constant'),

 ('urbansim.gridcell.building_age', 'BLD_AGE'),
# ('urbansim.gridcell.is_outside_urban_growth_boundary', 'OUT_UGB'),
 ('urbansim.gridcell.is_near_arterial', 'ART'),
 ('urbansim.gridcell.is_near_highway', 'HWY'),
# ('urbansim.gridcell.ln_distance_to_highway', 'LDHW'),
# ('urbansim.gridcell.percent_floodplain', 'PFLOOD'),
# ('urbansim.gridcell.percent_stream_buffer', 'PSTREAM'),

#  ('urbansim.gridcell.ln_total_improvement_value', 'LIMPV'),

#  ('urbansim.gridcell.ln_total_nonresidential_sqft_within_walking_distance', 'LNRSFW'),
# #('urbansim.gridcell.ln_commercial_sqft', 'LSFC'),
# ('urbansim.gridcell.ln_commercial_sqft_within_walking_distance', 'LSFCW'),
# #('urbansim.gridcell.ln_industrial_sqft', 'LSFI'),
# ('urbansim.gridcell.ln_industrial_sqft_within_walking_distance', 'LSFIW'),

# # ('urbansim.gridcell.ln_residential_units', 'LDU'),
  ('urbansim.gridcell.ln_residential_units_within_walking_distance', 'LDUW'),
# ('urbansim.gridcell.residential_density', 'RDEN'),
# ('urbansim.gridcell. population_density', 'POPDEN'),
# ('urbansim.gridcell.ln_total_population_within_walking_distance', 'LPOPW'),
#  ('urbansim.gridcell.ln_total_employment_within_walking_distance', 'LE_W'),
 ('urbansim.gridcell.ln_basic_sector_employment_within_walking_distance', 'LE_BW'),
 ('urbansim.gridcell.ln_retail_sector_employment_within_walking_distance', 'LE_REW'),
 ('urbansim.gridcell.ln_service_sector_employment_within_walking_distance', 'LE_SEW'),

 ('urbansim.gridcell.percent_commercial_within_walking_distance','PCW'),
 ('urbansim.gridcell.percent_industrial_within_walking_distance','PIW'), 
 ('urbansim.gridcell.percent_residential_within_walking_distance','PRW'),
  ('urbansim.gridcell.percent_developed_within_walking_distance', 'PDEVW'),
# ('urbansim.gridcell.percent_open_space_within_walking_distance','POSW'), 
  ('urbansim.gridcell.percent_water', 'PWATER'),
#  ('urbansim.gridcell.percent_wetland', 'PWETLA'),

# ('ln(urbansim.gridcell.average_income)','LAI'),
 ('ln(urbansim.gridcell.average_income_within_walking_distance)','LAIW'),
# ('urbansim.gridcell.percent_low_income_households_within_walking_distance', 'PLIW'),
# #('urbansim.gridcell.percent_mid_income_households_within_walking_distance', 'PMIW'),
# ('urbansim.gridcell.percent_high_income_households_within_walking_distance', 'PHIW'),
# ('urbansim.gridcell.is_average_income_within_walking_distance_high_income', 'AIHIW'),
# ('urbansim.gridcell.is_average_income_high_income', 'AIHI'), 
 
#  ('LNGCWEDA = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_drive_alone))','LNGCWEDA'),
#  ('LNGCWETW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_transit_walk))','LNGCWETW'),
#  ('LNGCWEW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_walk))','LNGCWEW'),
#  ('LNE20MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_drive_alone))','LNE20MDA'),
#  ('LNE20MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_transit_walk))','LNE20MTW'),
#  ('LNE20MW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_walk))','LNE20MW'),
  ('LNE30MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_drive_alone))','LNE30MDA'),
  ('LNE30MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_transit_walk))','LNE30MTW'),
  ('gc_cbd = gridcell.disaggregate(psrc.zone.generalized_cost_hbw_am_drive_alone_to_129)', 'GC_CBD'),
#  ('psrc.gridcell.travel_time_hbw_am_drive_alone_to_cbd', 'TT_CBD'),
],

10:
[
 ('constant', 'constant'),

 ('urbansim.gridcell.building_age', 'BLD_AGE'),
# ('urbansim.gridcell.is_outside_urban_growth_boundary', 'OUT_UGB'),
 ('urbansim.gridcell.is_near_arterial', 'ART'),
 ('urbansim.gridcell.is_near_highway', 'HWY'),
# ('urbansim.gridcell.ln_distance_to_highway', 'LDHW'),
# ('urbansim.gridcell.percent_floodplain', 'PFLOOD'),
# ('urbansim.gridcell.percent_stream_buffer', 'PSTREAM'),

#  ('urbansim.gridcell.ln_total_improvement_value', 'LIMPV'),

#  ('urbansim.gridcell.ln_total_nonresidential_sqft_within_walking_distance', 'LNRSFW'),
# #('urbansim.gridcell.ln_commercial_sqft', 'LSFC'),
# ('urbansim.gridcell.ln_commercial_sqft_within_walking_distance', 'LSFCW'),
# #('urbansim.gridcell.ln_industrial_sqft', 'LSFI'),
# ('urbansim.gridcell.ln_industrial_sqft_within_walking_distance', 'LSFIW'),

# # ('urbansim.gridcell.ln_residential_units', 'LDU'),
  ('urbansim.gridcell.ln_residential_units_within_walking_distance', 'LDUW'),
# ('urbansim.gridcell.residential_density', 'RDEN'),
# ('urbansim.gridcell. population_density', 'POPDEN'),
# ('urbansim.gridcell.ln_total_population_within_walking_distance', 'LPOPW'),
#  ('urbansim.gridcell.ln_total_employment_within_walking_distance', 'LE_W'),
 ('urbansim.gridcell.ln_basic_sector_employment_within_walking_distance', 'LE_BW'),
 ('urbansim.gridcell.ln_retail_sector_employment_within_walking_distance', 'LE_REW'),
 ('urbansim.gridcell.ln_service_sector_employment_within_walking_distance', 'LE_SEW'),

 ('urbansim.gridcell.percent_commercial_within_walking_distance','PCW'),
 ('urbansim.gridcell.percent_industrial_within_walking_distance','PIW'), 
 ('urbansim.gridcell.percent_residential_within_walking_distance','PRW'),
  ('urbansim.gridcell.percent_developed_within_walking_distance', 'PDEVW'),
# ('urbansim.gridcell.percent_open_space_within_walking_distance','POSW'), 
  ('urbansim.gridcell.percent_water', 'PWATER'),
#  ('urbansim.gridcell.percent_wetland', 'PWETLA'),

# ('ln(urbansim.gridcell.average_income)','LAI'),
 ('ln(urbansim.gridcell.average_income_within_walking_distance)','LAIW'),
# ('urbansim.gridcell.percent_low_income_households_within_walking_distance', 'PLIW'),
# #('urbansim.gridcell.percent_mid_income_households_within_walking_distance', 'PMIW'),
# ('urbansim.gridcell.percent_high_income_households_within_walking_distance', 'PHIW'),
# ('urbansim.gridcell.is_average_income_within_walking_distance_high_income', 'AIHIW'),
# ('urbansim.gridcell.is_average_income_high_income', 'AIHI'), 
 
#  ('LNGCWEDA = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_drive_alone))','LNGCWEDA'),
#  ('LNGCWETW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_transit_walk))','LNGCWETW'),
#  ('LNGCWEW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_walk))','LNGCWEW'),
#  ('LNE20MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_drive_alone))','LNE20MDA'),
#  ('LNE20MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_transit_walk))','LNE20MTW'),
#  ('LNE20MW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_walk))','LNE20MW'),
  ('LNE30MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_drive_alone))','LNE30MDA'),
  ('LNE30MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_transit_walk))','LNE30MTW'),
  ('gc_cbd = gridcell.disaggregate(psrc.zone.generalized_cost_hbw_am_drive_alone_to_129)', 'GC_CBD'),
#  ('psrc.gridcell.travel_time_hbw_am_drive_alone_to_cbd', 'TT_CBD'),
],

11:
[
 ('constant', 'constant'),

 ('urbansim.gridcell.building_age', 'BLD_AGE'),
# ('urbansim.gridcell.is_outside_urban_growth_boundary', 'OUT_UGB'),
 ('urbansim.gridcell.is_near_arterial', 'ART'),
 ('urbansim.gridcell.is_near_highway', 'HWY'),
# ('urbansim.gridcell.ln_distance_to_highway', 'LDHW'),
# ('urbansim.gridcell.percent_floodplain', 'PFLOOD'),
# ('urbansim.gridcell.percent_stream_buffer', 'PSTREAM'),

#  ('urbansim.gridcell.ln_total_improvement_value', 'LIMPV'),

#  ('urbansim.gridcell.ln_total_nonresidential_sqft_within_walking_distance', 'LNRSFW'),
# #('urbansim.gridcell.ln_commercial_sqft', 'LSFC'),
# ('urbansim.gridcell.ln_commercial_sqft_within_walking_distance', 'LSFCW'),
# #('urbansim.gridcell.ln_industrial_sqft', 'LSFI'),
# ('urbansim.gridcell.ln_industrial_sqft_within_walking_distance', 'LSFIW'),

# # ('urbansim.gridcell.ln_residential_units', 'LDU'),
  ('urbansim.gridcell.ln_residential_units_within_walking_distance', 'LDUW'),
# ('urbansim.gridcell.residential_density', 'RDEN'),
# ('urbansim.gridcell. population_density', 'POPDEN'),
# ('urbansim.gridcell.ln_total_population_within_walking_distance', 'LPOPW'),
#  ('urbansim.gridcell.ln_total_employment_within_walking_distance', 'LE_W'),
 ('urbansim.gridcell.ln_basic_sector_employment_within_walking_distance', 'LE_BW'),
 ('urbansim.gridcell.ln_retail_sector_employment_within_walking_distance', 'LE_REW'),
 ('urbansim.gridcell.ln_service_sector_employment_within_walking_distance', 'LE_SEW'),

 ('urbansim.gridcell.percent_commercial_within_walking_distance','PCW'),
 ('urbansim.gridcell.percent_industrial_within_walking_distance','PIW'), 
 ('urbansim.gridcell.percent_residential_within_walking_distance','PRW'),
  ('urbansim.gridcell.percent_developed_within_walking_distance', 'PDEVW'),
# ('urbansim.gridcell.percent_open_space_within_walking_distance','POSW'), 
  ('urbansim.gridcell.percent_water', 'PWATER'),
#  ('urbansim.gridcell.percent_wetland', 'PWETLA'),

# ('ln(urbansim.gridcell.average_income)','LAI'),
 ('ln(urbansim.gridcell.average_income_within_walking_distance)','LAIW'),
# ('urbansim.gridcell.percent_low_income_households_within_walking_distance', 'PLIW'),
# #('urbansim.gridcell.percent_mid_income_households_within_walking_distance', 'PMIW'),
# ('urbansim.gridcell.percent_high_income_households_within_walking_distance', 'PHIW'),
# ('urbansim.gridcell.is_average_income_within_walking_distance_high_income', 'AIHIW'),
# ('urbansim.gridcell.is_average_income_high_income', 'AIHI'), 
 
#  ('LNGCWEDA = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_drive_alone))','LNGCWEDA'),
#  ('LNGCWETW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_transit_walk))','LNGCWETW'),
#  ('LNGCWEW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_walk))','LNGCWEW'),
#  ('LNE20MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_drive_alone))','LNE20MDA'),
#  ('LNE20MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_transit_walk))','LNE20MTW'),
#  ('LNE20MW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_walk))','LNE20MW'),
  ('LNE30MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_drive_alone))','LNE30MDA'),
  ('LNE30MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_transit_walk))','LNE30MTW'),
  ('gc_cbd = gridcell.disaggregate(psrc.zone.generalized_cost_hbw_am_drive_alone_to_129)', 'GC_CBD'),
#  ('psrc.gridcell.travel_time_hbw_am_drive_alone_to_cbd', 'TT_CBD'),
],

12:
[
 ('constant', 'constant'),

 ('urbansim.gridcell.building_age', 'BLD_AGE'),
# ('urbansim.gridcell.is_outside_urban_growth_boundary', 'OUT_UGB'),
 ('urbansim.gridcell.is_near_arterial', 'ART'),
 ('urbansim.gridcell.is_near_highway', 'HWY'),
# ('urbansim.gridcell.ln_distance_to_highway', 'LDHW'),
# ('urbansim.gridcell.percent_floodplain', 'PFLOOD'),
# ('urbansim.gridcell.percent_stream_buffer', 'PSTREAM'),

#  ('urbansim.gridcell.ln_total_improvement_value', 'LIMPV'),

#  ('urbansim.gridcell.ln_total_nonresidential_sqft_within_walking_distance', 'LNRSFW'),
# #('urbansim.gridcell.ln_commercial_sqft', 'LSFC'),
# ('urbansim.gridcell.ln_commercial_sqft_within_walking_distance', 'LSFCW'),
# #('urbansim.gridcell.ln_industrial_sqft', 'LSFI'),
# ('urbansim.gridcell.ln_industrial_sqft_within_walking_distance', 'LSFIW'),

# # ('urbansim.gridcell.ln_residential_units', 'LDU'),
  ('urbansim.gridcell.ln_residential_units_within_walking_distance', 'LDUW'),
# ('urbansim.gridcell.residential_density', 'RDEN'),
# ('urbansim.gridcell. population_density', 'POPDEN'),
# ('urbansim.gridcell.ln_total_population_within_walking_distance', 'LPOPW'),
#  ('urbansim.gridcell.ln_total_employment_within_walking_distance', 'LE_W'),
 ('urbansim.gridcell.ln_basic_sector_employment_within_walking_distance', 'LE_BW'),
 ('urbansim.gridcell.ln_retail_sector_employment_within_walking_distance', 'LE_REW'),
 ('urbansim.gridcell.ln_service_sector_employment_within_walking_distance', 'LE_SEW'),

 ('urbansim.gridcell.percent_commercial_within_walking_distance','PCW'),
 ('urbansim.gridcell.percent_industrial_within_walking_distance','PIW'), 
 ('urbansim.gridcell.percent_residential_within_walking_distance','PRW'),
  ('urbansim.gridcell.percent_developed_within_walking_distance', 'PDEVW'),
# ('urbansim.gridcell.percent_open_space_within_walking_distance','POSW'), 
  ('urbansim.gridcell.percent_water', 'PWATER'),
#  ('urbansim.gridcell.percent_wetland', 'PWETLA'),

# ('ln(urbansim.gridcell.average_income)','LAI'),
 ('ln(urbansim.gridcell.average_income_within_walking_distance)','LAIW'),
# ('urbansim.gridcell.percent_low_income_households_within_walking_distance', 'PLIW'),
# #('urbansim.gridcell.percent_mid_income_households_within_walking_distance', 'PMIW'),
# ('urbansim.gridcell.percent_high_income_households_within_walking_distance', 'PHIW'),
# ('urbansim.gridcell.is_average_income_within_walking_distance_high_income', 'AIHIW'),
# ('urbansim.gridcell.is_average_income_high_income', 'AIHI'), 
 
#  ('LNGCWEDA = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_drive_alone))','LNGCWEDA'),
#  ('LNGCWETW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_transit_walk))','LNGCWETW'),
#  ('LNGCWEW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_walk))','LNGCWEW'),
#  ('LNE20MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_drive_alone))','LNE20MDA'),
#  ('LNE20MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_transit_walk))','LNE20MTW'),
#  ('LNE20MW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_walk))','LNE20MW'),
  ('LNE30MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_drive_alone))','LNE30MDA'),
  ('LNE30MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_transit_walk))','LNE30MTW'),
  ('gc_cbd = gridcell.disaggregate(psrc.zone.generalized_cost_hbw_am_drive_alone_to_129)', 'GC_CBD'),
#  ('psrc.gridcell.travel_time_hbw_am_drive_alone_to_cbd', 'TT_CBD'),
],

13:
[
 ('constant', 'constant'),

 ('urbansim.gridcell.building_age', 'BLD_AGE'),
# ('urbansim.gridcell.is_outside_urban_growth_boundary', 'OUT_UGB'),
 ('urbansim.gridcell.is_near_arterial', 'ART'),
 ('urbansim.gridcell.is_near_highway', 'HWY'),
# ('urbansim.gridcell.ln_distance_to_highway', 'LDHW'),
# ('urbansim.gridcell.percent_floodplain', 'PFLOOD'),
# ('urbansim.gridcell.percent_stream_buffer', 'PSTREAM'),

#  ('urbansim.gridcell.ln_total_improvement_value', 'LIMPV'),

#  ('urbansim.gridcell.ln_total_nonresidential_sqft_within_walking_distance', 'LNRSFW'),
# #('urbansim.gridcell.ln_commercial_sqft', 'LSFC'),
# ('urbansim.gridcell.ln_commercial_sqft_within_walking_distance', 'LSFCW'),
# #('urbansim.gridcell.ln_industrial_sqft', 'LSFI'),
# ('urbansim.gridcell.ln_industrial_sqft_within_walking_distance', 'LSFIW'),

# # ('urbansim.gridcell.ln_residential_units', 'LDU'),
  ('urbansim.gridcell.ln_residential_units_within_walking_distance', 'LDUW'),
# ('urbansim.gridcell.residential_density', 'RDEN'),
# ('urbansim.gridcell. population_density', 'POPDEN'),
# ('urbansim.gridcell.ln_total_population_within_walking_distance', 'LPOPW'),
#  ('urbansim.gridcell.ln_total_employment_within_walking_distance', 'LE_W'),
 ('urbansim.gridcell.ln_basic_sector_employment_within_walking_distance', 'LE_BW'),
 ('urbansim.gridcell.ln_retail_sector_employment_within_walking_distance', 'LE_REW'),
 ('urbansim.gridcell.ln_service_sector_employment_within_walking_distance', 'LE_SEW'),

 ('urbansim.gridcell.percent_commercial_within_walking_distance','PCW'),
 ('urbansim.gridcell.percent_industrial_within_walking_distance','PIW'), 
 ('urbansim.gridcell.percent_residential_within_walking_distance','PRW'),
  ('urbansim.gridcell.percent_developed_within_walking_distance', 'PDEVW'),
# ('urbansim.gridcell.percent_open_space_within_walking_distance','POSW'), 
  ('urbansim.gridcell.percent_water', 'PWATER'),
#  ('urbansim.gridcell.percent_wetland', 'PWETLA'),

# ('ln(urbansim.gridcell.average_income)','LAI'),
 ('ln(urbansim.gridcell.average_income_within_walking_distance)','LAIW'),
# ('urbansim.gridcell.percent_low_income_households_within_walking_distance', 'PLIW'),
# #('urbansim.gridcell.percent_mid_income_households_within_walking_distance', 'PMIW'),
# ('urbansim.gridcell.percent_high_income_households_within_walking_distance', 'PHIW'),
# ('urbansim.gridcell.is_average_income_within_walking_distance_high_income', 'AIHIW'),
# ('urbansim.gridcell.is_average_income_high_income', 'AIHI'), 
 
#  ('LNGCWEDA = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_drive_alone))','LNGCWEDA'),
#  ('LNGCWETW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_transit_walk))','LNGCWETW'),
#  ('LNGCWEW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_walk))','LNGCWEW'),
#  ('LNE20MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_drive_alone))','LNE20MDA'),
#  ('LNE20MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_transit_walk))','LNE20MTW'),
#  ('LNE20MW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_walk))','LNE20MW'),
  ('LNE30MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_drive_alone))','LNE30MDA'),
  ('LNE30MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_transit_walk))','LNE30MTW'),
  ('gc_cbd = gridcell.disaggregate(psrc.zone.generalized_cost_hbw_am_drive_alone_to_129)', 'GC_CBD'),
#  ('psrc.gridcell.travel_time_hbw_am_drive_alone_to_cbd', 'TT_CBD'),
],

14:
[
 ('constant', 'constant'),

 ('urbansim.gridcell.building_age', 'BLD_AGE'),
# ('urbansim.gridcell.is_outside_urban_growth_boundary', 'OUT_UGB'),
 ('urbansim.gridcell.is_near_arterial', 'ART'),
 ('urbansim.gridcell.is_near_highway', 'HWY'),
# ('urbansim.gridcell.ln_distance_to_highway', 'LDHW'),
# ('urbansim.gridcell.percent_floodplain', 'PFLOOD'),
# ('urbansim.gridcell.percent_stream_buffer', 'PSTREAM'),

#  ('urbansim.gridcell.ln_total_improvement_value', 'LIMPV'),

#  ('urbansim.gridcell.ln_total_nonresidential_sqft_within_walking_distance', 'LNRSFW'),
# #('urbansim.gridcell.ln_commercial_sqft', 'LSFC'),
# ('urbansim.gridcell.ln_commercial_sqft_within_walking_distance', 'LSFCW'),
# #('urbansim.gridcell.ln_industrial_sqft', 'LSFI'),
# ('urbansim.gridcell.ln_industrial_sqft_within_walking_distance', 'LSFIW'),

# # ('urbansim.gridcell.ln_residential_units', 'LDU'),
  ('urbansim.gridcell.ln_residential_units_within_walking_distance', 'LDUW'),
# ('urbansim.gridcell.residential_density', 'RDEN'),
# ('urbansim.gridcell. population_density', 'POPDEN'),
# ('urbansim.gridcell.ln_total_population_within_walking_distance', 'LPOPW'),
#  ('urbansim.gridcell.ln_total_employment_within_walking_distance', 'LE_W'),
 ('urbansim.gridcell.ln_basic_sector_employment_within_walking_distance', 'LE_BW'),
 ('urbansim.gridcell.ln_retail_sector_employment_within_walking_distance', 'LE_REW'),
 ('urbansim.gridcell.ln_service_sector_employment_within_walking_distance', 'LE_SEW'),

 ('urbansim.gridcell.percent_commercial_within_walking_distance','PCW'),
 ('urbansim.gridcell.percent_industrial_within_walking_distance','PIW'), 
 ('urbansim.gridcell.percent_residential_within_walking_distance','PRW'),
  ('urbansim.gridcell.percent_developed_within_walking_distance', 'PDEVW'),
# ('urbansim.gridcell.percent_open_space_within_walking_distance','POSW'), 
  ('urbansim.gridcell.percent_water', 'PWATER'),
#  ('urbansim.gridcell.percent_wetland', 'PWETLA'),

# ('ln(urbansim.gridcell.average_income)','LAI'),
 ('ln(urbansim.gridcell.average_income_within_walking_distance)','LAIW'),
# ('urbansim.gridcell.percent_low_income_households_within_walking_distance', 'PLIW'),
# #('urbansim.gridcell.percent_mid_income_households_within_walking_distance', 'PMIW'),
# ('urbansim.gridcell.percent_high_income_households_within_walking_distance', 'PHIW'),
# ('urbansim.gridcell.is_average_income_within_walking_distance_high_income', 'AIHIW'),
# ('urbansim.gridcell.is_average_income_high_income', 'AIHI'), 
 
#  ('LNGCWEDA = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_drive_alone))','LNGCWEDA'),
#  ('LNGCWETW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_transit_walk))','LNGCWETW'),
#  ('LNGCWEW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_walk))','LNGCWEW'),
#  ('LNE20MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_drive_alone))','LNE20MDA'),
#  ('LNE20MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_transit_walk))','LNE20MTW'),
#  ('LNE20MW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_walk))','LNE20MW'),
  ('LNE30MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_drive_alone))','LNE30MDA'),
  ('LNE30MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_transit_walk))','LNE30MTW'),
  ('gc_cbd = gridcell.disaggregate(psrc.zone.generalized_cost_hbw_am_drive_alone_to_129)', 'GC_CBD'),
#  ('psrc.gridcell.travel_time_hbw_am_drive_alone_to_cbd', 'TT_CBD'),
],

15:
[
 ('constant', 'constant'),

 ('urbansim.gridcell.building_age', 'BLD_AGE'),
# ('urbansim.gridcell.is_outside_urban_growth_boundary', 'OUT_UGB'),
 ('urbansim.gridcell.is_near_arterial', 'ART'),
 ('urbansim.gridcell.is_near_highway', 'HWY'),
# ('urbansim.gridcell.ln_distance_to_highway', 'LDHW'),
# ('urbansim.gridcell.percent_floodplain', 'PFLOOD'),
# ('urbansim.gridcell.percent_stream_buffer', 'PSTREAM'),

#  ('urbansim.gridcell.ln_total_improvement_value', 'LIMPV'),

#  ('urbansim.gridcell.ln_total_nonresidential_sqft_within_walking_distance', 'LNRSFW'),
# #('urbansim.gridcell.ln_commercial_sqft', 'LSFC'),
# ('urbansim.gridcell.ln_commercial_sqft_within_walking_distance', 'LSFCW'),
# #('urbansim.gridcell.ln_industrial_sqft', 'LSFI'),
# ('urbansim.gridcell.ln_industrial_sqft_within_walking_distance', 'LSFIW'),

# # ('urbansim.gridcell.ln_residential_units', 'LDU'),
  ('urbansim.gridcell.ln_residential_units_within_walking_distance', 'LDUW'),
# ('urbansim.gridcell.residential_density', 'RDEN'),
# ('urbansim.gridcell. population_density', 'POPDEN'),
# ('urbansim.gridcell.ln_total_population_within_walking_distance', 'LPOPW'),
#  ('urbansim.gridcell.ln_total_employment_within_walking_distance', 'LE_W'),
 ('urbansim.gridcell.ln_basic_sector_employment_within_walking_distance', 'LE_BW'),
 ('urbansim.gridcell.ln_retail_sector_employment_within_walking_distance', 'LE_REW'),
 ('urbansim.gridcell.ln_service_sector_employment_within_walking_distance', 'LE_SEW'),

 ('urbansim.gridcell.percent_commercial_within_walking_distance','PCW'),
 ('urbansim.gridcell.percent_industrial_within_walking_distance','PIW'), 
 ('urbansim.gridcell.percent_residential_within_walking_distance','PRW'),
  ('urbansim.gridcell.percent_developed_within_walking_distance', 'PDEVW'),
# ('urbansim.gridcell.percent_open_space_within_walking_distance','POSW'), 
  ('urbansim.gridcell.percent_water', 'PWATER'),
#  ('urbansim.gridcell.percent_wetland', 'PWETLA'),

# ('ln(urbansim.gridcell.average_income)','LAI'),
 ('ln(urbansim.gridcell.average_income_within_walking_distance)','LAIW'),
# ('urbansim.gridcell.percent_low_income_households_within_walking_distance', 'PLIW'),
# #('urbansim.gridcell.percent_mid_income_households_within_walking_distance', 'PMIW'),
# ('urbansim.gridcell.percent_high_income_households_within_walking_distance', 'PHIW'),
# ('urbansim.gridcell.is_average_income_within_walking_distance_high_income', 'AIHIW'),
# ('urbansim.gridcell.is_average_income_high_income', 'AIHI'), 
 
#  ('LNGCWEDA = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_drive_alone))','LNGCWEDA'),
#  ('LNGCWETW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_transit_walk))','LNGCWETW'),
#  ('LNGCWEW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_walk))','LNGCWEW'),
#  ('LNE20MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_drive_alone))','LNE20MDA'),
#  ('LNE20MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_transit_walk))','LNE20MTW'),
#  ('LNE20MW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_walk))','LNE20MW'),
  ('LNE30MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_drive_alone))','LNE30MDA'),
  ('LNE30MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_transit_walk))','LNE30MTW'),
  ('gc_cbd = gridcell.disaggregate(psrc.zone.generalized_cost_hbw_am_drive_alone_to_129)', 'GC_CBD'),
#  ('psrc.gridcell.travel_time_hbw_am_drive_alone_to_cbd', 'TT_CBD'),
],

16:
[
 ('constant', 'constant'),

 ('urbansim.gridcell.building_age', 'BLD_AGE'),
# ('urbansim.gridcell.is_outside_urban_growth_boundary', 'OUT_UGB'),
 ('urbansim.gridcell.is_near_arterial', 'ART'),
 ('urbansim.gridcell.is_near_highway', 'HWY'),
# ('urbansim.gridcell.ln_distance_to_highway', 'LDHW'),
# ('urbansim.gridcell.percent_floodplain', 'PFLOOD'),
# ('urbansim.gridcell.percent_stream_buffer', 'PSTREAM'),

#  ('urbansim.gridcell.ln_total_improvement_value', 'LIMPV'),

#  ('urbansim.gridcell.ln_total_nonresidential_sqft_within_walking_distance', 'LNRSFW'),
# #('urbansim.gridcell.ln_commercial_sqft', 'LSFC'),
# ('urbansim.gridcell.ln_commercial_sqft_within_walking_distance', 'LSFCW'),
# #('urbansim.gridcell.ln_industrial_sqft', 'LSFI'),
# ('urbansim.gridcell.ln_industrial_sqft_within_walking_distance', 'LSFIW'),

# # ('urbansim.gridcell.ln_residential_units', 'LDU'),
  ('urbansim.gridcell.ln_residential_units_within_walking_distance', 'LDUW'),
# ('urbansim.gridcell.residential_density', 'RDEN'),
# ('urbansim.gridcell. population_density', 'POPDEN'),
# ('urbansim.gridcell.ln_total_population_within_walking_distance', 'LPOPW'),
#  ('urbansim.gridcell.ln_total_employment_within_walking_distance', 'LE_W'),
 ('urbansim.gridcell.ln_basic_sector_employment_within_walking_distance', 'LE_BW'),
 ('urbansim.gridcell.ln_retail_sector_employment_within_walking_distance', 'LE_REW'),
 ('urbansim.gridcell.ln_service_sector_employment_within_walking_distance', 'LE_SEW'),

 ('urbansim.gridcell.percent_commercial_within_walking_distance','PCW'),
 ('urbansim.gridcell.percent_industrial_within_walking_distance','PIW'), 
 ('urbansim.gridcell.percent_residential_within_walking_distance','PRW'),
  ('urbansim.gridcell.percent_developed_within_walking_distance', 'PDEVW'),
# ('urbansim.gridcell.percent_open_space_within_walking_distance','POSW'), 
  ('urbansim.gridcell.percent_water', 'PWATER'),
#  ('urbansim.gridcell.percent_wetland', 'PWETLA'),

# ('ln(urbansim.gridcell.average_income)','LAI'),
 ('ln(urbansim.gridcell.average_income_within_walking_distance)','LAIW'),
# ('urbansim.gridcell.percent_low_income_households_within_walking_distance', 'PLIW'),
# #('urbansim.gridcell.percent_mid_income_households_within_walking_distance', 'PMIW'),
# ('urbansim.gridcell.percent_high_income_households_within_walking_distance', 'PHIW'),
# ('urbansim.gridcell.is_average_income_within_walking_distance_high_income', 'AIHIW'),
# ('urbansim.gridcell.is_average_income_high_income', 'AIHI'), 
 
#  ('LNGCWEDA = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_drive_alone))','LNGCWEDA'),
#  ('LNGCWETW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_transit_walk))','LNGCWETW'),
#  ('LNGCWEW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_walk))','LNGCWEW'),
#  ('LNE20MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_drive_alone))','LNE20MDA'),
#  ('LNE20MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_transit_walk))','LNE20MTW'),
#  ('LNE20MW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_walk))','LNE20MW'),
  ('LNE30MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_drive_alone))','LNE30MDA'),
  ('LNE30MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_transit_walk))','LNE30MTW'),
  ('gc_cbd = gridcell.disaggregate(psrc.zone.generalized_cost_hbw_am_drive_alone_to_129)', 'GC_CBD'),
#  ('psrc.gridcell.travel_time_hbw_am_drive_alone_to_cbd', 'TT_CBD'),
],

17:
[
 ('constant', 'constant'),

 ('urbansim.gridcell.building_age', 'BLD_AGE'),
# ('urbansim.gridcell.is_outside_urban_growth_boundary', 'OUT_UGB'),
 ('urbansim.gridcell.is_near_arterial', 'ART'),
 ('urbansim.gridcell.is_near_highway', 'HWY'),
# ('urbansim.gridcell.ln_distance_to_highway', 'LDHW'),
# ('urbansim.gridcell.percent_floodplain', 'PFLOOD'),
# ('urbansim.gridcell.percent_stream_buffer', 'PSTREAM'),

#  ('urbansim.gridcell.ln_total_improvement_value', 'LIMPV'),

#  ('urbansim.gridcell.ln_total_nonresidential_sqft_within_walking_distance', 'LNRSFW'),
# #('urbansim.gridcell.ln_commercial_sqft', 'LSFC'),
# ('urbansim.gridcell.ln_commercial_sqft_within_walking_distance', 'LSFCW'),
# #('urbansim.gridcell.ln_industrial_sqft', 'LSFI'),
# ('urbansim.gridcell.ln_industrial_sqft_within_walking_distance', 'LSFIW'),

# # ('urbansim.gridcell.ln_residential_units', 'LDU'),
  ('urbansim.gridcell.ln_residential_units_within_walking_distance', 'LDUW'),
# ('urbansim.gridcell.residential_density', 'RDEN'),
# ('urbansim.gridcell. population_density', 'POPDEN'),
# ('urbansim.gridcell.ln_total_population_within_walking_distance', 'LPOPW'),
#  ('urbansim.gridcell.ln_total_employment_within_walking_distance', 'LE_W'),
 ('urbansim.gridcell.ln_basic_sector_employment_within_walking_distance', 'LE_BW'),
 ('urbansim.gridcell.ln_retail_sector_employment_within_walking_distance', 'LE_REW'),
 ('urbansim.gridcell.ln_service_sector_employment_within_walking_distance', 'LE_SEW'),

 ('urbansim.gridcell.percent_commercial_within_walking_distance','PCW'),
 ('urbansim.gridcell.percent_industrial_within_walking_distance','PIW'), 
 ('urbansim.gridcell.percent_residential_within_walking_distance','PRW'),
  ('urbansim.gridcell.percent_developed_within_walking_distance', 'PDEVW'),
# ('urbansim.gridcell.percent_open_space_within_walking_distance','POSW'), 
  ('urbansim.gridcell.percent_water', 'PWATER'),
#  ('urbansim.gridcell.percent_wetland', 'PWETLA'),

# ('ln(urbansim.gridcell.average_income)','LAI'),
 ('ln(urbansim.gridcell.average_income_within_walking_distance)','LAIW'),
# ('urbansim.gridcell.percent_low_income_households_within_walking_distance', 'PLIW'),
# #('urbansim.gridcell.percent_mid_income_households_within_walking_distance', 'PMIW'),
# ('urbansim.gridcell.percent_high_income_households_within_walking_distance', 'PHIW'),
# ('urbansim.gridcell.is_average_income_within_walking_distance_high_income', 'AIHIW'),
# ('urbansim.gridcell.is_average_income_high_income', 'AIHI'), 
 
#  ('LNGCWEDA = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_drive_alone))','LNGCWEDA'),
#  ('LNGCWETW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_transit_walk))','LNGCWETW'),
#  ('LNGCWEW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_walk))','LNGCWEW'),
#  ('LNE20MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_drive_alone))','LNE20MDA'),
#  ('LNE20MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_transit_walk))','LNE20MTW'),
#  ('LNE20MW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_walk))','LNE20MW'),
  ('LNE30MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_drive_alone))','LNE30MDA'),
  ('LNE30MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_transit_walk))','LNE30MTW'),
  ('gc_cbd = gridcell.disaggregate(psrc.zone.generalized_cost_hbw_am_drive_alone_to_129)', 'GC_CBD'),
#  ('psrc.gridcell.travel_time_hbw_am_drive_alone_to_cbd', 'TT_CBD'),
],

18:
[
 ('constant', 'constant'),

 ('urbansim.gridcell.building_age', 'BLD_AGE'),
# ('urbansim.gridcell.is_outside_urban_growth_boundary', 'OUT_UGB'),
 ('urbansim.gridcell.is_near_arterial', 'ART'),
 ('urbansim.gridcell.is_near_highway', 'HWY'),
# ('urbansim.gridcell.ln_distance_to_highway', 'LDHW'),
# ('urbansim.gridcell.percent_floodplain', 'PFLOOD'),
# ('urbansim.gridcell.percent_stream_buffer', 'PSTREAM'),

#  ('urbansim.gridcell.ln_total_improvement_value', 'LIMPV'),

#  ('urbansim.gridcell.ln_total_nonresidential_sqft_within_walking_distance', 'LNRSFW'),
# #('urbansim.gridcell.ln_commercial_sqft', 'LSFC'),
# ('urbansim.gridcell.ln_commercial_sqft_within_walking_distance', 'LSFCW'),
# #('urbansim.gridcell.ln_industrial_sqft', 'LSFI'),
# ('urbansim.gridcell.ln_industrial_sqft_within_walking_distance', 'LSFIW'),

# # ('urbansim.gridcell.ln_residential_units', 'LDU'),
  ('urbansim.gridcell.ln_residential_units_within_walking_distance', 'LDUW'),
# ('urbansim.gridcell.residential_density', 'RDEN'),
# ('urbansim.gridcell. population_density', 'POPDEN'),
# ('urbansim.gridcell.ln_total_population_within_walking_distance', 'LPOPW'),
#  ('urbansim.gridcell.ln_total_employment_within_walking_distance', 'LE_W'),
 ('urbansim.gridcell.ln_basic_sector_employment_within_walking_distance', 'LE_BW'),
 ('urbansim.gridcell.ln_retail_sector_employment_within_walking_distance', 'LE_REW'),
 ('urbansim.gridcell.ln_service_sector_employment_within_walking_distance', 'LE_SEW'),

 ('urbansim.gridcell.percent_commercial_within_walking_distance','PCW'),
 ('urbansim.gridcell.percent_industrial_within_walking_distance','PIW'), 
 ('urbansim.gridcell.percent_residential_within_walking_distance','PRW'),
  ('urbansim.gridcell.percent_developed_within_walking_distance', 'PDEVW'),
# ('urbansim.gridcell.percent_open_space_within_walking_distance','POSW'), 
  ('urbansim.gridcell.percent_water', 'PWATER'),
#  ('urbansim.gridcell.percent_wetland', 'PWETLA'),

# ('ln(urbansim.gridcell.average_income)','LAI'),
 ('ln(urbansim.gridcell.average_income_within_walking_distance)','LAIW'),
# ('urbansim.gridcell.percent_low_income_households_within_walking_distance', 'PLIW'),
# #('urbansim.gridcell.percent_mid_income_households_within_walking_distance', 'PMIW'),
# ('urbansim.gridcell.percent_high_income_households_within_walking_distance', 'PHIW'),
# ('urbansim.gridcell.is_average_income_within_walking_distance_high_income', 'AIHIW'),
# ('urbansim.gridcell.is_average_income_high_income', 'AIHI'), 
 
#  ('LNGCWEDA = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_drive_alone))','LNGCWEDA'),
#  ('LNGCWETW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_transit_walk))','LNGCWETW'),
#  ('LNGCWEW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_walk))','LNGCWEW'),
#  ('LNE20MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_drive_alone))','LNE20MDA'),
#  ('LNE20MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_transit_walk))','LNE20MTW'),
#  ('LNE20MW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_walk))','LNE20MW'),
  ('LNE30MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_drive_alone))','LNE30MDA'),
  ('LNE30MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_transit_walk))','LNE30MTW'),
  ('gc_cbd = gridcell.disaggregate(psrc.zone.generalized_cost_hbw_am_drive_alone_to_129)', 'GC_CBD'),
#  ('psrc.gridcell.travel_time_hbw_am_drive_alone_to_cbd', 'TT_CBD'),
],

19:
[
 ('constant', 'constant'),

 ('urbansim.gridcell.building_age', 'BLD_AGE'),
# ('urbansim.gridcell.is_outside_urban_growth_boundary', 'OUT_UGB'),
 ('urbansim.gridcell.is_near_arterial', 'ART'),
 ('urbansim.gridcell.is_near_highway', 'HWY'),
# ('urbansim.gridcell.ln_distance_to_highway', 'LDHW'),
# ('urbansim.gridcell.percent_floodplain', 'PFLOOD'),
# ('urbansim.gridcell.percent_stream_buffer', 'PSTREAM'),

#  ('urbansim.gridcell.ln_total_improvement_value', 'LIMPV'),

#  ('urbansim.gridcell.ln_total_nonresidential_sqft_within_walking_distance', 'LNRSFW'),
# #('urbansim.gridcell.ln_commercial_sqft', 'LSFC'),
# ('urbansim.gridcell.ln_commercial_sqft_within_walking_distance', 'LSFCW'),
# #('urbansim.gridcell.ln_industrial_sqft', 'LSFI'),
# ('urbansim.gridcell.ln_industrial_sqft_within_walking_distance', 'LSFIW'),

# # ('urbansim.gridcell.ln_residential_units', 'LDU'),
  ('urbansim.gridcell.ln_residential_units_within_walking_distance', 'LDUW'),
# ('urbansim.gridcell.residential_density', 'RDEN'),
# ('urbansim.gridcell. population_density', 'POPDEN'),
# ('urbansim.gridcell.ln_total_population_within_walking_distance', 'LPOPW'),
#  ('urbansim.gridcell.ln_total_employment_within_walking_distance', 'LE_W'),
 ('urbansim.gridcell.ln_basic_sector_employment_within_walking_distance', 'LE_BW'),
 ('urbansim.gridcell.ln_retail_sector_employment_within_walking_distance', 'LE_REW'),
 ('urbansim.gridcell.ln_service_sector_employment_within_walking_distance', 'LE_SEW'),

 ('urbansim.gridcell.percent_commercial_within_walking_distance','PCW'),
 ('urbansim.gridcell.percent_industrial_within_walking_distance','PIW'), 
 ('urbansim.gridcell.percent_residential_within_walking_distance','PRW'),
  ('urbansim.gridcell.percent_developed_within_walking_distance', 'PDEVW'),
# ('urbansim.gridcell.percent_open_space_within_walking_distance','POSW'), 
  ('urbansim.gridcell.percent_water', 'PWATER'),
#  ('urbansim.gridcell.percent_wetland', 'PWETLA'),

# ('ln(urbansim.gridcell.average_income)','LAI'),
 ('ln(urbansim.gridcell.average_income_within_walking_distance)','LAIW'),
# ('urbansim.gridcell.percent_low_income_households_within_walking_distance', 'PLIW'),
# #('urbansim.gridcell.percent_mid_income_households_within_walking_distance', 'PMIW'),
# ('urbansim.gridcell.percent_high_income_households_within_walking_distance', 'PHIW'),
# ('urbansim.gridcell.is_average_income_within_walking_distance_high_income', 'AIHIW'),
# ('urbansim.gridcell.is_average_income_high_income', 'AIHI'), 
 
#  ('LNGCWEDA = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_drive_alone))','LNGCWEDA'),
#  ('LNGCWETW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_transit_walk))','LNGCWETW'),
#  ('LNGCWEW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_walk))','LNGCWEW'),
#  ('LNE20MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_drive_alone))','LNE20MDA'),
#  ('LNE20MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_transit_walk))','LNE20MTW'),
#  ('LNE20MW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_walk))','LNE20MW'),
  ('LNE30MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_drive_alone))','LNE30MDA'),
  ('LNE30MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_transit_walk))','LNE30MTW'),
  ('gc_cbd = gridcell.disaggregate(psrc.zone.generalized_cost_hbw_am_drive_alone_to_129)', 'GC_CBD'),
#  ('psrc.gridcell.travel_time_hbw_am_drive_alone_to_cbd', 'TT_CBD'),
],

20:
[
 ('constant', 'constant'),

 ('urbansim.gridcell.building_age', 'BLD_AGE'),
# ('urbansim.gridcell.is_outside_urban_growth_boundary', 'OUT_UGB'),
 ('urbansim.gridcell.is_near_arterial', 'ART'),
 ('urbansim.gridcell.is_near_highway', 'HWY'),
# ('urbansim.gridcell.ln_distance_to_highway', 'LDHW'),
# ('urbansim.gridcell.percent_floodplain', 'PFLOOD'),
# ('urbansim.gridcell.percent_stream_buffer', 'PSTREAM'),

#  ('urbansim.gridcell.ln_total_improvement_value', 'LIMPV'),

#  ('urbansim.gridcell.ln_total_nonresidential_sqft_within_walking_distance', 'LNRSFW'),
# #('urbansim.gridcell.ln_commercial_sqft', 'LSFC'),
# ('urbansim.gridcell.ln_commercial_sqft_within_walking_distance', 'LSFCW'),
# #('urbansim.gridcell.ln_industrial_sqft', 'LSFI'),
# ('urbansim.gridcell.ln_industrial_sqft_within_walking_distance', 'LSFIW'),

# # ('urbansim.gridcell.ln_residential_units', 'LDU'),
  ('urbansim.gridcell.ln_residential_units_within_walking_distance', 'LDUW'),
# ('urbansim.gridcell.residential_density', 'RDEN'),
# ('urbansim.gridcell. population_density', 'POPDEN'),
# ('urbansim.gridcell.ln_total_population_within_walking_distance', 'LPOPW'),
#  ('urbansim.gridcell.ln_total_employment_within_walking_distance', 'LE_W'),
 ('urbansim.gridcell.ln_basic_sector_employment_within_walking_distance', 'LE_BW'),
 ('urbansim.gridcell.ln_retail_sector_employment_within_walking_distance', 'LE_REW'),
 ('urbansim.gridcell.ln_service_sector_employment_within_walking_distance', 'LE_SEW'),

 ('urbansim.gridcell.percent_commercial_within_walking_distance','PCW'),
 ('urbansim.gridcell.percent_industrial_within_walking_distance','PIW'), 
 ('urbansim.gridcell.percent_residential_within_walking_distance','PRW'),
  ('urbansim.gridcell.percent_developed_within_walking_distance', 'PDEVW'),
# ('urbansim.gridcell.percent_open_space_within_walking_distance','POSW'), 
  ('urbansim.gridcell.percent_water', 'PWATER'),
#  ('urbansim.gridcell.percent_wetland', 'PWETLA'),

# ('ln(urbansim.gridcell.average_income)','LAI'),
 ('ln(urbansim.gridcell.average_income_within_walking_distance)','LAIW'),
# ('urbansim.gridcell.percent_low_income_households_within_walking_distance', 'PLIW'),
# #('urbansim.gridcell.percent_mid_income_households_within_walking_distance', 'PMIW'),
# ('urbansim.gridcell.percent_high_income_households_within_walking_distance', 'PHIW'),
# ('urbansim.gridcell.is_average_income_within_walking_distance_high_income', 'AIHIW'),
# ('urbansim.gridcell.is_average_income_high_income', 'AIHI'), 
 
#  ('LNGCWEDA = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_drive_alone))','LNGCWEDA'),
#  ('LNGCWETW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_transit_walk))','LNGCWETW'),
#  ('LNGCWEW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_walk))','LNGCWEW'),
#  ('LNE20MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_drive_alone))','LNE20MDA'),
#  ('LNE20MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_transit_walk))','LNE20MTW'),
#  ('LNE20MW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_walk))','LNE20MW'),
  ('LNE30MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_drive_alone))','LNE30MDA'),
  ('LNE30MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_transit_walk))','LNE30MTW'),
  ('gc_cbd = gridcell.disaggregate(psrc.zone.generalized_cost_hbw_am_drive_alone_to_129)', 'GC_CBD'),
#  ('psrc.gridcell.travel_time_hbw_am_drive_alone_to_cbd', 'TT_CBD'),
],

21:
[
 ('constant', 'constant'),

 ('urbansim.gridcell.building_age', 'BLD_AGE'),
# ('urbansim.gridcell.is_outside_urban_growth_boundary', 'OUT_UGB'),
 ('urbansim.gridcell.is_near_arterial', 'ART'),
 ('urbansim.gridcell.is_near_highway', 'HWY'),
# ('urbansim.gridcell.ln_distance_to_highway', 'LDHW'),
# ('urbansim.gridcell.percent_floodplain', 'PFLOOD'),
# ('urbansim.gridcell.percent_stream_buffer', 'PSTREAM'),

#  ('urbansim.gridcell.ln_total_improvement_value', 'LIMPV'),

#  ('urbansim.gridcell.ln_total_nonresidential_sqft_within_walking_distance', 'LNRSFW'),
# #('urbansim.gridcell.ln_commercial_sqft', 'LSFC'),
# ('urbansim.gridcell.ln_commercial_sqft_within_walking_distance', 'LSFCW'),
# #('urbansim.gridcell.ln_industrial_sqft', 'LSFI'),
# ('urbansim.gridcell.ln_industrial_sqft_within_walking_distance', 'LSFIW'),

# # ('urbansim.gridcell.ln_residential_units', 'LDU'),
  ('urbansim.gridcell.ln_residential_units_within_walking_distance', 'LDUW'),
# ('urbansim.gridcell.residential_density', 'RDEN'),
# ('urbansim.gridcell. population_density', 'POPDEN'),
# ('urbansim.gridcell.ln_total_population_within_walking_distance', 'LPOPW'),
#  ('urbansim.gridcell.ln_total_employment_within_walking_distance', 'LE_W'),
 ('urbansim.gridcell.ln_basic_sector_employment_within_walking_distance', 'LE_BW'),
 ('urbansim.gridcell.ln_retail_sector_employment_within_walking_distance', 'LE_REW'),
 ('urbansim.gridcell.ln_service_sector_employment_within_walking_distance', 'LE_SEW'),

 ('urbansim.gridcell.percent_commercial_within_walking_distance','PCW'),
 ('urbansim.gridcell.percent_industrial_within_walking_distance','PIW'), 
 ('urbansim.gridcell.percent_residential_within_walking_distance','PRW'),
  ('urbansim.gridcell.percent_developed_within_walking_distance', 'PDEVW'),
# ('urbansim.gridcell.percent_open_space_within_walking_distance','POSW'), 
  ('urbansim.gridcell.percent_water', 'PWATER'),
#  ('urbansim.gridcell.percent_wetland', 'PWETLA'),

# ('ln(urbansim.gridcell.average_income)','LAI'),
 ('ln(urbansim.gridcell.average_income_within_walking_distance)','LAIW'),
# ('urbansim.gridcell.percent_low_income_households_within_walking_distance', 'PLIW'),
# #('urbansim.gridcell.percent_mid_income_households_within_walking_distance', 'PMIW'),
# ('urbansim.gridcell.percent_high_income_households_within_walking_distance', 'PHIW'),
# ('urbansim.gridcell.is_average_income_within_walking_distance_high_income', 'AIHIW'),
# ('urbansim.gridcell.is_average_income_high_income', 'AIHI'), 
 
#  ('LNGCWEDA = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_drive_alone))','LNGCWEDA'),
#  ('LNGCWETW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_transit_walk))','LNGCWETW'),
#  ('LNGCWEW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_walk))','LNGCWEW'),
#  ('LNE20MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_drive_alone))','LNE20MDA'),
#  ('LNE20MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_transit_walk))','LNE20MTW'),
#  ('LNE20MW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_walk))','LNE20MW'),
  ('LNE30MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_drive_alone))','LNE30MDA'),
  ('LNE30MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_transit_walk))','LNE30MTW'),
  ('gc_cbd = gridcell.disaggregate(psrc.zone.generalized_cost_hbw_am_drive_alone_to_129)', 'GC_CBD'),
#  ('psrc.gridcell.travel_time_hbw_am_drive_alone_to_cbd', 'TT_CBD'),
],

22:
[
 ('constant', 'constant'),

 ('urbansim.gridcell.building_age', 'BLD_AGE'),
# ('urbansim.gridcell.is_outside_urban_growth_boundary', 'OUT_UGB'),
 ('urbansim.gridcell.is_near_arterial', 'ART'),
 ('urbansim.gridcell.is_near_highway', 'HWY'),
# ('urbansim.gridcell.ln_distance_to_highway', 'LDHW'),
# ('urbansim.gridcell.percent_floodplain', 'PFLOOD'),
# ('urbansim.gridcell.percent_stream_buffer', 'PSTREAM'),

#  ('urbansim.gridcell.ln_total_improvement_value', 'LIMPV'),

#  ('urbansim.gridcell.ln_total_nonresidential_sqft_within_walking_distance', 'LNRSFW'),
# #('urbansim.gridcell.ln_commercial_sqft', 'LSFC'),
# ('urbansim.gridcell.ln_commercial_sqft_within_walking_distance', 'LSFCW'),
# #('urbansim.gridcell.ln_industrial_sqft', 'LSFI'),
# ('urbansim.gridcell.ln_industrial_sqft_within_walking_distance', 'LSFIW'),

# # ('urbansim.gridcell.ln_residential_units', 'LDU'),
  ('urbansim.gridcell.ln_residential_units_within_walking_distance', 'LDUW'),
# ('urbansim.gridcell.residential_density', 'RDEN'),
# ('urbansim.gridcell. population_density', 'POPDEN'),
# ('urbansim.gridcell.ln_total_population_within_walking_distance', 'LPOPW'),
#  ('urbansim.gridcell.ln_total_employment_within_walking_distance', 'LE_W'),
 ('urbansim.gridcell.ln_basic_sector_employment_within_walking_distance', 'LE_BW'),
 ('urbansim.gridcell.ln_retail_sector_employment_within_walking_distance', 'LE_REW'),
 ('urbansim.gridcell.ln_service_sector_employment_within_walking_distance', 'LE_SEW'),

 ('urbansim.gridcell.percent_commercial_within_walking_distance','PCW'),
 ('urbansim.gridcell.percent_industrial_within_walking_distance','PIW'), 
 ('urbansim.gridcell.percent_residential_within_walking_distance','PRW'),
  ('urbansim.gridcell.percent_developed_within_walking_distance', 'PDEVW'),
# ('urbansim.gridcell.percent_open_space_within_walking_distance','POSW'), 
  ('urbansim.gridcell.percent_water', 'PWATER'),
#  ('urbansim.gridcell.percent_wetland', 'PWETLA'),

# ('ln(urbansim.gridcell.average_income)','LAI'),
 ('ln(urbansim.gridcell.average_income_within_walking_distance)','LAIW'),
# ('urbansim.gridcell.percent_low_income_households_within_walking_distance', 'PLIW'),
# #('urbansim.gridcell.percent_mid_income_households_within_walking_distance', 'PMIW'),
# ('urbansim.gridcell.percent_high_income_households_within_walking_distance', 'PHIW'),
# ('urbansim.gridcell.is_average_income_within_walking_distance_high_income', 'AIHIW'),
# ('urbansim.gridcell.is_average_income_high_income', 'AIHI'), 
 
#  ('LNGCWEDA = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_drive_alone))','LNGCWEDA'),
#  ('LNGCWETW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_transit_walk))','LNGCWETW'),
#  ('LNGCWEW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_walk))','LNGCWEW'),
#  ('LNE20MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_drive_alone))','LNE20MDA'),
#  ('LNE20MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_transit_walk))','LNE20MTW'),
#  ('LNE20MW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_walk))','LNE20MW'),
  ('LNE30MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_drive_alone))','LNE30MDA'),
  ('LNE30MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_transit_walk))','LNE30MTW'),
  ('gc_cbd = gridcell.disaggregate(psrc.zone.generalized_cost_hbw_am_drive_alone_to_129)', 'GC_CBD'),
#  ('psrc.gridcell.travel_time_hbw_am_drive_alone_to_cbd', 'TT_CBD'),
],

23:
[
 ('constant', 'constant'),

 ('urbansim.gridcell.building_age', 'BLD_AGE'),
# ('urbansim.gridcell.is_outside_urban_growth_boundary', 'OUT_UGB'),
 ('urbansim.gridcell.is_near_arterial', 'ART'),
 ('urbansim.gridcell.is_near_highway', 'HWY'),
# ('urbansim.gridcell.ln_distance_to_highway', 'LDHW'),
# ('urbansim.gridcell.percent_floodplain', 'PFLOOD'),
# ('urbansim.gridcell.percent_stream_buffer', 'PSTREAM'),

#  ('urbansim.gridcell.ln_total_improvement_value', 'LIMPV'),

#  ('urbansim.gridcell.ln_total_nonresidential_sqft_within_walking_distance', 'LNRSFW'),
# #('urbansim.gridcell.ln_commercial_sqft', 'LSFC'),
# ('urbansim.gridcell.ln_commercial_sqft_within_walking_distance', 'LSFCW'),
# #('urbansim.gridcell.ln_industrial_sqft', 'LSFI'),
# ('urbansim.gridcell.ln_industrial_sqft_within_walking_distance', 'LSFIW'),

# # ('urbansim.gridcell.ln_residential_units', 'LDU'),
  ('urbansim.gridcell.ln_residential_units_within_walking_distance', 'LDUW'),
# ('urbansim.gridcell.residential_density', 'RDEN'),
# ('urbansim.gridcell. population_density', 'POPDEN'),
# ('urbansim.gridcell.ln_total_population_within_walking_distance', 'LPOPW'),
#  ('urbansim.gridcell.ln_total_employment_within_walking_distance', 'LE_W'),
 ('urbansim.gridcell.ln_basic_sector_employment_within_walking_distance', 'LE_BW'),
 ('urbansim.gridcell.ln_retail_sector_employment_within_walking_distance', 'LE_REW'),
 ('urbansim.gridcell.ln_service_sector_employment_within_walking_distance', 'LE_SEW'),

 ('urbansim.gridcell.percent_commercial_within_walking_distance','PCW'),
 ('urbansim.gridcell.percent_industrial_within_walking_distance','PIW'), 
 ('urbansim.gridcell.percent_residential_within_walking_distance','PRW'),
  ('urbansim.gridcell.percent_developed_within_walking_distance', 'PDEVW'),
# ('urbansim.gridcell.percent_open_space_within_walking_distance','POSW'), 
  ('urbansim.gridcell.percent_water', 'PWATER'),
#  ('urbansim.gridcell.percent_wetland', 'PWETLA'),

# ('ln(urbansim.gridcell.average_income)','LAI'),
 ('ln(urbansim.gridcell.average_income_within_walking_distance)','LAIW'),
# ('urbansim.gridcell.percent_low_income_households_within_walking_distance', 'PLIW'),
# #('urbansim.gridcell.percent_mid_income_households_within_walking_distance', 'PMIW'),
# ('urbansim.gridcell.percent_high_income_households_within_walking_distance', 'PHIW'),
# ('urbansim.gridcell.is_average_income_within_walking_distance_high_income', 'AIHIW'),
# ('urbansim.gridcell.is_average_income_high_income', 'AIHI'), 
 
#  ('LNGCWEDA = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_drive_alone))','LNGCWEDA'),
#  ('LNGCWETW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_transit_walk))','LNGCWETW'),
#  ('LNGCWEW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_walk))','LNGCWEW'),
#  ('LNE20MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_drive_alone))','LNE20MDA'),
#  ('LNE20MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_transit_walk))','LNE20MTW'),
#  ('LNE20MW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_walk))','LNE20MW'),
  ('LNE30MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_drive_alone))','LNE30MDA'),
  ('LNE30MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_transit_walk))','LNE30MTW'),
  ('gc_cbd = gridcell.disaggregate(psrc.zone.generalized_cost_hbw_am_drive_alone_to_129)', 'GC_CBD'),
#  ('psrc.gridcell.travel_time_hbw_am_drive_alone_to_cbd', 'TT_CBD'),
],

24:
[
 ('constant', 'constant'),

 ('urbansim.gridcell.building_age', 'BLD_AGE'),
# ('urbansim.gridcell.is_outside_urban_growth_boundary', 'OUT_UGB'),
 ('urbansim.gridcell.is_near_arterial', 'ART'),
 ('urbansim.gridcell.is_near_highway', 'HWY'),
# ('urbansim.gridcell.ln_distance_to_highway', 'LDHW'),
# ('urbansim.gridcell.percent_floodplain', 'PFLOOD'),
# ('urbansim.gridcell.percent_stream_buffer', 'PSTREAM'),

#  ('urbansim.gridcell.ln_total_improvement_value', 'LIMPV'),

#  ('urbansim.gridcell.ln_total_nonresidential_sqft_within_walking_distance', 'LNRSFW'),
# #('urbansim.gridcell.ln_commercial_sqft', 'LSFC'),
# ('urbansim.gridcell.ln_commercial_sqft_within_walking_distance', 'LSFCW'),
# #('urbansim.gridcell.ln_industrial_sqft', 'LSFI'),
# ('urbansim.gridcell.ln_industrial_sqft_within_walking_distance', 'LSFIW'),

# # ('urbansim.gridcell.ln_residential_units', 'LDU'),
  ('urbansim.gridcell.ln_residential_units_within_walking_distance', 'LDUW'),
# ('urbansim.gridcell.residential_density', 'RDEN'),
# ('urbansim.gridcell. population_density', 'POPDEN'),
# ('urbansim.gridcell.ln_total_population_within_walking_distance', 'LPOPW'),
#  ('urbansim.gridcell.ln_total_employment_within_walking_distance', 'LE_W'),
 ('urbansim.gridcell.ln_basic_sector_employment_within_walking_distance', 'LE_BW'),
 ('urbansim.gridcell.ln_retail_sector_employment_within_walking_distance', 'LE_REW'),
 ('urbansim.gridcell.ln_service_sector_employment_within_walking_distance', 'LE_SEW'),

 ('urbansim.gridcell.percent_commercial_within_walking_distance','PCW'),
 ('urbansim.gridcell.percent_industrial_within_walking_distance','PIW'), 
 ('urbansim.gridcell.percent_residential_within_walking_distance','PRW'),
  ('urbansim.gridcell.percent_developed_within_walking_distance', 'PDEVW'),
# ('urbansim.gridcell.percent_open_space_within_walking_distance','POSW'), 
  ('urbansim.gridcell.percent_water', 'PWATER'),
#  ('urbansim.gridcell.percent_wetland', 'PWETLA'),

# ('ln(urbansim.gridcell.average_income)','LAI'),
 ('ln(urbansim.gridcell.average_income_within_walking_distance)','LAIW'),
# ('urbansim.gridcell.percent_low_income_households_within_walking_distance', 'PLIW'),
# #('urbansim.gridcell.percent_mid_income_households_within_walking_distance', 'PMIW'),
# ('urbansim.gridcell.percent_high_income_households_within_walking_distance', 'PHIW'),
# ('urbansim.gridcell.is_average_income_within_walking_distance_high_income', 'AIHIW'),
# ('urbansim.gridcell.is_average_income_high_income', 'AIHI'), 
 
#  ('LNGCWEDA = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_drive_alone))','LNGCWEDA'),
#  ('LNGCWETW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_transit_walk))','LNGCWETW'),
#  ('LNGCWEW = ln(gridcell.disaggregate(psrc.zone.generalized_cost_weighted_access_to_employment_hbw_am_walk))','LNGCWEW'),
#  ('LNE20MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_drive_alone))','LNE20MDA'),
#  ('LNE20MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_transit_walk))','LNE20MTW'),
#  ('LNE20MW = ln(gridcell.disaggregate(psrc.zone.employment_within_20_minutes_travel_time_hbw_am_walk))','LNE20MW'),
  ('LNE30MDA = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_drive_alone))','LNE30MDA'),
  ('LNE30MTW = ln(gridcell.disaggregate(psrc.zone.employment_within_30_minutes_travel_time_hbw_am_transit_walk))','LNE30MTW'),
  ('gc_cbd = gridcell.disaggregate(psrc.zone.generalized_cost_hbw_am_drive_alone_to_129)', 'GC_CBD'),
#  ('psrc.gridcell.travel_time_hbw_am_drive_alone_to_cbd', 'TT_CBD'),
],
}