# Opus/UrbanSim urban simulation software.
# Copyright (C) 2010-2011 University of California, Berkeley, 2005-2009 University of Washington
# See opus_core/LICENSE 

# this is a test of the expression alias file
# one of the aliases uses a primary attribute in the expression, the other a variable

aliases = [
   "is_residential_land_use_type = parcel.disaggregate(generic_land_use_type.unit_name == 'residential_units', [land_use_type])",
   "plan_1=parcel.plan_type_id==1",
    "plan_2=parcel.plan_type_id==2",
    "plan_3=parcel.plan_type_id==3",
    "plan_4=parcel.plan_type_id==4",
    "plan_5=parcel.plan_type_id==5",
    "plan_6=parcel.plan_type_id==6",
    "plan_7=parcel.plan_type_id==7",
    "plan_8=parcel.plan_type_id==8",
    "plan_9=parcel.plan_type_id==9",
    "plan_10=parcel.plan_type_id==10",
    "plan_11=parcel.plan_type_id==11",
    "plan_12=parcel.plan_type_id==12",
    "plan_13=parcel.plan_type_id==13",
    "plan_14=parcel.plan_type_id==14",
    "plan_15=parcel.plan_type_id==15",
    "plan_16=parcel.plan_type_id==16",
    "plan_17=parcel.plan_type_id==17",
    "plan_18=parcel.plan_type_id==18",
    "plan_19=parcel.plan_type_id==19",
    "plan_20=parcel.plan_type_id==20",
    # Carefull: the following two variables depend on the contents of the table plan_types
    "is_residential_plan_type = (%s + %s + %s + %s + %s + %s + %s + %s + %s + %s + %s + %s + %s + %s) > 0" % (
              "urbansim_parcel.parcel.plan_1",
              "urbansim_parcel.parcel.plan_3",
              "urbansim_parcel.parcel.plan_4",
              "urbansim_parcel.parcel.plan_6",
              "urbansim_parcel.parcel.plan_7",
              "urbansim_parcel.parcel.plan_8",
              "urbansim_parcel.parcel.plan_9",
              "urbansim_parcel.parcel.plan_11",
              "urbansim_parcel.parcel.plan_12",
              "urbansim_parcel.parcel.plan_13",
              "urbansim_parcel.parcel.plan_16",
              "urbansim_parcel.parcel.plan_17",
              "urbansim_parcel.parcel.plan_19",
              "urbansim_parcel.parcel.plan_20"),
    "is_non_residential_plan_type = (%s + %s + %s + %s + %s + %s + %s + %s + %s) > 0" % (
              "urbansim_parcel.parcel.plan_5",
              "urbansim_parcel.parcel.plan_6",
              "urbansim_parcel.parcel.plan_10",
              "urbansim_parcel.parcel.plan_12",
              "urbansim_parcel.parcel.plan_14",
              "urbansim_parcel.parcel.plan_15",
              "urbansim_parcel.parcel.plan_16",
              "urbansim_parcel.parcel.plan_18",
              "urbansim_parcel.parcel.plan_20"),
       "used_land_area = (parcel.aggregate(building.land_area, function=sum)).astype(int32)",
       "vacant_land_area = parcel.parcel_sqft - urbansim_parcel.parcel.used_land_area",
       "unit_name = parcel.disaggregate(land_use_type.unit_name)",
       "building_sqft = (parcel.aggregate(urbansim_parcel.building.building_sqft)).astype(int32)",
       "building_sqft_per_unit = safe_array_divide(urbansim_parcel.parcel.building_sqft, urbansim_parcel.parcel.residential_units)",
       "residential_units = (parcel.aggregate(building.residential_units)).astype(int32)",       
       "parcel_sqft_per_unit = safe_array_divide( parcel.parcel_sqft, (urbansim_parcel.parcel.residential_units).astype(float32) )",
       "unit_price = safe_array_divide(parcel.land_value + urbansim_parcel.parcel.improvement_value, urbansim_parcel.parcel.existing_units)",
       "price_per_residential_unit = safe_array_divide(parcel.land_value + urbansim_parcel.parcel.improvement_value, urbansim_parcel.parcel.residential_units)",
       "demolition_cost = (parcel.aggregate(urbansim_parcel.building.demolition_cost)).astype(int32)",
       "improvement_value =parcel.aggregate(building.improvement_value)",
       "total_value_per_sqft = safe_array_divide(parcel.land_value + urbansim_parcel.parcel.improvement_value, parcel.parcel_sqft)",
       "number_of_jobs = parcel.aggregate(urbansim_parcel.building.number_of_jobs)",
       "employment = parcel.aggregate(urbansim_parcel.building.number_of_jobs)",
       "employment_retail = parcel.aggregate(urbansim.job.is_in_employment_sector_group_retail, intermediates=[building])",
       "number_of_households = parcel.aggregate(urbansim_parcel.building.number_of_households)",
       "population = parcel.aggregate(urbansim_parcel.building.population)",
       "travel_time_to_cbd = parcel.disaggregate(urbansim.gridcell.travel_time_to_cbd)",
       "large_area_id = parcel.disaggregate(faz.large_area_id, intermediates=[zone])",
           ]
