# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'error_form.ui'
#
# Created: Tue Jan  6 22:39:49 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_dlgErrorForm(object):
    def setupUi(self, dlgErrorForm):
        dlgErrorForm.setObjectName("dlgErrorForm")
        dlgErrorForm.setWindowModality(QtCore.Qt.NonModal)
        dlgErrorForm.resize(500, 200)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dlgErrorForm.sizePolicy().hasHeightForWidth())
        dlgErrorForm.setSizePolicy(sizePolicy)
        dlgErrorForm.setBaseSize(QtCore.QSize(500, 200))
        dlgErrorForm.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/error.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlgErrorForm.setWindowIcon(icon)
        dlgErrorForm.setSizeGripEnabled(True)
        dlgErrorForm.setModal(True)
        self.gridLayout = QtGui.QGridLayout(dlgErrorForm)
        self.gridLayout.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.layoutErrorMessage = QtGui.QHBoxLayout()
        self.layoutErrorMessage.setObjectName("layoutErrorMessage")
        self.frame = QtGui.QFrame(dlgErrorForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblImage = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblImage.sizePolicy().hasHeightForWidth())
        self.lblImage.setSizePolicy(sizePolicy)
        self.lblImage.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblImage.setPixmap(QtGui.QPixmap("Images/big_error.png"))
        self.lblImage.setAlignment(QtCore.Qt.AlignCenter)
        self.lblImage.setObjectName("lblImage")
        self.horizontalLayout_2.addWidget(self.lblImage)
        self.layoutErrorMessage.addWidget(self.frame)
        self.lblText = QtGui.QLabel(dlgErrorForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblText.sizePolicy().hasHeightForWidth())
        self.lblText.setSizePolicy(sizePolicy)
        self.lblText.setBaseSize(QtCore.QSize(400, 0))
        self.lblText.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblText.setWordWrap(True)
        self.lblText.setObjectName("lblText")
        self.layoutErrorMessage.addWidget(self.lblText)
        self.gridLayout.addLayout(self.layoutErrorMessage, 0, 0, 1, 2)
        self.layoutShowDetails = QtGui.QHBoxLayout()
        self.layoutShowDetails.setObjectName("layoutShowDetails")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.layoutShowDetails.addItem(spacerItem)
        self.pbnShowDetails = QtGui.QPushButton(dlgErrorForm)
        self.pbnShowDetails.setAutoDefault(False)
        self.pbnShowDetails.setObjectName("pbnShowDetails")
        self.layoutShowDetails.addWidget(self.pbnShowDetails)
        self.gridLayout.addLayout(self.layoutShowDetails, 1, 0, 1, 1)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.btnOk = QtGui.QPushButton(dlgErrorForm)
        self.btnOk.setDefault(True)
        self.btnOk.setObjectName("btnOk")
        self.hboxlayout.addWidget(self.btnOk)
        self.gridLayout.addLayout(self.hboxlayout, 1, 1, 1, 1)
        self.saDetails = QtGui.QScrollArea(dlgErrorForm)
        self.saDetails.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saDetails.sizePolicy().hasHeightForWidth())
        self.saDetails.setSizePolicy(sizePolicy)
        self.saDetails.setWidgetResizable(True)
        self.saDetails.setObjectName("saDetails")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.saDetails)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 457, 104))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblDetailText = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDetailText.sizePolicy().hasHeightForWidth())
        self.lblDetailText.setSizePolicy(sizePolicy)
        self.lblDetailText.setReadOnly(True)
        self.lblDetailText.setObjectName("lblDetailText")
        self.horizontalLayout.addWidget(self.lblDetailText)
        self.saDetails.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.saDetails, 2, 0, 1, 2)

        self.retranslateUi(dlgErrorForm)
        QtCore.QMetaObject.connectSlotsByName(dlgErrorForm)

    def retranslateUi(self, dlgErrorForm):
        dlgErrorForm.setWindowTitle(QtGui.QApplication.translate("dlgErrorForm", " ", None, QtGui.QApplication.UnicodeUTF8))
        dlgErrorForm.setWindowFilePath(QtGui.QApplication.translate("dlgErrorForm", " ", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnShowDetails.setText(QtGui.QApplication.translate("dlgErrorForm", "Show Details...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOk.setText(QtGui.QApplication.translate("dlgErrorForm", "Ok", None, QtGui.QApplication.UnicodeUTF8))

