# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/ckla/Documents/workspace/opus_trunk/opus_gui/main/views/message_box.ui'
#
# Created: Sun May 10 00:57:44 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MessageBox(object):
    def setupUi(self, MessageBox):
        MessageBox.setObjectName("MessageBox")
        MessageBox.setWindowModality(QtCore.Qt.NonModal)
        MessageBox.resize(500, 324)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MessageBox.sizePolicy().hasHeightForWidth())
        MessageBox.setSizePolicy(sizePolicy)
        MessageBox.setBaseSize(QtCore.QSize(500, 200))
        MessageBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        MessageBox.setSizeGripEnabled(True)
        MessageBox.setModal(True)
        self.verticalLayout = QtGui.QVBoxLayout(MessageBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layoutErrorMessage = QtGui.QHBoxLayout()
        self.layoutErrorMessage.setObjectName("layoutErrorMessage")
        self.frame = QtGui.QFrame(MessageBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblImage = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblImage.sizePolicy().hasHeightForWidth())
        self.lblImage.setSizePolicy(sizePolicy)
        self.lblImage.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblImage.setPixmap(QtGui.QPixmap("Images/big_error.png"))
        self.lblImage.setAlignment(QtCore.Qt.AlignCenter)
        self.lblImage.setObjectName("lblImage")
        self.horizontalLayout_2.addWidget(self.lblImage)
        self.layoutErrorMessage.addWidget(self.frame)
        self.lblText = QtGui.QLabel(MessageBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblText.sizePolicy().hasHeightForWidth())
        self.lblText.setSizePolicy(sizePolicy)
        self.lblText.setMinimumSize(QtCore.QSize(400, 0))
        self.lblText.setBaseSize(QtCore.QSize(400, 0))
        self.lblText.setFrameShape(QtGui.QFrame.NoFrame)
        self.lblText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblText.setWordWrap(True)
        self.lblText.setObjectName("lblText")
        self.layoutErrorMessage.addWidget(self.lblText)
        self.verticalLayout.addLayout(self.layoutErrorMessage)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.pbnShowDetails = QtGui.QPushButton(MessageBox)
        self.pbnShowDetails.setAutoDefault(False)
        self.pbnShowDetails.setObjectName("pbnShowDetails")
        self.hboxlayout.addWidget(self.pbnShowDetails)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.btnOk = QtGui.QPushButton(MessageBox)
        self.btnOk.setDefault(True)
        self.btnOk.setObjectName("btnOk")
        self.hboxlayout.addWidget(self.btnOk)
        self.verticalLayout.addLayout(self.hboxlayout)
        self.frame_details = QtGui.QFrame(MessageBox)
        self.frame_details.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_details.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_details.setObjectName("frame_details")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_details)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line = QtGui.QFrame(self.frame_details)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.lblDetailText = QtGui.QTextEdit(self.frame_details)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDetailText.sizePolicy().hasHeightForWidth())
        self.lblDetailText.setSizePolicy(sizePolicy)
        self.lblDetailText.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.lblDetailText.setReadOnly(True)
        self.lblDetailText.setObjectName("lblDetailText")
        self.verticalLayout_2.addWidget(self.lblDetailText)
        self.verticalLayout.addWidget(self.frame_details)

        self.retranslateUi(MessageBox)
        QtCore.QMetaObject.connectSlotsByName(MessageBox)

    def retranslateUi(self, MessageBox):
        MessageBox.setWindowTitle(QtGui.QApplication.translate("MessageBox", "Opus Message", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnShowDetails.setText(QtGui.QApplication.translate("MessageBox", "Show Details...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOk.setText(QtGui.QApplication.translate("MessageBox", "Ok", None, QtGui.QApplication.UnicodeUTF8))

