# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/ckla/Documents/workspace/opus_trunk/opus_gui/main/views/message_box.ui'
#
# Created: Sun May 10 00:57:44 2009
#      by: PyQt5 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_MessageBox(object):
    def setupUi(self, MessageBox):
        MessageBox.setObjectName("MessageBox")
        MessageBox.setWindowModality(QtCore.Qt.NonModal)
        MessageBox.resize(500, 324)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MessageBox.sizePolicy().hasHeightForWidth())
        MessageBox.setSizePolicy(sizePolicy)
        MessageBox.setBaseSize(QtCore.QSize(500, 200))
        MessageBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        MessageBox.setSizeGripEnabled(True)
        MessageBox.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(MessageBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layoutErrorMessage = QtWidgets.QHBoxLayout()
        self.layoutErrorMessage.setObjectName("layoutErrorMessage")
        self.frame = QtWidgets.QFrame(MessageBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblImage = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblImage.sizePolicy().hasHeightForWidth())
        self.lblImage.setSizePolicy(sizePolicy)
        self.lblImage.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblImage.setPixmap(QtWidgets.QPixmap("Images/big_error.png"))
        self.lblImage.setAlignment(QtCore.Qt.AlignCenter)
        self.lblImage.setObjectName("lblImage")
        self.horizontalLayout_2.addWidget(self.lblImage)
        self.layoutErrorMessage.addWidget(self.frame)
        self.lblText = QtWidgets.QLabel(MessageBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblText.sizePolicy().hasHeightForWidth())
        self.lblText.setSizePolicy(sizePolicy)
        self.lblText.setMinimumSize(QtCore.QSize(400, 0))
        self.lblText.setBaseSize(QtCore.QSize(400, 0))
        self.lblText.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblText.setWordWrap(True)
        self.lblText.setObjectName("lblText")
        self.layoutErrorMessage.addWidget(self.lblText)
        self.verticalLayout.addLayout(self.layoutErrorMessage)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.pbnShowDetails = QtWidgets.QPushButton(MessageBox)
        self.pbnShowDetails.setAutoDefault(False)
        self.pbnShowDetails.setObjectName("pbnShowDetails")
        self.hboxlayout.addWidget(self.pbnShowDetails)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.btnOk = QtWidgets.QPushButton(MessageBox)
        self.btnOk.setDefault(True)
        self.btnOk.setObjectName("btnOk")
        self.hboxlayout.addWidget(self.btnOk)
        self.verticalLayout.addLayout(self.hboxlayout)
        self.frame_details = QtWidgets.QFrame(MessageBox)
        self.frame_details.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_details.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_details.setObjectName("frame_details")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_details)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line = QtWidgets.QFrame(self.frame_details)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.lblDetailText = QtWidgets.QTextEdit(self.frame_details)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDetailText.sizePolicy().hasHeightForWidth())
        self.lblDetailText.setSizePolicy(sizePolicy)
        self.lblDetailText.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.lblDetailText.setReadOnly(True)
        self.lblDetailText.setObjectName("lblDetailText")
        self.verticalLayout_2.addWidget(self.lblDetailText)
        self.verticalLayout.addWidget(self.frame_details)

        self.retranslateUi(MessageBox)
        QtCore.QMetaObject.connectSlotsByName(MessageBox)

    def retranslateUi(self, MessageBox):
        MessageBox.setWindowTitle(QtWidgets.QApplication.translate("MessageBox", "Opus Message", None, QtWidgets.QApplication.UnicodeUTF8))
        self.pbnShowDetails.setText(QtWidgets.QApplication.translate("MessageBox", "Show Details...", None, QtWidgets.QApplication.UnicodeUTF8))
        self.btnOk.setText(QtWidgets.QApplication.translate("MessageBox", "OK", None, QtWidgets.QApplication.UnicodeUTF8))

