# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sat Feb 27 18:12:26 2010
#      by: PyQt5 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1093, 515)
        font = QtWidgets.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtWidgets.QIcon()
        icon.addPixmap(QtWidgets.QPixmap(":/Images/Images/new-logo-medium-no-mirror.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.toolBox = QtWidgets.QTabWidget(self.splitter)
        self.toolBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBox.setBaseSize(QtCore.QSize(200, 0))
        font = QtWidgets.QFont()
        font.setPointSize(12)
        self.toolBox.setFont(font)
        self.toolBox.setObjectName("toolBox")
        self.generalmanager_page = QtWidgets.QWidget()
        self.generalmanager_page.setObjectName("generalmanager_page")
        self.gridlayout = QtWidgets.QGridLayout(self.generalmanager_page)
        self.gridlayout.setObjectName("gridlayout")
        self.toolBox.addTab(self.generalmanager_page, "")
        self.datamanager_page = QtWidgets.QWidget()
        self.datamanager_page.setObjectName("datamanager_page")
        self.gridlayout1 = QtWidgets.QGridLayout(self.datamanager_page)
        self.gridlayout1.setObjectName("gridlayout1")
        self.dataManager_toolBox = QtWidgets.QTabWidget(self.datamanager_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataManager_toolBox.sizePolicy().hasHeightForWidth())
        self.dataManager_toolBox.setSizePolicy(sizePolicy)
        font = QtWidgets.QFont()
        font.setPointSize(11)
        self.dataManager_toolBox.setFont(font)
        self.dataManager_toolBox.setObjectName("dataManager_toolBox")
        self.datamanager_xmlconfig = QtWidgets.QWidget()
        self.datamanager_xmlconfig.setObjectName("datamanager_xmlconfig")
        self.gridlayout2 = QtWidgets.QGridLayout(self.datamanager_xmlconfig)
        self.gridlayout2.setObjectName("gridlayout2")
        self.dataManager_toolBox.addTab(self.datamanager_xmlconfig, "")
        self.datamanager_dirview = QtWidgets.QWidget()
        self.datamanager_dirview.setObjectName("datamanager_dirview")
        self.gridlayout3 = QtWidgets.QGridLayout(self.datamanager_dirview)
        self.gridlayout3.setObjectName("gridlayout3")
        self.dataManager_toolBox.addTab(self.datamanager_dirview, "")
        self.gridlayout1.addWidget(self.dataManager_toolBox, 0, 0, 1, 1)
        self.toolBox.addTab(self.datamanager_page, "")
        self.modelmanager_page = QtWidgets.QWidget()
        self.modelmanager_page.setObjectName("modelmanager_page")
        self.gridlayout4 = QtWidgets.QGridLayout(self.modelmanager_page)
        self.gridlayout4.setObjectName("gridlayout4")
        self.toolBox.addTab(self.modelmanager_page, "")
        self.runmanager_page = QtWidgets.QWidget()
        self.runmanager_page.setObjectName("runmanager_page")
        self.gridlayout5 = QtWidgets.QGridLayout(self.runmanager_page)
        self.gridlayout5.setObjectName("gridlayout5")
        self.toolBox.addTab(self.runmanager_page, "")
        self.resultsmanager_page = QtWidgets.QWidget()
        self.resultsmanager_page.setObjectName("resultsmanager_page")
        self.gridlayout6 = QtWidgets.QGridLayout(self.resultsmanager_page)
        self.gridlayout6.setObjectName("gridlayout6")
        self.toolBox.addTab(self.resultsmanager_page, "")
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1093, 27))
        self.menubar.setObjectName("menubar")
        self.menuProject = QtWidgets.QMenu(self.menubar)
        self.menuProject.setObjectName("menuProject")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuUtilities = QtWidgets.QMenu(self.menubar)
        self.menuUtilities.setObjectName("menuUtilities")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(20, 20))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.mpActionZoomOut = QtWidgets.QAction(MainWindow)
        icon1 = QtWidgets.QIcon()
        icon1.addPixmap(QtWidgets.QPixmap(":/Images/Images/mActionZoomOut.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        self.mpActionZoomOut.setIcon(icon1)
        self.mpActionZoomOut.setObjectName("mpActionZoomOut")
        self.mpActionPan = QtWidgets.QAction(MainWindow)
        icon2 = QtWidgets.QIcon()
        icon2.addPixmap(QtWidgets.QPixmap(":/Images/Images/mActionPan.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        self.mpActionPan.setIcon(icon2)
        self.mpActionPan.setObjectName("mpActionPan")
        self.mpActionAddRasterLayer = QtWidgets.QAction(MainWindow)
        icon3 = QtWidgets.QIcon()
        icon3.addPixmap(QtWidgets.QPixmap(":/Images/Images/mActionAddRasterLayer.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        self.mpActionAddRasterLayer.setIcon(icon3)
        self.mpActionAddRasterLayer.setObjectName("mpActionAddRasterLayer")
        self.mpActionZoomIn = QtWidgets.QAction(MainWindow)
        icon4 = QtWidgets.QIcon()
        icon4.addPixmap(QtWidgets.QPixmap(":/Images/Images/mActionZoomIn.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        self.mpActionZoomIn.setIcon(icon4)
        self.mpActionZoomIn.setObjectName("mpActionZoomIn")
        self.mpActionAddVectorLayer = QtWidgets.QAction(MainWindow)
        icon5 = QtWidgets.QIcon()
        icon5.addPixmap(QtWidgets.QPixmap(":/Images/Images/mActionAddLayer.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        self.mpActionAddVectorLayer.setIcon(icon5)
        self.mpActionAddVectorLayer.setObjectName("mpActionAddVectorLayer")
        self.actOpenProject = QtWidgets.QAction(MainWindow)
        icon8 = QtWidgets.QIcon()
        icon8.addPixmap(QtWidgets.QPixmap(":/Images/Images/open.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        self.actOpenProject.setIcon(icon8)
        self.actOpenProject.setIconVisibleInMenu(True)
        self.actOpenProject.setObjectName("actOpenProject")
        self.actExit = QtWidgets.QAction(MainWindow)
        icon9 = QtWidgets.QIcon()
        icon9.addPixmap(QtWidgets.QPixmap(":/Images/Images/exit.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        self.actExit.setIcon(icon9)
        self.actExit.setObjectName("actExit")
        self.actSaveProject = QtWidgets.QAction(MainWindow)
        self.actSaveProject.setEnabled(False)
        icon10 = QtWidgets.QIcon()
        icon10.addPixmap(QtWidgets.QPixmap(":/Images/Images/save.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        self.actSaveProject.setIcon(icon10)
        self.actSaveProject.setObjectName("actSaveProject")
        self.actSaveProjectAs = QtWidgets.QAction(MainWindow)
        self.actSaveProjectAs.setEnabled(False)
        icon11 = QtWidgets.QIcon()
        icon11.addPixmap(QtWidgets.QPixmap(":/Images/Images/save_as.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        self.actSaveProjectAs.setIcon(icon11)
        self.actSaveProjectAs.setObjectName("actSaveProjectAs")
        self.actShowHidden = QtWidgets.QAction(MainWindow)
        self.actShowHidden.setEnabled(True)
        self.actShowHidden.setObjectName("actShowHidden")
        self.actShowHidden.setCheckable(True)
        self.actReloadProject = QtWidgets.QAction(MainWindow)
        self.actReloadProject.setEnabled(False)
        self.actReloadProject.setObjectName("actReloadProject")
        self.actionRun_Manager = QtWidgets.QAction(MainWindow)
        icon12 = QtWidgets.QIcon()
        icon12.addPixmap(QtWidgets.QPixmap(":/Images/Images/cog.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        self.actionRun_Manager.setIcon(icon12)
        self.actionRun_Manager.setObjectName("actionRun_Manager")
        self.actAbout = QtWidgets.QAction(MainWindow)
        icon13 = QtWidgets.QIcon()
        icon13.addPixmap(QtWidgets.QPixmap(":/Images/Images/help.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        self.actAbout.setIcon(icon13)
        self.actAbout.setObjectName("actAbout")
        self.tabActionEditor = QtWidgets.QAction(MainWindow)
        icon14 = QtWidgets.QIcon()
        icon14.addPixmap(QtWidgets.QPixmap(":/Images/Images/table.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        self.tabActionEditor.setIcon(icon14)
        self.tabActionEditor.setObjectName("tabActionEditor")
        self.tabActionMapView = QtWidgets.QAction(MainWindow)
        icon15 = QtWidgets.QIcon()
        icon15.addPixmap(QtWidgets.QPixmap(":/Images/Images/map.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        self.tabActionMapView.setIcon(icon15)
        self.tabActionMapView.setObjectName("tabActionMapView")
        self.tabActionPythonConsole = QtWidgets.QAction(MainWindow)
        icon16 = QtWidgets.QIcon()
        icon16.addPixmap(QtWidgets.QPixmap(":/Images/Images/python_type.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        self.tabActionPythonConsole.setIcon(icon16)
        self.tabActionPythonConsole.setObjectName("tabActionPythonConsole")
        self.tabActionLogView = QtWidgets.QAction(MainWindow)
        icon6 = QtWidgets.QIcon()
        icon6.addPixmap(QtWidgets.QPixmap(":/Images/Images/folder.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        self.tabActionLogView.setIcon(icon6)
        self.tabActionLogView.setObjectName("tabActionLogView")
        self.actPythonView = QtWidgets.QAction(MainWindow)
        self.actPythonView.setEnabled(False)
        self.actPythonView.setIcon(icon16)
        self.actPythonView.setVisible(False)
        self.actPythonView.setIconVisibleInMenu(True)
        self.actPythonView.setObjectName("actPythonView")
        self.actLogView = QtWidgets.QAction(MainWindow)
        self.actLogView.setIcon(icon14)
        self.actLogView.setObjectName("actLogView")
        self.actEditorView = QtWidgets.QAction(MainWindow)
        icon17 = QtWidgets.QIcon()
        icon17.addPixmap(QtWidgets.QPixmap(":/Images/Images/table_lightning.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        self.actEditorView.setIcon(icon17)
        self.actEditorView.setVisible(False)
        self.actEditorView.setObjectName("actEditorView")
        self.actionMap_View = QtWidgets.QAction(MainWindow)
        self.actionMap_View.setIcon(icon15)
        self.actionMap_View.setObjectName("actionMap_View")
        self.actionIncreaseFontSize = QtWidgets.QAction(MainWindow)
        self.actionIncreaseFontSize.setObjectName("actionIncreaseFontSize")
        self.actionDecreaseFontSize = QtWidgets.QAction(MainWindow)
        self.actionDecreaseFontSize.setObjectName("actionDecreaseFontSize")
        self.actCloseProject = QtWidgets.QAction(MainWindow)
        self.actCloseProject.setEnabled(False)
        icon18 = QtWidgets.QIcon()
        icon18.addPixmap(QtWidgets.QPixmap(":/Images/Images/close.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        self.actCloseProject.setIcon(icon18)
        self.actCloseProject.setObjectName("actCloseProject")
        self.actVariableLibrary = QtWidgets.QAction(MainWindow)
        icon19 = QtWidgets.QIcon()
        icon19.addPixmap(QtWidgets.QPixmap(":/Images/Images/variable_library.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        self.actVariableLibrary.setIcon(icon19)
        self.actVariableLibrary.setObjectName("actVariableLibrary")
        self.actPreferences = QtWidgets.QAction(MainWindow)
        icon20 = QtWidgets.QIcon()
        icon20.addPixmap(QtWidgets.QPixmap(":/Images/Images/configure.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        self.actPreferences.setIcon(icon20)
        self.actPreferences.setObjectName("actPreferences")
        self.actLaunchResultBrowser = QtWidgets.QAction(MainWindow)
        icon21 = QtWidgets.QIcon()
        icon21.addPixmap(QtWidgets.QPixmap(":/Images/Images/result_browser.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        self.actLaunchResultBrowser.setIcon(icon21)
        self.actLaunchResultBrowser.setObjectName("actLaunchResultBrowser")
        self.actDatabaseSettings = QtWidgets.QAction(MainWindow)
        icon22 = QtWidgets.QIcon()
        icon22.addPixmap(QtWidgets.QPixmap(":/Images/Images/database_link.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        self.actDatabaseSettings.setIcon(icon22)
        self.actDatabaseSettings.setObjectName("actDatabaseSettings")
        self.actNewProject = QtWidgets.QAction(MainWindow)
        icon23 = QtWidgets.QIcon()
        icon23.addPixmap(QtWidgets.QPixmap(":/Images/Images/xml_document.png"), QtWidgets.QIcon.Normal, QtWidgets.QIcon.Off)
        self.actNewProject.setIcon(icon23)
        self.actNewProject.setObjectName("actNewProject")
        self.menuProject.addAction(self.actNewProject)
        self.menuProject.addAction(self.actOpenProject)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actSaveProject)
        self.menuProject.addAction(self.actSaveProjectAs)
        self.menuProject.addAction(self.actReloadProject)
        self.menuProject.addAction(self.actCloseProject)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actShowHidden)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actExit)
        self.menuHelp.addAction(self.actAbout)
        self.menuUtilities.addAction(self.actPythonView)
        self.menuUtilities.addAction(self.actLogView)
        self.menuUtilities.addAction(self.actEditorView)
        self.menuUtilities.addSeparator()
        self.menuUtilities.addAction(self.actVariableLibrary)
        self.menuUtilities.addAction(self.actLaunchResultBrowser)
        self.menuUtilities.addSeparator()
        self.menuUtilities.addAction(self.actPreferences)
        self.menuUtilities.addAction(self.actDatabaseSettings)
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuUtilities.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actOpenProject)
        self.toolBar.addAction(self.actSaveProject)
        self.toolBar.addAction(self.actCloseProject)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actVariableLibrary)
        self.toolBar.addAction(self.actLaunchResultBrowser)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actLogView)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actDatabaseSettings)
        self.toolBar.addAction(self.actPreferences)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.dataManager_toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.toolBox.setTabText(self.toolBox.indexOf(self.generalmanager_page), QtWidgets.QApplication.translate("MainWindow", "General", None, QtWidgets.QApplication.UnicodeUTF8))
        self.dataManager_toolBox.setTabText(self.dataManager_toolBox.indexOf(self.datamanager_xmlconfig), QtWidgets.QApplication.translate("MainWindow", "Tools", None, QtWidgets.QApplication.UnicodeUTF8))
        self.dataManager_toolBox.setTabText(self.dataManager_toolBox.indexOf(self.datamanager_dirview), QtWidgets.QApplication.translate("MainWindow", "Opus Data", None, QtWidgets.QApplication.UnicodeUTF8))
        self.toolBox.setTabText(self.toolBox.indexOf(self.datamanager_page), QtWidgets.QApplication.translate("MainWindow", "Data", None, QtWidgets.QApplication.UnicodeUTF8))
        self.toolBox.setTabText(self.toolBox.indexOf(self.modelmanager_page), QtWidgets.QApplication.translate("MainWindow", "Models", None, QtWidgets.QApplication.UnicodeUTF8))
        self.toolBox.setTabText(self.toolBox.indexOf(self.runmanager_page), QtWidgets.QApplication.translate("MainWindow", "Scenarios", None, QtWidgets.QApplication.UnicodeUTF8))
        self.toolBox.setTabText(self.toolBox.indexOf(self.resultsmanager_page), QtWidgets.QApplication.translate("MainWindow", "Results", None, QtWidgets.QApplication.UnicodeUTF8))
        self.menuProject.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, QtWidgets.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, QtWidgets.QApplication.UnicodeUTF8))
        self.menuUtilities.setTitle(QtWidgets.QApplication.translate("MainWindow", "Tools", None, QtWidgets.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "toolBar", None, QtWidgets.QApplication.UnicodeUTF8))
        self.mpActionZoomOut.setText(QtWidgets.QApplication.translate("MainWindow", "Zoom Out", None, QtWidgets.QApplication.UnicodeUTF8))
        self.mpActionPan.setText(QtWidgets.QApplication.translate("MainWindow", "Pan", None, QtWidgets.QApplication.UnicodeUTF8))
        self.mpActionAddRasterLayer.setText(QtWidgets.QApplication.translate("MainWindow", "Add Raster Layer", None, QtWidgets.QApplication.UnicodeUTF8))
        self.mpActionZoomIn.setText(QtWidgets.QApplication.translate("MainWindow", "Zoom In", None, QtWidgets.QApplication.UnicodeUTF8))
        self.mpActionAddVectorLayer.setText(QtWidgets.QApplication.translate("MainWindow", "Add Vector Layer", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actOpenProject.setText(QtWidgets.QApplication.translate("MainWindow", "Open Project", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actExit.setText(QtWidgets.QApplication.translate("MainWindow", "Exit", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actSaveProject.setText(QtWidgets.QApplication.translate("MainWindow", "Save Project", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actSaveProjectAs.setText(QtWidgets.QApplication.translate("MainWindow", "Save Project As...", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actShowHidden.setText(QtWidgets.QApplication.translate("MainWindow", "Show hidden", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actReloadProject.setText(QtWidgets.QApplication.translate("MainWindow", "Reload Project", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actionRun_Manager.setText(QtWidgets.QApplication.translate("MainWindow", "Run Manager", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tabActionEditor.setText(QtWidgets.QApplication.translate("MainWindow", "Editor", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tabActionMapView.setText(QtWidgets.QApplication.translate("MainWindow", "Map View", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tabActionPythonConsole.setText(QtWidgets.QApplication.translate("MainWindow", "Python Console", None, QtWidgets.QApplication.UnicodeUTF8))
        self.tabActionLogView.setText(QtWidgets.QApplication.translate("MainWindow", "Log View", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actPythonView.setText(QtWidgets.QApplication.translate("MainWindow", "Python Console", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actPythonView.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Open Python Console", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actLogView.setText(QtWidgets.QApplication.translate("MainWindow", "Log View", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actLogView.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Open Log View", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actEditorView.setText(QtWidgets.QApplication.translate("MainWindow", "Editor View", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actEditorView.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Open Editor View", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actionMap_View.setText(QtWidgets.QApplication.translate("MainWindow", "Map View", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actionIncreaseFontSize.setText(QtWidgets.QApplication.translate("MainWindow", "Increase Font Size", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actionDecreaseFontSize.setText(QtWidgets.QApplication.translate("MainWindow", "Decrease Font Size", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actCloseProject.setText(QtWidgets.QApplication.translate("MainWindow", "Close Project", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actCloseProject.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Close Project", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actVariableLibrary.setText(QtWidgets.QApplication.translate("MainWindow", "Variable Library", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actVariableLibrary.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Open Variable Library", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actPreferences.setText(QtWidgets.QApplication.translate("MainWindow", "Preferences", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actPreferences.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Open Preferences", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actLaunchResultBrowser.setText(QtWidgets.QApplication.translate("MainWindow", "Result Browser", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actLaunchResultBrowser.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Open Result Browser", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actDatabaseSettings.setText(QtWidgets.QApplication.translate("MainWindow", "Database Connection Settings", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actDatabaseSettings.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Open Database Connection Settings", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actNewProject.setText(QtWidgets.QApplication.translate("MainWindow", "New Project", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actNewProject.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Create a new project based on a built-in or custom project", None, QtWidgets.QApplication.UnicodeUTF8))
        self.actNewProject.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+N", None, QtWidgets.QApplication.UnicodeUTF8))

from . import opusmain_rc
