# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sat Jan 31 11:37:04 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 499)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/Images/cog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setGeometry(QtCore.QRect(0, 54, 802, 425))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.toolBox = QtGui.QTabWidget(self.splitter)
        self.toolBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBox.setBaseSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toolBox.setFont(font)
        self.toolBox.setObjectName("toolBox")
        self.generalmanager_page = QtGui.QWidget()
        self.generalmanager_page.setGeometry(QtCore.QRect(0, 0, 399, 372))
        self.generalmanager_page.setObjectName("generalmanager_page")
        self.gridlayout = QtGui.QGridLayout(self.generalmanager_page)
        self.gridlayout.setObjectName("gridlayout")
        self.toolBox.addTab(self.generalmanager_page, "")
        self.datamanager_page = QtGui.QWidget()
        self.datamanager_page.setGeometry(QtCore.QRect(0, 0, 399, 372))
        self.datamanager_page.setObjectName("datamanager_page")
        self.gridlayout1 = QtGui.QGridLayout(self.datamanager_page)
        self.gridlayout1.setObjectName("gridlayout1")
        self.dataManager_toolBox = QtGui.QTabWidget(self.datamanager_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataManager_toolBox.sizePolicy().hasHeightForWidth())
        self.dataManager_toolBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dataManager_toolBox.setFont(font)
        self.dataManager_toolBox.setObjectName("dataManager_toolBox")
        self.datamanager_xmlconfig = QtGui.QWidget()
        self.datamanager_xmlconfig.setGeometry(QtCore.QRect(0, 0, 369, 325))
        self.datamanager_xmlconfig.setObjectName("datamanager_xmlconfig")
        self.gridlayout2 = QtGui.QGridLayout(self.datamanager_xmlconfig)
        self.gridlayout2.setObjectName("gridlayout2")
        self.dataManager_toolBox.addTab(self.datamanager_xmlconfig, "")
        self.datamanager_dirview = QtGui.QWidget()
        self.datamanager_dirview.setGeometry(QtCore.QRect(0, 0, 372, 325))
        self.datamanager_dirview.setObjectName("datamanager_dirview")
        self.gridlayout3 = QtGui.QGridLayout(self.datamanager_dirview)
        self.gridlayout3.setObjectName("gridlayout3")
        self.dataManager_toolBox.addTab(self.datamanager_dirview, "")
        self.gridlayout1.addWidget(self.dataManager_toolBox, 0, 0, 1, 1)
        self.toolBox.addTab(self.datamanager_page, "")
        self.modelmanager_page = QtGui.QWidget()
        self.modelmanager_page.setGeometry(QtCore.QRect(0, 0, 399, 372))
        self.modelmanager_page.setObjectName("modelmanager_page")
        self.gridlayout4 = QtGui.QGridLayout(self.modelmanager_page)
        self.gridlayout4.setObjectName("gridlayout4")
        self.toolBox.addTab(self.modelmanager_page, "")
        self.runmanager_page = QtGui.QWidget()
        self.runmanager_page.setGeometry(QtCore.QRect(0, 0, 399, 372))
        self.runmanager_page.setObjectName("runmanager_page")
        self.gridlayout5 = QtGui.QGridLayout(self.runmanager_page)
        self.gridlayout5.setObjectName("gridlayout5")
        self.toolBox.addTab(self.runmanager_page, "")
        self.resultsmanager_page = QtGui.QWidget()
        self.resultsmanager_page.setGeometry(QtCore.QRect(0, 0, 399, 372))
        self.resultsmanager_page.setObjectName("resultsmanager_page")
        self.gridlayout6 = QtGui.QGridLayout(self.resultsmanager_page)
        self.gridlayout6.setObjectName("gridlayout6")
        self.toolBox.addTab(self.resultsmanager_page, "")
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.tabWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.tabWidget.setBaseSize(QtCore.QSize(1000, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_editorView = QtGui.QWidget()
        self.tab_editorView.setGeometry(QtCore.QRect(0, 0, 360, 372))
        self.tab_editorView.setObjectName("tab_editorView")
        self.gridlayout7 = QtGui.QGridLayout(self.tab_editorView)
        self.gridlayout7.setObjectName("gridlayout7")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Images/Images/table_lightning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_editorView, icon1, "")
        self.tab_pythonView = QtGui.QWidget()
        self.tab_pythonView.setGeometry(QtCore.QRect(0, 0, 360, 372))
        self.tab_pythonView.setObjectName("tab_pythonView")
        self.gridlayout8 = QtGui.QGridLayout(self.tab_pythonView)
        self.gridlayout8.setObjectName("gridlayout8")
        self.pythonLineWidget = QtGui.QWidget(self.tab_pythonView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pythonLineWidget.sizePolicy().hasHeightForWidth())
        self.pythonLineWidget.setSizePolicy(sizePolicy)
        self.pythonLineWidget.setObjectName("pythonLineWidget")
        self.hboxlayout = QtGui.QHBoxLayout(self.pythonLineWidget)
        self.hboxlayout.setObjectName("hboxlayout")
        self.pythonLabel = QtGui.QLabel(self.pythonLineWidget)
        self.pythonLabel.setObjectName("pythonLabel")
        self.hboxlayout.addWidget(self.pythonLabel)
        self.pythonLineEdit = QtGui.QLineEdit(self.pythonLineWidget)
        self.pythonLineEdit.setObjectName("pythonLineEdit")
        self.hboxlayout.addWidget(self.pythonLineEdit)
        self.gridlayout8.addWidget(self.pythonLineWidget, 1, 0, 1, 1)
        self.pythonWidget = QtGui.QWidget(self.tab_pythonView)
        self.pythonWidget.setObjectName("pythonWidget")
        self.gridlayout8.addWidget(self.pythonWidget, 0, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Images/Images/python_type.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_pythonView, icon2, "")
        self.tab_logView = QtGui.QWidget()
        self.tab_logView.setGeometry(QtCore.QRect(0, 0, 360, 372))
        self.tab_logView.setObjectName("tab_logView")
        self.gridlayout9 = QtGui.QGridLayout(self.tab_logView)
        self.gridlayout9.setObjectName("gridlayout9")
        self.logViewTextBrowser = QtGui.QTextBrowser(self.tab_logView)
        self.logViewTextBrowser.setObjectName("logViewTextBrowser")
        self.gridlayout9.addWidget(self.logViewTextBrowser, 0, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Images/Images/table.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_logView, icon3, "")
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 22))
        self.menubar.setObjectName("menubar")
        self.menuProject = QtGui.QMenu(self.menubar)
        self.menuProject.setObjectName("menuProject")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuUtilities = QtGui.QMenu(self.menubar)
        self.menuUtilities.setObjectName("menuUtilities")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setGeometry(QtCore.QRect(0, 479, 802, 20))
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setGeometry(QtCore.QRect(0, 22, 802, 32))
        self.toolBar.setIconSize(QtCore.QSize(20, 20))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.mpActionZoomOut = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Images/Images/mActionZoomOut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionZoomOut.setIcon(icon4)
        self.mpActionZoomOut.setObjectName("mpActionZoomOut")
        self.mpActionPan = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Images/Images/mActionPan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionPan.setIcon(icon5)
        self.mpActionPan.setObjectName("mpActionPan")
        self.mpActionAddRasterLayer = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Images/Images/mActionAddRasterLayer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionAddRasterLayer.setIcon(icon6)
        self.mpActionAddRasterLayer.setObjectName("mpActionAddRasterLayer")
        self.mpActionZoomIn = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Images/Images/mActionZoomIn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionZoomIn.setIcon(icon7)
        self.mpActionZoomIn.setObjectName("mpActionZoomIn")
        self.mpActionAddVectorLayer = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Images/Images/mActionAddLayer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionAddVectorLayer.setIcon(icon8)
        self.mpActionAddVectorLayer.setObjectName("mpActionAddVectorLayer")
        self.actionOpen_Project = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Images/Images/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_Project.setIcon(icon9)
        self.actionOpen_Project.setObjectName("actionOpen_Project")
        self.actionSave_Project = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Images/Images/script_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_Project.setIcon(icon10)
        self.actionSave_Project.setObjectName("actionSave_Project")
        self.actionSave_Project_As = QtGui.QAction(MainWindow)
        self.actionSave_Project_As.setIcon(icon10)
        self.actionSave_Project_As.setObjectName("actionSave_Project_As")
        self.actOpenProject = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Images/Images/folder_database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actOpenProject.setIcon(icon11)
        self.actOpenProject.setObjectName("actOpenProject")
        self.actExit = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Images/Images/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actExit.setIcon(icon12)
        self.actExit.setObjectName("actExit")
        self.actSaveProject = QtGui.QAction(MainWindow)
        self.actSaveProject.setEnabled(False)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/Images/Images/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actSaveProject.setIcon(icon13)
        self.actSaveProject.setObjectName("actSaveProject")
        self.actSaveProjectAs = QtGui.QAction(MainWindow)
        self.actSaveProjectAs.setEnabled(False)
        self.actSaveProjectAs.setIcon(icon10)
        self.actSaveProjectAs.setObjectName("actSaveProjectAs")
        self.actionRun_Manager = QtGui.QAction(MainWindow)
        self.actionRun_Manager.setIcon(icon)
        self.actionRun_Manager.setObjectName("actionRun_Manager")
        self.actAbout = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/Images/Images/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actAbout.setIcon(icon14)
        self.actAbout.setObjectName("actAbout")
        self.tabActionEditor = QtGui.QAction(MainWindow)
        self.tabActionEditor.setIcon(icon3)
        self.tabActionEditor.setObjectName("tabActionEditor")
        self.tabActionMapView = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/Images/Images/map.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabActionMapView.setIcon(icon15)
        self.tabActionMapView.setObjectName("tabActionMapView")
        self.tabActionPythonConsole = QtGui.QAction(MainWindow)
        self.tabActionPythonConsole.setIcon(icon2)
        self.tabActionPythonConsole.setObjectName("tabActionPythonConsole")
        self.tabActionLogView = QtGui.QAction(MainWindow)
        self.tabActionLogView.setIcon(icon9)
        self.tabActionLogView.setObjectName("tabActionLogView")
        self.actPythonView = QtGui.QAction(MainWindow)
        self.actPythonView.setEnabled(True)
        self.actPythonView.setIcon(icon2)
        self.actPythonView.setVisible(True)
        self.actPythonView.setIconVisibleInMenu(True)
        self.actPythonView.setObjectName("actPythonView")
        self.actLogView = QtGui.QAction(MainWindow)
        self.actLogView.setIcon(icon3)
        self.actLogView.setObjectName("actLogView")
        self.actEditorView = QtGui.QAction(MainWindow)
        self.actEditorView.setIcon(icon1)
        self.actEditorView.setObjectName("actEditorView")
        self.actionMap_View = QtGui.QAction(MainWindow)
        self.actionMap_View.setIcon(icon15)
        self.actionMap_View.setObjectName("actionMap_View")
        self.actionIncreaseFontSize = QtGui.QAction(MainWindow)
        self.actionIncreaseFontSize.setObjectName("actionIncreaseFontSize")
        self.actionDecreaseFontSize = QtGui.QAction(MainWindow)
        self.actionDecreaseFontSize.setObjectName("actionDecreaseFontSize")
        self.actCloseProject = QtGui.QAction(MainWindow)
        self.actCloseProject.setEnabled(False)
        self.actCloseProject.setIcon(icon9)
        self.actCloseProject.setObjectName("actCloseProject")
        self.actVariableLibrary = QtGui.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/Images/Images/book_edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actVariableLibrary.setIcon(icon16)
        self.actVariableLibrary.setObjectName("actVariableLibrary")
        self.actPreferences = QtGui.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/Images/Images/script.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actPreferences.setIcon(icon17)
        self.actPreferences.setObjectName("actPreferences")
        self.actLaunchResultBrowser = QtGui.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/Images/Images/layout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actLaunchResultBrowser.setIcon(icon18)
        self.actLaunchResultBrowser.setObjectName("actLaunchResultBrowser")
        self.actDatabaseSettings = QtGui.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/Images/Images/database_link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actDatabaseSettings.setIcon(icon19)
        self.actDatabaseSettings.setObjectName("actDatabaseSettings")
        self.menuProject.addAction(self.actOpenProject)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actSaveProject)
        self.menuProject.addAction(self.actSaveProjectAs)
        self.menuProject.addAction(self.actCloseProject)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actExit)
        self.menuHelp.addAction(self.actAbout)
        self.menuUtilities.addAction(self.actPythonView)
        self.menuUtilities.addAction(self.actLogView)
        self.menuUtilities.addAction(self.actEditorView)
        self.menuUtilities.addSeparator()
        self.menuUtilities.addAction(self.actVariableLibrary)
        self.menuUtilities.addAction(self.actLaunchResultBrowser)
        self.menuUtilities.addSeparator()
        self.menuUtilities.addAction(self.actPreferences)
        self.menuUtilities.addAction(self.actDatabaseSettings)
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuUtilities.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actOpenProject)
        self.toolBar.addAction(self.actSaveProject)
        self.toolBar.addAction(self.actCloseProject)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actVariableLibrary)
        self.toolBar.addAction(self.actLaunchResultBrowser)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actLogView)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actDatabaseSettings)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actPreferences)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.dataManager_toolBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.toolBox.setTabText(self.toolBox.indexOf(self.generalmanager_page), QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.dataManager_toolBox.setTabText(self.dataManager_toolBox.indexOf(self.datamanager_xmlconfig), QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.dataManager_toolBox.setTabText(self.dataManager_toolBox.indexOf(self.datamanager_dirview), QtGui.QApplication.translate("MainWindow", "Opus Data", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setTabText(self.toolBox.indexOf(self.datamanager_page), QtGui.QApplication.translate("MainWindow", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setTabText(self.toolBox.indexOf(self.modelmanager_page), QtGui.QApplication.translate("MainWindow", "Models", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setTabText(self.toolBox.indexOf(self.runmanager_page), QtGui.QApplication.translate("MainWindow", "Scenarios", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setTabText(self.toolBox.indexOf(self.resultsmanager_page), QtGui.QApplication.translate("MainWindow", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_editorView), QtGui.QApplication.translate("MainWindow", "Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.pythonLabel.setText(QtGui.QApplication.translate("MainWindow", ">>>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_pythonView), QtGui.QApplication.translate("MainWindow", "Python Console", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_logView), QtGui.QApplication.translate("MainWindow", "Log View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProject.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuUtilities.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionZoomOut.setText(QtGui.QApplication.translate("MainWindow", "Zoom Out", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionPan.setText(QtGui.QApplication.translate("MainWindow", "Pan", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionAddRasterLayer.setText(QtGui.QApplication.translate("MainWindow", "Add Raster Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionZoomIn.setText(QtGui.QApplication.translate("MainWindow", "Zoom In", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionAddVectorLayer.setText(QtGui.QApplication.translate("MainWindow", "Add Vector Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Project.setText(QtGui.QApplication.translate("MainWindow", "Open Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Project.setText(QtGui.QApplication.translate("MainWindow", "Save Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Project_As.setText(QtGui.QApplication.translate("MainWindow", "Save Project As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actOpenProject.setText(QtGui.QApplication.translate("MainWindow", "Open Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actSaveProject.setText(QtGui.QApplication.translate("MainWindow", "Save Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actSaveProjectAs.setText(QtGui.QApplication.translate("MainWindow", "Save Project As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_Manager.setText(QtGui.QApplication.translate("MainWindow", "Run Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.actAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.tabActionEditor.setText(QtGui.QApplication.translate("MainWindow", "Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.tabActionMapView.setText(QtGui.QApplication.translate("MainWindow", "Map View", None, QtGui.QApplication.UnicodeUTF8))
        self.tabActionPythonConsole.setText(QtGui.QApplication.translate("MainWindow", "Python Console", None, QtGui.QApplication.UnicodeUTF8))
        self.tabActionLogView.setText(QtGui.QApplication.translate("MainWindow", "Log View", None, QtGui.QApplication.UnicodeUTF8))
        self.actPythonView.setText(QtGui.QApplication.translate("MainWindow", "Python Console", None, QtGui.QApplication.UnicodeUTF8))
        self.actPythonView.setToolTip(QtGui.QApplication.translate("MainWindow", "Open Python Console", None, QtGui.QApplication.UnicodeUTF8))
        self.actLogView.setText(QtGui.QApplication.translate("MainWindow", "Log View", None, QtGui.QApplication.UnicodeUTF8))
        self.actLogView.setToolTip(QtGui.QApplication.translate("MainWindow", "Open Log View", None, QtGui.QApplication.UnicodeUTF8))
        self.actEditorView.setText(QtGui.QApplication.translate("MainWindow", "Editor View", None, QtGui.QApplication.UnicodeUTF8))
        self.actEditorView.setToolTip(QtGui.QApplication.translate("MainWindow", "Open Editor View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMap_View.setText(QtGui.QApplication.translate("MainWindow", "Map View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIncreaseFontSize.setText(QtGui.QApplication.translate("MainWindow", "Increase Font Size", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDecreaseFontSize.setText(QtGui.QApplication.translate("MainWindow", "Decrease Font Size", None, QtGui.QApplication.UnicodeUTF8))
        self.actCloseProject.setText(QtGui.QApplication.translate("MainWindow", "Close Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actCloseProject.setToolTip(QtGui.QApplication.translate("MainWindow", "Close Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actVariableLibrary.setText(QtGui.QApplication.translate("MainWindow", "Variable Library", None, QtGui.QApplication.UnicodeUTF8))
        self.actVariableLibrary.setToolTip(QtGui.QApplication.translate("MainWindow", "Open Variable Library", None, QtGui.QApplication.UnicodeUTF8))
        self.actPreferences.setText(QtGui.QApplication.translate("MainWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actPreferences.setToolTip(QtGui.QApplication.translate("MainWindow", "Open Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actLaunchResultBrowser.setText(QtGui.QApplication.translate("MainWindow", "Result Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.actLaunchResultBrowser.setToolTip(QtGui.QApplication.translate("MainWindow", "Open Result Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.actDatabaseSettings.setText(QtGui.QApplication.translate("MainWindow", "Database Connection Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.actDatabaseSettings.setToolTip(QtGui.QApplication.translate("MainWindow", "Open Database Connection Settings", None, QtGui.QApplication.UnicodeUTF8))

import opusmain_rc
