# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'opusmain.ui'
#
# Created: Mon Sep 15 11:17:22 2008
#      by: PyQt4 UI code generator 4.3.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(974, 707)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/Images/cog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setGeometry(QtCore.QRect(0, 22, 974, 665))
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(20, 12, 941, 651))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(10)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line_2 = QtGui.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tbOpenProject = QtGui.QToolButton(self.verticalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Images/Images/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbOpenProject.setIcon(icon1)
        self.tbOpenProject.setObjectName("tbOpenProject")
        self.horizontalLayout.addWidget(self.tbOpenProject)
        self.tbSaveProject = QtGui.QToolButton(self.verticalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Images/Images/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbSaveProject.setIcon(icon2)
        self.tbSaveProject.setObjectName("tbSaveProject")
        self.horizontalLayout.addWidget(self.tbSaveProject)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.tbVariableLibrary = QtGui.QToolButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbVariableLibrary.sizePolicy().hasHeightForWidth())
        self.tbVariableLibrary.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Images/Images/book_edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbVariableLibrary.setIcon(icon3)
        self.tbVariableLibrary.setObjectName("tbVariableLibrary")
        self.horizontalLayout.addWidget(self.tbVariableLibrary)
        self.tbResultsBrowser = QtGui.QToolButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbResultsBrowser.sizePolicy().hasHeightForWidth())
        self.tbResultsBrowser.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Images/Images/layout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbResultsBrowser.setIcon(icon4)
        self.tbResultsBrowser.setIconSize(QtCore.QSize(16, 16))
        self.tbResultsBrowser.setObjectName("tbResultsBrowser")
        self.horizontalLayout.addWidget(self.tbResultsBrowser)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.tbPythonConsole = QtGui.QToolButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbPythonConsole.sizePolicy().hasHeightForWidth())
        self.tbPythonConsole.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Images/Images/python_type.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbPythonConsole.setIcon(icon5)
        self.tbPythonConsole.setObjectName("tbPythonConsole")
        self.horizontalLayout.addWidget(self.tbPythonConsole)
        self.tbLogView = QtGui.QToolButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbLogView.sizePolicy().hasHeightForWidth())
        self.tbLogView.setSizePolicy(sizePolicy)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Images/Images/table.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbLogView.setIcon(icon6)
        self.tbLogView.setObjectName("tbLogView")
        self.horizontalLayout.addWidget(self.tbLogView)
        self.tbEditorView = QtGui.QToolButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbEditorView.sizePolicy().hasHeightForWidth())
        self.tbEditorView.setSizePolicy(sizePolicy)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Images/Images/table_lightning.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbEditorView.setIcon(icon7)
        self.tbEditorView.setObjectName("tbEditorView")
        self.horizontalLayout.addWidget(self.tbEditorView)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.tbDatabaseConfigurations = QtGui.QToolButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbDatabaseConfigurations.sizePolicy().hasHeightForWidth())
        self.tbDatabaseConfigurations.setSizePolicy(sizePolicy)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Images/Images/database_link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbDatabaseConfigurations.setIcon(icon8)
        self.tbDatabaseConfigurations.setIconSize(QtCore.QSize(16, 16))
        self.tbDatabaseConfigurations.setObjectName("tbDatabaseConfigurations")
        self.horizontalLayout.addWidget(self.tbDatabaseConfigurations)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.toolBox = QtGui.QTabWidget(self.verticalLayoutWidget)
        self.toolBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(100, 0))
        self.toolBox.setBaseSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toolBox.setFont(font)
        self.toolBox.setObjectName("toolBox")
        self.generalmanager_page = QtGui.QWidget()
        self.generalmanager_page.setGeometry(QtCore.QRect(0, 0, 323, 580))
        self.generalmanager_page.setObjectName("generalmanager_page")
        self.gridlayout = QtGui.QGridLayout(self.generalmanager_page)
        self.gridlayout.setObjectName("gridlayout")
        self.toolBox.addTab(self.generalmanager_page, "")
        self.datamanager_page = QtGui.QWidget()
        self.datamanager_page.setGeometry(QtCore.QRect(0, 0, 323, 580))
        self.datamanager_page.setObjectName("datamanager_page")
        self.gridlayout1 = QtGui.QGridLayout(self.datamanager_page)
        self.gridlayout1.setObjectName("gridlayout1")
        self.dataManager_toolBox = QtGui.QTabWidget(self.datamanager_page)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dataManager_toolBox.setFont(font)
        self.dataManager_toolBox.setObjectName("dataManager_toolBox")
        self.datamanager_xmlconfig = QtGui.QWidget()
        self.datamanager_xmlconfig.setGeometry(QtCore.QRect(0, 0, 293, 533))
        self.datamanager_xmlconfig.setObjectName("datamanager_xmlconfig")
        self.gridlayout2 = QtGui.QGridLayout(self.datamanager_xmlconfig)
        self.gridlayout2.setObjectName("gridlayout2")
        self.dataManager_toolBox.addTab(self.datamanager_xmlconfig, "")
        self.datamanager_dirview = QtGui.QWidget()
        self.datamanager_dirview.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.datamanager_dirview.setObjectName("datamanager_dirview")
        self.gridlayout3 = QtGui.QGridLayout(self.datamanager_dirview)
        self.gridlayout3.setObjectName("gridlayout3")
        self.dataManager_toolBox.addTab(self.datamanager_dirview, "")
        self.gridlayout1.addWidget(self.dataManager_toolBox, 0, 0, 1, 1)
        self.toolBox.addTab(self.datamanager_page, "")
        self.modelmanager_page = QtGui.QWidget()
        self.modelmanager_page.setGeometry(QtCore.QRect(0, 0, 323, 580))
        self.modelmanager_page.setObjectName("modelmanager_page")
        self.gridlayout4 = QtGui.QGridLayout(self.modelmanager_page)
        self.gridlayout4.setObjectName("gridlayout4")
        self.toolBox.addTab(self.modelmanager_page, "")
        self.runmanager_page = QtGui.QWidget()
        self.runmanager_page.setGeometry(QtCore.QRect(0, 0, 323, 580))
        self.runmanager_page.setObjectName("runmanager_page")
        self.gridlayout5 = QtGui.QGridLayout(self.runmanager_page)
        self.gridlayout5.setObjectName("gridlayout5")
        self.toolBox.addTab(self.runmanager_page, "")
        self.resultsmanager_page = QtGui.QWidget()
        self.resultsmanager_page.setGeometry(QtCore.QRect(0, 0, 323, 580))
        self.resultsmanager_page.setObjectName("resultsmanager_page")
        self.gridlayout6 = QtGui.QGridLayout(self.resultsmanager_page)
        self.gridlayout6.setObjectName("gridlayout6")
        self.toolBox.addTab(self.resultsmanager_page, "")
        self.verticalLayout_2.addWidget(self.toolBox)
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(600, 0))
        self.tabWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.tabWidget.setBaseSize(QtCore.QSize(1000, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_editorView = QtGui.QWidget()
        self.tab_editorView.setGeometry(QtCore.QRect(0, 0, 594, 622))
        self.tab_editorView.setObjectName("tab_editorView")
        self.gridlayout7 = QtGui.QGridLayout(self.tab_editorView)
        self.gridlayout7.setObjectName("gridlayout7")
        self.tabWidget.addTab(self.tab_editorView, icon7, "")
        self.tab_pythonView = QtGui.QWidget()
        self.tab_pythonView.setGeometry(QtCore.QRect(0, 0, 594, 622))
        self.tab_pythonView.setObjectName("tab_pythonView")
        self.gridlayout8 = QtGui.QGridLayout(self.tab_pythonView)
        self.gridlayout8.setObjectName("gridlayout8")
        self.pythonLineWidget = QtGui.QWidget(self.tab_pythonView)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pythonLineWidget.sizePolicy().hasHeightForWidth())
        self.pythonLineWidget.setSizePolicy(sizePolicy)
        self.pythonLineWidget.setObjectName("pythonLineWidget")
        self.hboxlayout = QtGui.QHBoxLayout(self.pythonLineWidget)
        self.hboxlayout.setObjectName("hboxlayout")
        self.pythonLabel = QtGui.QLabel(self.pythonLineWidget)
        self.pythonLabel.setObjectName("pythonLabel")
        self.hboxlayout.addWidget(self.pythonLabel)
        self.pythonLineEdit = QtGui.QLineEdit(self.pythonLineWidget)
        self.pythonLineEdit.setObjectName("pythonLineEdit")
        self.hboxlayout.addWidget(self.pythonLineEdit)
        self.gridlayout8.addWidget(self.pythonLineWidget, 1, 0, 1, 1)
        self.pythonWidget = QtGui.QWidget(self.tab_pythonView)
        self.pythonWidget.setObjectName("pythonWidget")
        self.gridlayout8.addWidget(self.pythonWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_pythonView, icon5, "")
        self.tab_logView = QtGui.QWidget()
        self.tab_logView.setGeometry(QtCore.QRect(0, 0, 594, 622))
        self.tab_logView.setObjectName("tab_logView")
        self.gridlayout9 = QtGui.QGridLayout(self.tab_logView)
        self.gridlayout9.setObjectName("gridlayout9")
        self.logViewTextBrowser = QtGui.QTextBrowser(self.tab_logView)
        self.logViewTextBrowser.setObjectName("logViewTextBrowser")
        self.gridlayout9.addWidget(self.logViewTextBrowser, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_logView, icon6, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 974, 22))
        self.menubar.setObjectName("menubar")
        self.menuProject = QtGui.QMenu(self.menubar)
        self.menuProject.setObjectName("menuProject")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuUtilities = QtGui.QMenu(self.menubar)
        self.menuUtilities.setObjectName("menuUtilities")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setGeometry(QtCore.QRect(0, 687, 974, 20))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.mpActionZoomOut = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Images/Images/mActionZoomOut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionZoomOut.setIcon(icon9)
        self.mpActionZoomOut.setObjectName("mpActionZoomOut")
        self.mpActionPan = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Images/Images/mActionPan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionPan.setIcon(icon10)
        self.mpActionPan.setObjectName("mpActionPan")
        self.mpActionAddRasterLayer = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Images/Images/mActionAddRasterLayer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionAddRasterLayer.setIcon(icon11)
        self.mpActionAddRasterLayer.setObjectName("mpActionAddRasterLayer")
        self.mpActionZoomIn = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Images/Images/mActionZoomIn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionZoomIn.setIcon(icon12)
        self.mpActionZoomIn.setObjectName("mpActionZoomIn")
        self.mpActionAddVectorLayer = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/Images/Images/mActionAddLayer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mpActionAddVectorLayer.setIcon(icon13)
        self.mpActionAddVectorLayer.setObjectName("mpActionAddVectorLayer")
        self.actionOpen_Project = QtGui.QAction(MainWindow)
        self.actionOpen_Project.setIcon(icon1)
        self.actionOpen_Project.setObjectName("actionOpen_Project")
        self.actionSave_Project = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/Images/Images/script_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_Project.setIcon(icon14)
        self.actionSave_Project.setObjectName("actionSave_Project")
        self.actionSave_Project_As = QtGui.QAction(MainWindow)
        self.actionSave_Project_As.setIcon(icon14)
        self.actionSave_Project_As.setObjectName("actionSave_Project_As")
        self.actionOpen_Project_2 = QtGui.QAction(MainWindow)
        self.actionOpen_Project_2.setIcon(icon1)
        self.actionOpen_Project_2.setObjectName("actionOpen_Project_2")
        self.actionExit = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/Images/Images/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon15)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_Project_2 = QtGui.QAction(MainWindow)
        self.actionSave_Project_2.setIcon(icon2)
        self.actionSave_Project_2.setObjectName("actionSave_Project_2")
        self.actionSave_Project_As_2 = QtGui.QAction(MainWindow)
        self.actionSave_Project_As_2.setIcon(icon14)
        self.actionSave_Project_As_2.setObjectName("actionSave_Project_As_2")
        self.actionRun_Manager = QtGui.QAction(MainWindow)
        self.actionRun_Manager.setIcon(icon)
        self.actionRun_Manager.setObjectName("actionRun_Manager")
        self.actionAbout = QtGui.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/Images/Images/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon16)
        self.actionAbout.setObjectName("actionAbout")
        self.tabActionEditor = QtGui.QAction(MainWindow)
        self.tabActionEditor.setIcon(icon6)
        self.tabActionEditor.setObjectName("tabActionEditor")
        self.tabActionMapView = QtGui.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/Images/Images/map.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabActionMapView.setIcon(icon17)
        self.tabActionMapView.setObjectName("tabActionMapView")
        self.tabActionPythonConsole = QtGui.QAction(MainWindow)
        self.tabActionPythonConsole.setIcon(icon5)
        self.tabActionPythonConsole.setObjectName("tabActionPythonConsole")
        self.tabActionLogView = QtGui.QAction(MainWindow)
        self.tabActionLogView.setIcon(icon1)
        self.tabActionLogView.setObjectName("tabActionLogView")
        self.actionPython_View = QtGui.QAction(MainWindow)
        self.actionPython_View.setIcon(icon5)
        self.actionPython_View.setObjectName("actionPython_View")
        self.actionLog_View = QtGui.QAction(MainWindow)
        self.actionLog_View.setIcon(icon6)
        self.actionLog_View.setObjectName("actionLog_View")
        self.actionEditor_View = QtGui.QAction(MainWindow)
        self.actionEditor_View.setIcon(icon7)
        self.actionEditor_View.setObjectName("actionEditor_View")
        self.actionMap_View = QtGui.QAction(MainWindow)
        self.actionMap_View.setIcon(icon17)
        self.actionMap_View.setObjectName("actionMap_View")
        self.actionIncreaseFontSize = QtGui.QAction(MainWindow)
        self.actionIncreaseFontSize.setObjectName("actionIncreaseFontSize")
        self.actionDecreaseFontSize = QtGui.QAction(MainWindow)
        self.actionDecreaseFontSize.setObjectName("actionDecreaseFontSize")
        self.actionClose_Project = QtGui.QAction(MainWindow)
        self.actionClose_Project.setIcon(icon1)
        self.actionClose_Project.setObjectName("actionClose_Project")
        self.actionEdit_all_variables = QtGui.QAction(MainWindow)
        self.actionEdit_all_variables.setIcon(icon3)
        self.actionEdit_all_variables.setObjectName("actionEdit_all_variables")
        self.actionPreferences = QtGui.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/Images/Images/script.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferences.setIcon(icon18)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actLaunchResultBrowser = QtGui.QAction(MainWindow)
        self.actLaunchResultBrowser.setIcon(icon4)
        self.actLaunchResultBrowser.setObjectName("actLaunchResultBrowser")
        self.actionDatabaseSettings = QtGui.QAction(MainWindow)
        self.actionDatabaseSettings.setIcon(icon8)
        self.actionDatabaseSettings.setObjectName("actionDatabaseSettings")
        self.menuProject.addAction(self.actionOpen_Project_2)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actionSave_Project_2)
        self.menuProject.addAction(self.actionSave_Project_As_2)
        self.menuProject.addAction(self.actionClose_Project)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuUtilities.addAction(self.actionPython_View)
        self.menuUtilities.addAction(self.actionLog_View)
        self.menuUtilities.addAction(self.actionEditor_View)
        self.menuUtilities.addSeparator()
        self.menuUtilities.addAction(self.actionEdit_all_variables)
        self.menuUtilities.addAction(self.actLaunchResultBrowser)
        self.menuUtilities.addSeparator()
        self.menuUtilities.addAction(self.actionPreferences)
        self.menuUtilities.addAction(self.actionDatabaseSettings)
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuUtilities.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(3)
        self.dataManager_toolBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.tbOpenProject.setToolTip(QtGui.QApplication.translate("MainWindow", "Open project", None, QtGui.QApplication.UnicodeUTF8))
        self.tbOpenProject.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSaveProject.setToolTip(QtGui.QApplication.translate("MainWindow", "Save project", None, QtGui.QApplication.UnicodeUTF8))
        self.tbSaveProject.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbVariableLibrary.setToolTip(QtGui.QApplication.translate("MainWindow", "Open Variable Library", None, QtGui.QApplication.UnicodeUTF8))
        self.tbVariableLibrary.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbResultsBrowser.setToolTip(QtGui.QApplication.translate("MainWindow", "Open Results Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.tbResultsBrowser.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPythonConsole.setToolTip(QtGui.QApplication.translate("MainWindow", "Open python console", None, QtGui.QApplication.UnicodeUTF8))
        self.tbPythonConsole.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbLogView.setToolTip(QtGui.QApplication.translate("MainWindow", "Open log view", None, QtGui.QApplication.UnicodeUTF8))
        self.tbLogView.setText(QtGui.QApplication.translate("MainWindow", "Log view", None, QtGui.QApplication.UnicodeUTF8))
        self.tbEditorView.setToolTip(QtGui.QApplication.translate("MainWindow", "Open editor view", None, QtGui.QApplication.UnicodeUTF8))
        self.tbEditorView.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tbDatabaseConfigurations.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setTabText(self.toolBox.indexOf(self.generalmanager_page), QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.dataManager_toolBox.setTabText(self.dataManager_toolBox.indexOf(self.datamanager_xmlconfig), QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.dataManager_toolBox.setTabText(self.dataManager_toolBox.indexOf(self.datamanager_dirview), QtGui.QApplication.translate("MainWindow", "Opus Data", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setTabText(self.toolBox.indexOf(self.datamanager_page), QtGui.QApplication.translate("MainWindow", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setTabText(self.toolBox.indexOf(self.modelmanager_page), QtGui.QApplication.translate("MainWindow", "Models", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setTabText(self.toolBox.indexOf(self.runmanager_page), QtGui.QApplication.translate("MainWindow", "Scenarios", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setTabText(self.toolBox.indexOf(self.resultsmanager_page), QtGui.QApplication.translate("MainWindow", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_editorView), QtGui.QApplication.translate("MainWindow", "Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.pythonLabel.setText(QtGui.QApplication.translate("MainWindow", ">>>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_pythonView), QtGui.QApplication.translate("MainWindow", "Python Console", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_logView), QtGui.QApplication.translate("MainWindow", "Log View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuProject.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuUtilities.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionZoomOut.setText(QtGui.QApplication.translate("MainWindow", "Zoom Out", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionPan.setText(QtGui.QApplication.translate("MainWindow", "Pan", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionAddRasterLayer.setText(QtGui.QApplication.translate("MainWindow", "Add Raster Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionZoomIn.setText(QtGui.QApplication.translate("MainWindow", "Zoom In", None, QtGui.QApplication.UnicodeUTF8))
        self.mpActionAddVectorLayer.setText(QtGui.QApplication.translate("MainWindow", "Add Vector Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Project.setText(QtGui.QApplication.translate("MainWindow", "Open Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Project.setText(QtGui.QApplication.translate("MainWindow", "Save Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Project_As.setText(QtGui.QApplication.translate("MainWindow", "Save Project As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Project_2.setText(QtGui.QApplication.translate("MainWindow", "Open Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Project_2.setText(QtGui.QApplication.translate("MainWindow", "Save Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Project_As_2.setText(QtGui.QApplication.translate("MainWindow", "Save Project As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun_Manager.setText(QtGui.QApplication.translate("MainWindow", "Run Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.tabActionEditor.setText(QtGui.QApplication.translate("MainWindow", "Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.tabActionMapView.setText(QtGui.QApplication.translate("MainWindow", "Map View", None, QtGui.QApplication.UnicodeUTF8))
        self.tabActionPythonConsole.setText(QtGui.QApplication.translate("MainWindow", "Python Console", None, QtGui.QApplication.UnicodeUTF8))
        self.tabActionLogView.setText(QtGui.QApplication.translate("MainWindow", "Log View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPython_View.setText(QtGui.QApplication.translate("MainWindow", "Python Console", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLog_View.setText(QtGui.QApplication.translate("MainWindow", "Log View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditor_View.setText(QtGui.QApplication.translate("MainWindow", "Editor View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMap_View.setText(QtGui.QApplication.translate("MainWindow", "Map View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIncreaseFontSize.setText(QtGui.QApplication.translate("MainWindow", "Increase Font Size", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDecreaseFontSize.setText(QtGui.QApplication.translate("MainWindow", "Decrease Font Size", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose_Project.setText(QtGui.QApplication.translate("MainWindow", "Close Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit_all_variables.setText(QtGui.QApplication.translate("MainWindow", "Variable Library", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("MainWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actLaunchResultBrowser.setText(QtGui.QApplication.translate("MainWindow", "Result Browser", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDatabaseSettings.setText(QtGui.QApplication.translate("MainWindow", "Database Connection Settings", None, QtGui.QApplication.UnicodeUTF8))

import opusmain_rc
