# Opus/UrbanSim urban simulation software.
# Copyright (C) 2010-2011 University of California, Berkeley, 2005-2009 University of Washington
# See opus_core/LICENSE 

class DummyName(object):
    """instances of DummyName are used to construct local environments for evaluating the expression
    in autogenerated variable classes."""
    pass
