# Input tables:
#	JOB_PROPORTIONS_BY_SECTOR
#	ZONE_WEIGHTS
#	JOBS_PER_COUNTY

# Output Tables:
#	HOMEBASED_JOBS_PER_ZONE
#	NONHOMEBASED_JOBS_PER_ZONE


#drop the output tables if versions of them already exist
DROP TABLE IF EXISTS DISTRIBUTED_JOBS;
DROP TABLE IF EXISTS HOMEBASED_JOBS_PER_ZONE;
DROP TABLE IF EXISTS NONHOMEBASED_JOBS_PER_ZONE;

CREATE TABLE IF NOT EXISTS DISTRIBUTED_JOBS (
	COUNTY VARCHAR(3), 
	SECTOR INT, 
	PARCEL_ID VARCHAR(16), 
	HOMEBASED TINYINT
);

# Get the total number of jobs per county sector to be placed on RESIDENTIAL parcels
# Then distribute Jobs across ZONES in accordance with the ZONE_WEIGHT_RES

CREATE TEMPORARY TABLE HOMEBASED_JOBS_PER_SECTOR
SELECT 
	a.COUNTY,
	a.SECTOR,
	(a.PROPORTION_OF_JOBS_HOMEBASED * b.TOTAL_COUNTY_JOBS) as HOMEBASED_JOBS
FROM JOB_PROPORTIONS_BY_SECTOR a 
	INNER JOIN JOBS_PER_COUNTY b ON a.county = b.county AND a.SECTOR = b.SECTOR;
	
CREATE TABLE HOMEBASED_JOBS_PER_ZONE
SELECT
	a.COUNTY,
	a.SECTOR,
	b.ZONE,
	ROUND((a.HOMEBASED_JOBS * b.ZONE_WEIGHT_HOMEBASED),0) AS HOMEBASED_JOBS
FROM HOMEBASED_JOBS_PER_SECTOR a
	INNER JOIN ZONE_WEIGHTS b ON a.county = b.county AND a.sector = b.sector;

# Get the total number of jobs per county sector to be placed on NONRESIDENTIAL parcels
# Then distribute Jobs across MAZs in accordance with the MAZ_WEIGHT_NONRES

CREATE TEMPORARY TABLE NONHOMEBASED_JOBS_PER_SECTOR
SELECT 
	a.COUNTY,
	a.SECTOR,
	(a.PROPORTION_OF_JOBS_NONHOMEBASED * b.TOTAL_COUNTY_JOBS) as NONHOMEBASED_JOBS
FROM JOB_PROPORTIONS_BY_SECTOR a 
	INNER JOIN JOBS_PER_COUNTY b ON a.county = b.county AND a.SECTOR = b.SECTOR;
	
CREATE TABLE NONHOMEBASED_JOBS_PER_ZONE
SELECT
	a.COUNTY,
	a.SECTOR,
	b.ZONE,
	ROUND((a.NONHOMEBASED_JOBS * b.ZONE_WEIGHT_NONHOMEBASED),0) AS NONHOMEBASED_JOBS
FROM NONHOMEBASED_JOBS_PER_SECTOR a
	INNER JOIN ZONE_WEIGHTS b ON a.county = b.county and a.sector = b.sector;

# CLEANUP
DROP TABLE NONHOMEBASED_JOBS_PER_SECTOR;
DROP TABLE HOMEBASED_JOBS_PER_SECTOR;

# NOT PERMANENT LINES:
#DELETE FROM NONHOMEBASED_JOBS_PER_ZONE WHERE SECTOR <> 1 OR  (ZONE <> 1 AND ZONE <> 3);
#DELETE FROM HOMEBASED_JOBS_PER_ZONE WHERE SECTOR <> 2 OR  (ZONE <> 2 AND ZONE <> 4);
#UPDATE NONHOMEBASED_JOBS_PER_ZONE SET NONHOMEBASED_JOBS = 1;
#UPDATE HOMEBASED_JOBS_PER_ZONE SET HOMEBASED_JOBS = 1;

