# Opus/UrbanSim urban simulation software.
# Copyright (C) 2010-2011 University of California, Berkeley, 2005-2009 University of Washington
# See opus_core/LICENSE 

aliases = [
    "zone_id = job.disaggregate(building.zone_id)",
    "county_id = job.disaggregate(zone.county_id, intermediates=[building])",
    "sector_county_id = 1*((job.sector_id==1)*(job.county_id==1))+2*((job.sector_id==2)*(job.county_id==1))+3*((job.sector_id==3)*(job.county_id==1))+4*((job.sector_id==4)*(job.county_id==1))+5*((job.sector_id==5)*(job.county_id==1))+6*((job.sector_id==6)*(job.county_id==1))+7*((job.sector_id==7)*(job.county_id==1))+8*((job.sector_id==8)*(job.county_id==1))+9*((job.sector_id==9)*(job.county_id==1))+10*((job.sector_id==10)*(job.county_id==1))+11*((job.sector_id==1)*(job.county_id==2))+12*((job.sector_id==2)*(job.county_id==2))+13*((job.sector_id==3)*(job.county_id==2))+14*((job.sector_id==4)*(job.county_id==2))+15*((job.sector_id==5)*(job.county_id==2))+16*((job.sector_id==6)*(job.county_id==2))+17*((job.sector_id==7)*(job.county_id==2))+18*((job.sector_id==8)*(job.county_id==2))+19*((job.sector_id==9)*(job.county_id==2))+20*((job.sector_id==10)*(job.county_id==2))+21*((job.sector_id==1)*(job.county_id==3))+22*((job.sector_id==2)*(job.county_id==3))+23*((job.sector_id==3)*(job.county_id==3))+24*((job.sector_id==4)*(job.county_id==3))+25*((job.sector_id==5)*(job.county_id==3))+26*((job.sector_id==6)*(job.county_id==3))+27*((job.sector_id==7)*(job.county_id==3))+28*((job.sector_id==8)*(job.county_id==3))+29*((job.sector_id==9)*(job.county_id==3))+30*((job.sector_id==10)*(job.county_id==3))+31*((job.sector_id==1)*(job.county_id==4))+32*((job.sector_id==2)*(job.county_id==4))+33*((job.sector_id==3)*(job.county_id==4))+34*((job.sector_id==4)*(job.county_id==4))+35*((job.sector_id==5)*(job.county_id==4))+36*((job.sector_id==6)*(job.county_id==4))+37*((job.sector_id==7)*(job.county_id==4))+38*((job.sector_id==8)*(job.county_id==4))+39*((job.sector_id==9)*(job.county_id==4))+40*((job.sector_id==10)*(job.county_id==4))",
           ]
