# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_model_from_template.ui'
#
# Created: Wed Sep 10 16:30:50 2008
#      by: PyQt4 UI code generator 4.3.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_CreateModelFromTemplate(object):
    def setupUi(self, CreateModelFromTemplate):
        CreateModelFromTemplate.setObjectName("CreateModelFromTemplate")
        CreateModelFromTemplate.resize(599, 276)
        self.vboxlayout = QtGui.QVBoxLayout(CreateModelFromTemplate)
        self.vboxlayout.setObjectName("vboxlayout")
        self.variableBox = QtGui.QGroupBox(CreateModelFromTemplate)
        self.variableBox.setObjectName("variableBox")
        self.vboxlayout1 = QtGui.QVBoxLayout(self.variableBox)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.nameWidget = QtGui.QWidget(self.variableBox)
        self.nameWidget.setObjectName("nameWidget")
        self.hboxlayout = QtGui.QHBoxLayout(self.nameWidget)
        self.hboxlayout.setObjectName("hboxlayout")
        self.label = QtGui.QLabel(self.nameWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label.setObjectName("label")
        self.hboxlayout.addWidget(self.label)
        self.cbModelName = QtGui.QLineEdit(self.nameWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbModelName.sizePolicy().hasHeightForWidth())
        self.cbModelName.setSizePolicy(sizePolicy)
        self.cbModelName.setObjectName("cbModelName")
        self.hboxlayout.addWidget(self.cbModelName)
        self.vboxlayout1.addWidget(self.nameWidget)
        self.datasetWidget = QtGui.QWidget(self.variableBox)
        self.datasetWidget.setObjectName("datasetWidget")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.datasetWidget)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.label_2 = QtGui.QLabel(self.datasetWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_2.setObjectName("label_2")
        self.hboxlayout1.addWidget(self.label_2)
        self.cboDataset = QtGui.QComboBox(self.datasetWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboDataset.sizePolicy().hasHeightForWidth())
        self.cboDataset.setSizePolicy(sizePolicy)
        self.cboDataset.setObjectName("cboDataset")
        self.hboxlayout1.addWidget(self.cboDataset)
        self.vboxlayout1.addWidget(self.datasetWidget)
        self.sourceWidget = QtGui.QWidget(self.variableBox)
        self.sourceWidget.setObjectName("sourceWidget")
        self.hboxlayout2 = QtGui.QHBoxLayout(self.sourceWidget)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.label_4 = QtGui.QLabel(self.sourceWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_4.setObjectName("label_4")
        self.hboxlayout2.addWidget(self.label_4)
        self.cboDependentVariable = QtGui.QComboBox(self.sourceWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboDependentVariable.sizePolicy().hasHeightForWidth())
        self.cboDependentVariable.setSizePolicy(sizePolicy)
        self.cboDependentVariable.setObjectName("cboDependentVariable")
        self.hboxlayout2.addWidget(self.cboDependentVariable)
        self.vboxlayout1.addWidget(self.sourceWidget)
        self.vboxlayout.addWidget(self.variableBox)
        self.widget = QtGui.QWidget(CreateModelFromTemplate)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 45))
        self.widget.setObjectName("widget")
        self.hboxlayout3 = QtGui.QHBoxLayout(self.widget)
        self.hboxlayout3.setObjectName("hboxlayout3")
        spacerItem = QtGui.QSpacerItem(441, 24, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem)
        self.line = QtGui.QFrame(self.widget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.hboxlayout3.addWidget(self.line)
        self.saveChanges = QtGui.QPushButton(self.widget)
        self.saveChanges.setEnabled(True)
        self.saveChanges.setObjectName("saveChanges")
        self.hboxlayout3.addWidget(self.saveChanges)
        self.cancelWindow = QtGui.QPushButton(self.widget)
        self.cancelWindow.setObjectName("cancelWindow")
        self.hboxlayout3.addWidget(self.cancelWindow)
        self.vboxlayout.addWidget(self.widget)

        self.retranslateUi(CreateModelFromTemplate)
        QtCore.QMetaObject.connectSlotsByName(CreateModelFromTemplate)

    def retranslateUi(self, CreateModelFromTemplate):
        CreateModelFromTemplate.setWindowTitle(QtGui.QApplication.translate("CreateModelFromTemplate", "Create model from template", None, QtGui.QApplication.UnicodeUTF8))
        self.variableBox.setTitle(QtGui.QApplication.translate("CreateModelFromTemplate", "New model configuration - derived from template", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setToolTip(QtGui.QApplication.translate("CreateModelFromTemplate", "A name for the new model. Use only alphanumeric characters.", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CreateModelFromTemplate", "Model name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setToolTip(QtGui.QApplication.translate("CreateModelFromTemplate", "The dataset that this model operates upon. ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("CreateModelFromTemplate", "Dataset:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setToolTip(QtGui.QApplication.translate("CreateModelFromTemplate", "The variable that is to be predicted.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("CreateModelFromTemplate", "Dependent variable:", None, QtGui.QApplication.UnicodeUTF8))
        self.saveChanges.setToolTip(QtGui.QApplication.translate("CreateModelFromTemplate", "Accept the new variable and return to the Variable Library.", None, QtGui.QApplication.UnicodeUTF8))
        self.saveChanges.setText(QtGui.QApplication.translate("CreateModelFromTemplate", "Accept", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelWindow.setToolTip(QtGui.QApplication.translate("CreateModelFromTemplate", "Return to the Variable Library without saving.", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelWindow.setText(QtGui.QApplication.translate("CreateModelFromTemplate", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

