# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/ckla/Documents/workspace/variable_library_rewrite/opus_gui/models_manager/views/submodel_editor.ui'
#
# Created: Fri May  1 16:06:59 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_SubModelEditor(object):
    def setupUi(self, SubModelEditor):
        SubModelEditor.setObjectName("SubModelEditor")
        SubModelEditor.resize(729, 498)
        SubModelEditor.setModal(True)
        self.verticalLayout_2 = QtGui.QVBoxLayout(SubModelEditor)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(SubModelEditor)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.le_name = QtGui.QLineEdit(SubModelEditor)
        self.le_name.setObjectName("le_name")
        self.horizontalLayout_3.addWidget(self.le_name)
        self.label_4 = QtGui.QLabel(SubModelEditor)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.spin_id = QtGui.QSpinBox(SubModelEditor)
        self.spin_id.setWrapping(False)
        self.spin_id.setFrame(False)
        self.spin_id.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.spin_id.setMinimum(-10000)
        self.spin_id.setMaximum(10000)
        self.spin_id.setProperty("value", QtCore.QVariant(-2))
        self.spin_id.setObjectName("spin_id")
        self.horizontalLayout_3.addWidget(self.spin_id)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtGui.QLabel(SubModelEditor)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.le_description = QtGui.QLineEdit(SubModelEditor)
        self.le_description.setObjectName("le_description")
        self.horizontalLayout_4.addWidget(self.le_description)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_2 = QtGui.QGroupBox(SubModelEditor)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.layout_dataset_filter = QtGui.QHBoxLayout()
        self.layout_dataset_filter.setObjectName("layout_dataset_filter")
        self.lbl_dataset_filter = QtGui.QLabel(self.groupBox_2)
        self.lbl_dataset_filter.setObjectName("lbl_dataset_filter")
        self.layout_dataset_filter.addWidget(self.lbl_dataset_filter)
        self.cbo_dataset_filter = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbo_dataset_filter.sizePolicy().hasHeightForWidth())
        self.cbo_dataset_filter.setSizePolicy(sizePolicy)
        self.cbo_dataset_filter.setObjectName("cbo_dataset_filter")
        self.layout_dataset_filter.addWidget(self.cbo_dataset_filter)
        self.verticalLayout_3.addLayout(self.layout_dataset_filter)
        self.lst_available = QtGui.QListWidget(self.groupBox_2)
        self.lst_available.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.lst_available.setObjectName("lst_available")
        self.verticalLayout_3.addWidget(self.lst_available)
        self.pb_add = QtGui.QPushButton(self.groupBox_2)
        self.pb_add.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/Images/arrow_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_add.setIcon(icon)
        self.pb_add.setObjectName("pb_add")
        self.verticalLayout_3.addWidget(self.pb_add)
        self.horizontalLayout_5.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(SubModelEditor)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tree_submodel_structure = QtGui.QTreeWidget(self.groupBox)
        self.tree_submodel_structure.setIndentation(5)
        self.tree_submodel_structure.setUniformRowHeights(True)
        self.tree_submodel_structure.setObjectName("tree_submodel_structure")
        self.verticalLayout.addWidget(self.tree_submodel_structure)
        self.lbl_active_variablelist = QtGui.QLabel(self.groupBox)
        self.lbl_active_variablelist.setObjectName("lbl_active_variablelist")
        self.verticalLayout.addWidget(self.lbl_active_variablelist)
        self.lst_selected = QtGui.QListWidget(self.groupBox)
        self.lst_selected.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.lst_selected.setObjectName("lst_selected")
        self.verticalLayout.addWidget(self.lst_selected)
        self.pb_remove = QtGui.QPushButton(self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Images/Images/arrow_left_red.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_remove.setIcon(icon1)
        self.pb_remove.setObjectName("pb_remove")
        self.verticalLayout.addWidget(self.pb_remove)
        self.horizontalLayout_5.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonBox = QtGui.QDialogButtonBox(SubModelEditor)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(SubModelEditor)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), SubModelEditor.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), SubModelEditor.reject)
        QtCore.QMetaObject.connectSlotsByName(SubModelEditor)

    def retranslateUi(self, SubModelEditor):
        SubModelEditor.setWindowTitle(QtGui.QApplication.translate("SubModelEditor", "Submodel Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SubModelEditor", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("SubModelEditor", "ID", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SubModelEditor", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("SubModelEditor", "Available Variables", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_dataset_filter.setText(QtGui.QApplication.translate("SubModelEditor", "Dataset filter:", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_add.setText(QtGui.QApplication.translate("SubModelEditor", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("SubModelEditor", "Submodel", None, QtGui.QApplication.UnicodeUTF8))
        self.tree_submodel_structure.headerItem().setText(0, QtGui.QApplication.translate("SubModelEditor", "id", None, QtGui.QApplication.UnicodeUTF8))
        self.tree_submodel_structure.headerItem().setText(1, QtGui.QApplication.translate("SubModelEditor", "name", None, QtGui.QApplication.UnicodeUTF8))
        self.tree_submodel_structure.headerItem().setText(2, QtGui.QApplication.translate("SubModelEditor", "type", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_active_variablelist.setText(QtGui.QApplication.translate("SubModelEditor", "type \"name\": 0 selected variables. ", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_remove.setText(QtGui.QApplication.translate("SubModelEditor", "Remove", None, QtGui.QApplication.UnicodeUTF8))

