create index accessibilities_year_zone_id on accessibilities (YEAR, ZONE_ID);

create temporary table tmp_table1
select a.YEAR as YEAR, a.GRID_ID as GRID_ID, a.DEVELOPMENT_TYPE_ID as DEVELOPMENT_TYPE_ID, b.ZONE_ID as ZONE_ID
from gridcells_exported as a left join WFRC_1997_baseyear.gridcells as b
  on a.GRID_ID = b.GRID_ID;

create index tmp_table1_year_zone_id on tmp_table1 (YEAR, ZONE_ID);

create temporary table tmp_table2
select a.YEAR as YEAR, a.DEVELOPMENT_TYPE_ID as DEVELOPMENT_TYPE_ID, a.ZONE_ID as ZONE_ID,
  b.HOME_ACCESS_TO_EMPLOYMENT_0,
  b.HOME_ACCESS_TO_EMPLOYMENT_1,
  b.HOME_ACCESS_TO_EMPLOYMENT_2,
  b.HOME_ACCESS_TO_EMPLOYMENT_3,
  b.WORK_ACCESS_TO_EMPLOYMENT_0,
  b.WORK_ACCESS_TO_EMPLOYMENT_1,
  b.WORK_ACCESS_TO_EMPLOYMENT_2,
  b.WORK_ACCESS_TO_EMPLOYMENT_3,
  b.HOME_ACCESS_TO_POPULATION_0,
  b.HOME_ACCESS_TO_POPULATION_1,
  b.HOME_ACCESS_TO_POPULATION_2,
  b.HOME_ACCESS_TO_POPULATION_3,
  b.WORK_ACCESS_TO_POPULATION_0,
  b.WORK_ACCESS_TO_POPULATION_1,
  b.WORK_ACCESS_TO_POPULATION_2,
  b.WORK_ACCESS_TO_POPULATION_3
from tmp_table1 as a left join accessibilities as b
  on a.YEAR = b.YEAR and a.ZONE_ID = b.ZONE_ID;

create index tmp_table2_year_devtype on tmp_table2 (YEAR, DEVELOPMENT_TYPE_ID);

create table accessibilities_by_devtype
select YEAR, DEVELOPMENT_TYPE_ID,
  avg(HOME_ACCESS_TO_EMPLOYMENT_0) as HOME_ACCESS_TO_EMPLOYMENT_0,
  avg(HOME_ACCESS_TO_EMPLOYMENT_1) as HOME_ACCESS_TO_EMPLOYMENT_1,
  avg(HOME_ACCESS_TO_EMPLOYMENT_2) as HOME_ACCESS_TO_EMPLOYMENT_2,
  avg(HOME_ACCESS_TO_EMPLOYMENT_3) as HOME_ACCESS_TO_EMPLOYMENT_3,
  avg(WORK_ACCESS_TO_EMPLOYMENT_0) as WORK_ACCESS_TO_EMPLOYMENT_0,
  avg(WORK_ACCESS_TO_EMPLOYMENT_1) as WORK_ACCESS_TO_EMPLOYMENT_1,
  avg(WORK_ACCESS_TO_EMPLOYMENT_2) as WORK_ACCESS_TO_EMPLOYMENT_2,
  avg(WORK_ACCESS_TO_EMPLOYMENT_3) as WORK_ACCESS_TO_EMPLOYMENT_3,
  avg(HOME_ACCESS_TO_POPULATION_0) as HOME_ACCESS_TO_POPULATION_0,
  avg(HOME_ACCESS_TO_POPULATION_1) as HOME_ACCESS_TO_POPULATION_1,
  avg(HOME_ACCESS_TO_POPULATION_2) as HOME_ACCESS_TO_POPULATION_2,
  avg(HOME_ACCESS_TO_POPULATION_3) as HOME_ACCESS_TO_POPULATION_3,
  avg(WORK_ACCESS_TO_POPULATION_0) as WORK_ACCESS_TO_POPULATION_0,
  avg(WORK_ACCESS_TO_POPULATION_1) as WORK_ACCESS_TO_POPULATION_1,
  avg(WORK_ACCESS_TO_POPULATION_2) as WORK_ACCESS_TO_POPULATION_2,
  avg(WORK_ACCESS_TO_POPULATION_3) as WORK_ACCESS_TO_POPULATION_3
from tmp_table2
group by YEAR, DEVELOPMENT_TYPE_ID;

create index access_by_devtype_year_devtype on accessibilities_by_devtype (YEAR, DEVELOPMENT_TYPE_ID);

drop table tmp_table1;
drop table tmp_table2;
