# Aggregate zone data to the small district level

DROP TABLE IF EXISTS distsml_2030;
CREATE TABLE distsml_2030 (distsml int, distmed int, distlrg int, county int);
     
ALTER TABLE distsml_2030
  ADD COLUMN dur_a int, ADD COLUMN iv_r_a double, 
  ADD COLUMN sf_c_a double, ADD COLUMN iv_c_a double, ADD COLUMN sf_i_a double, ADD COLUMN iv_i_a double, ADD COLUMN sf_g_a double, 
  ADD COLUMN iv_g_a double, ADD COLUMN lv_r_a double, ADD COLUMN lv_nr_a double, ADD COLUMN sf_tot_a double, ADD COLUMN lv_tot_a double, 
  ADD COLUMN js_hb_a double, ADD COLUMN js_nhb_a double, ADD COLUMN js_tot_a double,
  ADD COLUMN hhs_a double, ADD COLUMN pop_a double, ADD COLUMN wrkrs_a double, ADD COLUMN totinc_a double, ADD COLUMN child_a double, 
  ADD COLUMN ageh_a double, ADD COLUMN jobs_a double, ADD COLUMN hb_pct_a double, ADD COLUMN j_3p_a double,
  ADD COLUMN vr_r_a double, ADD COLUMN vr_nr_a double, ADD COLUMN hhsz_a double, ADD COLUMN hhin_a double,
  ADD COLUMN hae0_a double, ADD COLUMN hae1_a double, ADD COLUMN hae2_a double, ADD COLUMN hae3_a double, 
  ADD COLUMN hap0_a double, ADD COLUMN hap1_a double, ADD COLUMN hap2_a double, ADD COLUMN hap3_a double, 
  ADD COLUMN wae0_a double, ADD COLUMN wae1_a double, ADD COLUMN wae2_a double, ADD COLUMN wae3_a double, 
  ADD COLUMN wap0_a double, ADD COLUMN wap1_a double, ADD COLUMN wap2_a double, ADD COLUMN wap3_a double,
  
  ADD COLUMN dur_z int, ADD COLUMN iv_r_z double,
  ADD COLUMN sf_c_z double, ADD COLUMN iv_c_z double, ADD COLUMN sf_i_z double, ADD COLUMN iv_i_z double, ADD COLUMN sf_g_z double, 
  ADD COLUMN iv_g_z double, ADD COLUMN lv_r_z double, ADD COLUMN lv_nr_z double, ADD COLUMN sf_tot_z double, ADD COLUMN lv_tot_z double, 
  ADD COLUMN js_hb_z double, ADD COLUMN js_nhb_z double, ADD COLUMN js_tot_z double,
  ADD COLUMN hhs_z double, ADD COLUMN pop_z double, ADD COLUMN wrkrs_z double, ADD COLUMN totinc_z double, ADD COLUMN child_z double, 
  ADD COLUMN ageh_z double, ADD COLUMN jobs_z double, ADD COLUMN hb_pct_z double, ADD COLUMN j_3p_z double,
  ADD COLUMN vr_r_z double, ADD COLUMN vr_nr_z double, ADD COLUMN hhsz_z double, ADD COLUMN hhin_z double,
  ADD COLUMN hae0_z double, ADD COLUMN hae1_z double, ADD COLUMN hae2_z double, ADD COLUMN hae3_z double, 
  ADD COLUMN hap0_z double, ADD COLUMN hap1_z double, ADD COLUMN hap2_z double, ADD COLUMN hap3_z double, 
  ADD COLUMN wae0_z double, ADD COLUMN wae1_z double, ADD COLUMN wae2_z double, ADD COLUMN wae3_z double, 
  ADD COLUMN wap0_z double, ADD COLUMN wap1_z double, ADD COLUMN wap2_z double, ADD COLUMN wap3_z double,

  ADD COLUMN dur_d int, ADD COLUMN iv_r_d double, 
  ADD COLUMN sf_c_d double, ADD COLUMN iv_c_d double, ADD COLUMN sf_i_d double, ADD COLUMN iv_i_d double, ADD COLUMN sf_g_d double, 
  ADD COLUMN iv_g_d double, ADD COLUMN lv_r_d double, ADD COLUMN lv_nr_d double, ADD COLUMN sf_tot_d double, ADD COLUMN lv_tot_d double, 
  ADD COLUMN js_hb_d double, ADD COLUMN js_nhb_d double, ADD COLUMN js_tot_d double,
  ADD COLUMN hhs_d double, ADD COLUMN pop_d double, ADD COLUMN wrkrs_d double, ADD COLUMN totinc_d double, ADD COLUMN child_d double, 
  ADD COLUMN ageh_d double, ADD COLUMN jobs_d double, ADD COLUMN hb_pct_d double, ADD COLUMN j_3p_d double,
  ADD COLUMN vr_r_d double, ADD COLUMN vr_nr_d double, ADD COLUMN hhsz_d double, ADD COLUMN hhin_d double,
  ADD COLUMN hae0_d double, ADD COLUMN hae1_d double, ADD COLUMN hae2_d double, ADD COLUMN hae3_d double, 
  ADD COLUMN hap0_d double, ADD COLUMN hap1_d double, ADD COLUMN hap2_d double, ADD COLUMN hap3_d double, 
  ADD COLUMN wae0_d double, ADD COLUMN wae1_d double, ADD COLUMN wae2_d double, ADD COLUMN wae3_d double, 
  ADD COLUMN wap0_d double, ADD COLUMN wap1_d double, ADD COLUMN wap2_d double, ADD COLUMN wap3_d double,
  
  ADD COLUMN dur_dl int, ADD COLUMN sf_tot_dl double, ADD COLUMN hhs_dl double, ADD COLUMN pop_dl double, 
  ADD COLUMN jobs_dl double, ADD COLUMN hae1_dl double, ADD COLUMN lv_tot_dl double;

ALTER TABLE distsml_2030
  ADD COLUMN dur_Change_percent double,
  ADD COLUMN pop_Change_percent double, ADD COLUMN hhs_Change_percent double, 
  ADD COLUMN jobs_Change_percent double, ADD COLUMN sf_tot_Change_percent double,
  ADD COLUMN hae1_Change_percent double, ADD COLUMN lv_tot_Change_percent double,
  ADD COLUMN dur_Absolute_percent double,
  ADD COLUMN pop_Absolute_percent double, ADD COLUMN hhs_Absolute_percent double, 
  ADD COLUMN jobs_Absolute_percent double, ADD COLUMN sf_tot_Absolute_percent double,
  ADD COLUMN hae1_Absolute_percent double, ADD COLUMN lv_tot_Absolute_percent double;
  
CREATE INDEX distsml_2030_distsml
     ON distsml_2030 (distsml);
     
INSERT INTO distsml_2030
SELECT distsml AS distsml,
    MAX(distmed) AS distmed,
    MAX(distlrg) AS distlrg,
    MAX(county) AS county,
    SUM(dur_a) AS dur_a, 
    SUM(iv_r_a) AS iv_r_a, 
    SUM(sf_c_a) AS sf_c_a, 
    SUM(iv_c_a) AS iv_c_a, 
    SUM(sf_i_a) AS sf_i_a,
    SUM(iv_i_a) AS iv_i_a, 
    SUM(sf_g_a) AS sf_g_a, 
    SUM(iv_g_a) AS iv_g_a, 
    SUM(lv_r_a) AS lv_r_a, 
    SUM(lv_nr_a) AS lv_nr_a, 
    SUM(sf_tot_a) AS sf_tot_a, 
    SUM(lv_tot_a) AS lv_tot_a, 
    SUM(js_hb_a) AS js_hb_a, 
    SUM(js_nhb_a) AS js_nhb_a, 
    SUM(js_tot_a) AS js_tot_a, 
    SUM(hhs_a) AS hhs_a, 
    SUM(pop_a) AS pop_a, 
    SUM(wrkrs_a) AS wrkrs_a, 
    SUM(totinc_a) AS totinc_a, 
    SUM(child_a) AS child_a, 
    AVG(ageh_a) AS ageh_a, 
    SUM(jobs_a) AS jobs_a, 
    AVG(hb_pct_a) AS hb_pct_a, 
    SUM(j_3p_a) AS j_3p_a,
    NULL AS vr_r_a, 
    NULL AS vr_nr_a, 
    NULL AS hhsz_a,
    NULL AS hhin_a,
    AVG(hae0_a) AS hae0_a, 
    AVG(hae1_a) AS hae1_a, 
    AVG(hae2_a) AS hae2_a, 
    AVG(hae3_a) AS hae3_a,
    AVG(hap0_a) AS hap0_a, 
    AVG(hap1_a) AS hap1_a, 
    AVG(hap2_a) AS hap2_a, 
    AVG(hap3_a) AS hap3_a, 
    AVG(wae0_a) AS wae0_a, 
    AVG(wae1_a) AS wae1_a, 
    AVG(wae2_a) AS wae2_a, 
    AVG(wae3_a) AS wae3_a,
    AVG(wap0_a) AS wap0_a, 
    AVG(wap1_a) AS wap1_a, 
    AVG(wap2_a) AS wap2_a, 
    AVG(wap3_a) AS wap3_a,

    SUM(dur_z) AS dur_z, 
    SUM(iv_r_z) AS iv_r_z, 
    SUM(sf_c_z) AS sf_c_z, 
    SUM(iv_c_z) AS iv_c_z, 
    SUM(sf_i_z) AS sf_i_z,
    SUM(iv_i_z) AS iv_i_z, 
    SUM(sf_g_z) AS sf_g_z, 
    SUM(iv_g_z) AS iv_g_z, 
    SUM(lv_r_z) AS lv_r_z, 
    SUM(lv_nr_z) AS lv_nr_z, 
    SUM(sf_tot_z) AS sf_tot_z, 
    SUM(lv_tot_z) AS lv_tot_z, 
    SUM(js_hb_z) AS js_hb_z, 
    SUM(js_nhb_z) AS js_nhb_z, 
    SUM(js_tot_z) AS js_tot_z, 
    SUM(hhs_z) AS hhs_z, 
    SUM(pop_z) AS pop_z, 
    SUM(wrkrs_z) AS wrkrs_z, 
    SUM(totinc_z) AS totinc_z, 
    SUM(child_z) AS child_z, 
    AVG(ageh_z) AS ageh_z, 
    SUM(jobs_z) AS jobs_z, 
    AVG(hb_pct_z) AS hb_pct_z, 
    SUM(j_3p_z) AS j_3p_z,
    NULL AS vr_r_z, 
    NULL AS vr_nr_z, 
    NULL AS hhsz_z,
    NULL AS hhin_z,
    AVG(hae0_z) AS hae0_z, 
    AVG(hae1_z) AS hae1_z, 
    AVG(hae2_z) AS hae2_z, 
    AVG(hae3_z) AS hae3_z,
    AVG(hap0_z) AS hap0_z, 
    AVG(hap1_z) AS hap1_z, 
    AVG(hap2_z) AS hap2_z, 
    AVG(hap3_z) AS hap3_z, 
    AVG(wae0_z) AS wae0_z, 
    AVG(wae1_z) AS wae1_z, 
    AVG(wae2_z) AS wae2_z, 
    AVG(wae3_z) AS wae3_z,
    AVG(wap0_z) AS wap0_z, 
    AVG(wap1_z) AS wap1_z, 
    AVG(wap2_z) AS wap2_z, 
    AVG(wap3_z) AS wap3_z,
    
    SUM(dur_d) AS dur_d, 
    SUM(iv_r_d) AS iv_r_d, 
    SUM(sf_c_d) AS sf_c_d, 
    SUM(iv_c_d) AS iv_c_d, 
    SUM(sf_i_d) AS sf_i_d,
    SUM(iv_i_d) AS iv_i_d, 
    SUM(sf_g_d) AS sf_g_d, 
    SUM(iv_g_d) AS iv_g_d, 
    SUM(lv_r_d) AS lv_r_d, 
    SUM(lv_nr_d) AS lv_nr_d, 
    SUM(sf_tot_d) AS sf_tot_d, 
    SUM(lv_tot_d) AS lv_tot_d, 
    SUM(js_hb_d) AS js_hb_d, 
    SUM(js_nhb_d) AS js_nhb_d, 
    SUM(js_tot_d) AS js_tot_d, 
    SUM(hhs_d) AS hhs_d, 
    SUM(pop_d) AS pop_d, 
    SUM(wrkrs_d) AS wrkrs_d, 
    SUM(totinc_d) AS totinc_d, 
    SUM(child_d) AS child_d, 
    NULL AS ageh_d, 
    SUM(jobs_d) AS jobs_d, 
    NULL AS hb_pct_d, 
    SUM(j_3p_d) AS j_3p_d,
    NULL AS vr_r_d, 
    NULL AS vr_nr_d, 
    NULL AS hhsz_d,
    NULL AS hhin_d,
    AVG(hae0_d) AS hae0_d, 
    AVG(hae1_d) AS hae1_d, 
    AVG(hae2_d) AS hae2_d, 
    AVG(hae3_d) AS hae3_d,
    AVG(hap0_d) AS hap0_d, 
    AVG(hap1_d) AS hap1_d, 
    AVG(hap2_d) AS hap2_d,
    AVG(hap3_d) AS hap3_d, 
    AVG(wae0_d) AS wae0_d, 
    AVG(wae1_d) AS wae1_d, 
    AVG(wae2_d) AS wae2_d, 
    AVG(wae3_d) AS wae3_d,
    AVG(wap0_d) AS wap0_d, 
    AVG(wap1_d) AS wap1_d, 
    AVG(wap2_d) AS wap2_d, 
    AVG(wap3_d) AS wap3_d,
    
  NULL AS dur_dl, 
  NULL AS sf_tot_dl, 
  NULL AS hhs_dl, 
  NULL AS pop_dl, 
  NULL AS jobs_dl,
  NULL AS hae1_dl,
  NULL AS lv_tot_dl,
  
  NULL AS dur_Change_percent,
  NULL AS pop_Change_percent,
  NULL AS hhs_Change_percent,
  NULL AS jobs_Change_percent,
  NULL AS sf_tot_Change_percent,
  NULL AS hae1_Change_percent,
  NULL AS lv_tot_Change_percent,
  NULL AS dur_Change_percent,
  NULL AS pop_Absolute_percent,
  NULL AS hhs_Absolute_percent,
  NULL AS jobs_Absolute_percent,
  NULL AS sf_tot_Absolute_percent,
  NULL AS hae1_Absolute_percent,
  NULL AS lv_tot_Absolute_percent
FROM zones_2030
GROUP BY distsml;

update distsml_2030 
     set vr_r_a = 1 - (hhs_a/dur_a),
          vr_nr_a = 1 - (jobs_a/js_tot_a),
          vr_r_z = 1 - (hhs_z/dur_z),
          vr_nr_z = 1 - (jobs_z/js_tot_z),
          vr_r_d = (hhs_a/dur_a) - (hhs_z/dur_z),
          vr_nr_d = (jobs_a/js_tot_a) - (jobs_z/js_tot_z),
          ageh_d = ageh_z - ageh_d,
          hb_pct_d = hb_pct_z - hb_pct_a,
          hhsz_a = pop_a/hhs_a,
          hhsz_z = pop_z/hhs_z,
          hhsz_d = (pop_z/hhs_z) - (pop_a/hhs_a),
          hhin_a = totinc_a/hhs_a,
          hhin_z = totinc_z/hhs_z,
          hhin_d = (totinc_z/hhs_z) - (totinc_a/hhs_a);
     
UPDATE distsml_2030 AS a
     INNER JOIN WFRC_1997_output_2030_LRP.distsml_2030 AS LRP
          ON a.distsml=LRP.distsml
     SET  a.dur_dl    = a.dur_z    - LRP.dur_z,
          a.sf_tot_dl = a.sf_tot_z - LRP.sf_tot_z,
          a.hhs_dl    = a.hhs_z    - LRP.hhs_z,
          a.pop_dl    = a.pop_z    - LRP.pop_z,
          a.jobs_dl   = a.jobs_z   - LRP.jobs_z,
          a.hae1_dl   = a.hae1_z   - LRP.hae1_z,
          a.lv_tot_dl = a.lv_tot_z - LRP.lv_tot_z,
          a.pop_Change_percent = (a.pop_d - LRP.pop_d) / ABS(LRP.pop_d),
          a.hhs_Change_percent = (a.hhs_d - LRP.hhs_d) / ABS(LRP.hhs_d),
          a.jobs_Change_percent = (a.jobs_d - LRP.jobs_d) / ABS(LRP.jobs_d),
          a.dur_Change_percent = (a.dur_d - LRP.dur_d) / ABS(LRP.dur_d),
          a.sf_tot_Change_percent = (a.sf_tot_d - LRP.sf_tot_d) / ABS(LRP.sf_tot_d),
          a.hae1_Change_percent = (a.hae1_d - LRP.hae1_d) / ABS(LRP.hae1_d),
          a.lv_tot_Change_percent = (a.lv_tot_d - LRP.lv_tot_d) / ABS(LRP.lv_tot_d),
          a.pop_Absolute_percent = (a.pop_z - LRP.pop_z) / ABS(LRP.pop_z),
          a.hhs_Absolute_percent = (a.hhs_z - LRP.hhs_z) / ABS(LRP.hhs_z),
          a.jobs_Absolute_percent = (a.jobs_z - LRP.jobs_z) / ABS(LRP.jobs_z),
          a.dur_Absolute_percent = (a.dur_z - LRP.dur_z) / ABS(LRP.dur_z),
          a.sf_tot_Absolute_percent = (a.sf_tot_z - LRP.sf_tot_z) / ABS(LRP.sf_tot_z),
          a.hae1_Absolute_percent = (a.hae1_z - LRP.hae1_z) / ABS(LRP.hae1_z),
          a.lv_tot_Absolute_percent = (a.lv_tot_z - LRP.lv_tot_z) / ABS(LRP.lv_tot_z);

# Create a table of comparisons with census and adopted-forecast data

DROP TABLE IF EXISTS distsml_comparisons;
CREATE TABLE distsml_comparisons
     SELECT a.distsml AS distsml,
        (LN(a.dur_z/a.dur_a))/(2030 - 1997) AS dur_aarc_u,
        (LN(b.census_residential_units_2000/b.census_residential_units_1990))/10 AS dur_aarc_c,
        (LN(a.hhs_z/a.hhs_a))/(2030 - 1997) AS hhs_aarc_u,
        (LN(b.census_households_2000/b.census_households_1990))/10 AS hhs_aarc_c, 
        (LN(a.j_3p_z/a.j_3p_a))/(2030 - 1997) AS jobs_aarc_u,
        (LN(b.census_employment_2001/b.census_employment_1990))/10 AS jobs_aarc_c,
        (LN(a.pop_z/a.pop_a))/(2030 - 1997) AS pop_aarc_u,
        (LN(b.census_population_2000/b.census_population_1990))/10 AS pop_aarc_c,
        (a.dur_z-b.old_method_residential_units_2030) AS dif_DWL,
        (a.hhs_z-b.old_method_households_2030) AS dif_HH,
        (a.j_3p_z-b.old_method_employment_2030) AS dif_EMP,
        (a.pop_z-b.old_method_population_2030) AS dif_POP
     FROM distsml_2030 AS a 
     INNER JOIN WFRC_1997_baseyear.small_districts AS b
          ON a.distsml = b.smalldst;

CREATE INDEX distsml_comparisons_distsml 
     on distsml_comparisons (distsml);

ALTER TABLE distsml_comparisons
     ADD COLUMN dif_dur_aarc double(25,8),
     ADD COLUMN dif_hhs_aarc double(25,8),
     ADD COLUMN dif_jobs_aarc double(25,8),
     ADD COLUMN dif_pop_aarc double(25,8);

UPDATE distsml_comparisons
     SET dif_dur_aarc=(dur_aarc_u-dur_aarc_c),
        dif_hhs_aarc=(hhs_aarc_u-hhs_aarc_c),
        dif_jobs_aarc=(jobs_aarc_u-jobs_aarc_c),
        dif_pop_aarc=(pop_aarc_u-pop_aarc_c);
