#
# UrbanSim software. Copyright (C) 1998-2007 University of Washington
# 
# You can redistribute this program and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation
# (http://www.gnu.org/copyleft/gpl.html).
# 
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the file LICENSE.html for copyright
# and licensing information, and the file ACKNOWLEDGMENTS.html for funding and
# other acknowledgments.
#


import os
import time, sys

from opus_core.opus_package import OpusPackage

nightly_package_path = OpusPackage().get_path_for_package('nightly')
html_file_path = os.path.join(nightly_package_path, 'release', 'latest_nightly_build.html')

version_build = sys.argv[1]

html_string = """
<!-- This file is automatically generated. See write_nightly_build_html. -->
    <tr style="background-color: #FFFFCC" bgcolor="#FFFFCC">
        <td>
            Nightly<br>
            (%(datetime)s)
        </td>
        <td>
            <a href="http://www.urbansim.org/opus/nightly_release/docs/index.shtml">on-line documentation</a><br>
            <a href="http://www.urbansim.org/opus/nightly_release/installers/opus-%(version_build)s.win32.exe">Windows</a><br>
            <a href="http://www.urbansim.org/opus/nightly_release/installers/opus-%(version_build)s.tar.gz">Unix/Linux</a>
        </td>
        <td>
            <a href="http://www.urbansim.org/opus/nightly_release/docs/userguide.pdf">pdf format</a><br>
            <a href="http://www.urbansim.org/opus/nightly_release/docs/html/userguide">html format</a><br>
            <a href="http://www.urbansim.org/opus/nightly_release/docs/release_notes.html">release notes</a>
        </td>
        <td>
            <a href="http://www.urbansim.org/opus/nightly_release/eugene_1980_baseyear_cache.zip">baseyear cache</a><br>
            <a href="http://www.urbansim.org/opus/nightly_release/eugene_opus_package.zip">"eugene" package</a><br>
            <a href="http://www.urbansim.org/wiki/external/index.php/Nightly:Install_Eugene_Tutorial">Eugene Tutorial</a>
        </td>
    </tr>
<!-- End automatically generated file. -->
""" % {
    'datetime': time.asctime(time.localtime(time.time())), 
    'version_build': version_build,
    }


html_file = open(html_file_path, 'w')
try:
    html_file.write(html_string)
    
finally:
    html_file.close()